import * as stylex from "@stylexjs/stylex";
import { colors, radii, shadows, space, typography } from "@foldworks/ui/tokens.stylex";

export const styles = stylex.create({
  root: {
    color: colors.foreground,
    display: "flex",
    flexDirection: "column",
    gap: space.lg,
    minWidth: 0,
    padding: {
      default: "24px",
      "@media (max-width: 760px)": "12px",
    },
  },
  intro: {
    alignItems: "flex-end",
    display: "flex",
    gap: space.xl,
    justifyContent: "space-between",
  },
  introCopy: {
    maxWidth: "720px",
  },
  eyebrow: {
    color: colors.primary,
    fontSize: typography.sizeXs,
    fontWeight: typography.weightSemibold,
    letterSpacing: "0.09em",
    textTransform: "uppercase",
  },
  introTitle: {
    fontSize: "24px",
    fontWeight: typography.weightSemibold,
    letterSpacing: "-0.035em",
    lineHeight: 1.2,
    margin: "5px 0 7px",
  },
  introText: {
    color: colors.foregroundMuted,
    fontSize: typography.sizeMd,
    lineHeight: 1.6,
    margin: 0,
  },
  live: {
    alignItems: "center",
    color: colors.foregroundMuted,
    display: {
      default: "flex",
      "@media (max-width: 760px)": "none",
    },
    fontSize: typography.sizeSm,
    gap: "7px",
    whiteSpace: "nowrap",
  },
  liveDot: {
    backgroundColor: colors.success,
    borderRadius: radii.full,
    boxShadow: `0 0 0 3px color-mix(in oklch, ${colors.success} 16%, transparent)`,
    height: "7px",
    width: "7px",
  },
  workbench: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.lg,
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: shadows.panel,
    display: "grid",
    gridTemplateColumns: {
      default: "224px minmax(420px, 1fr) 224px",
      "@media (max-width: 1060px)": "210px minmax(0, 1fr)",
      "@media (max-width: 680px)": "minmax(0, 1fr)",
    },
    minHeight: "610px",
    minWidth: 0,
    overflow: "hidden",
  },
  sidebar: {
    borderRightColor: colors.border,
    borderRightStyle: "solid",
    borderRightWidth: "1px",
    display: {
      default: "flex",
      "@media (max-width: 680px)": "none",
    },
    flexDirection: "column",
    minWidth: 0,
    padding: space.md,
  },
  repo: {
    alignItems: "center",
    display: "flex",
    fontSize: typography.sizeMd,
    fontWeight: typography.weightSemibold,
    gap: space.sm,
    marginBottom: space.md,
    minHeight: "28px",
  },
  repoIcon: {
    alignItems: "center",
    backgroundColor: colors.foreground,
    borderRadius: radii.sm,
    color: colors.background,
    display: "inline-flex",
    height: "24px",
    justifyContent: "center",
    width: "24px",
  },
  search: {
    alignItems: "center",
    backgroundColor: colors.surfaceSubtle,
    borderColor: colors.border,
    borderRadius: radii.md,
    borderStyle: "solid",
    borderWidth: "1px",
    color: colors.foregroundMuted,
    display: "flex",
    fontSize: typography.sizeSm,
    gap: space.sm,
    height: "32px",
    padding: "0 9px",
  },
  switcher: {
    backgroundColor: colors.surfaceSubtle,
    borderRadius: radii.md,
    display: "grid",
    gap: "2px",
    gridTemplateColumns: "repeat(3, 1fr)",
    margin: "9px 0 12px",
    padding: "3px",
  },
  switchItem: {
    borderRadius: radii.sm,
    color: colors.foregroundMuted,
    fontSize: typography.sizeXs,
    padding: "5px 3px",
    textAlign: "center",
  },
  switchActive: {
    backgroundColor: colors.surface,
    boxShadow: shadows.control,
    color: colors.foreground,
    fontWeight: typography.weightMedium,
  },
  sectionLabel: {
    color: colors.foregroundMuted,
    fontSize: "10px",
    fontWeight: typography.weightSemibold,
    letterSpacing: "0.07em",
    margin: "10px 6px 5px",
    textTransform: "uppercase",
  },
  nav: {
    display: "flex",
    flexDirection: "column",
    gap: "1px",
  },
  navItem: {
    alignItems: "center",
    borderRadius: radii.sm,
    color: colors.foregroundMuted,
    display: "grid",
    fontSize: typography.sizeSm,
    gap: "7px",
    gridTemplateColumns: "15px minmax(0, 1fr)",
    minHeight: "28px",
    padding: "4px 7px",
  },
  navSelected: {
    backgroundColor: colors.selection,
    color: colors.selectionForeground,
    fontWeight: typography.weightMedium,
  },
  navText: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  main: {
    backgroundColor: colors.canvas,
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
  },
  mainHeader: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderBottomColor: colors.border,
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    display: "flex",
    gap: space.md,
    justifyContent: "space-between",
    minHeight: "49px",
    padding: "0 16px",
  },
  path: {
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: typography.sizeXs,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  tabs: {
    display: "flex",
    flexShrink: 0,
    gap: "2px",
  },
  tab: {
    borderRadius: radii.sm,
    color: colors.foregroundMuted,
    fontSize: typography.sizeSm,
    padding: "5px 8px",
  },
  tabActive: {
    backgroundColor: colors.selection,
    color: colors.selectionForeground,
    fontWeight: typography.weightMedium,
  },
  content: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    gap: space.md,
    minHeight: 0,
    padding: {
      default: "22px",
      "@media (max-width: 760px)": "12px",
    },
  },
  diffSwitcher: {
    alignSelf: "flex-start",
    backgroundColor: colors.surfaceSubtle,
    borderColor: colors.border,
    borderRadius: radii.md,
    borderStyle: "solid",
    borderWidth: "1px",
    display: "flex",
    gap: "2px",
    padding: "3px",
  },
  codeCard: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.md,
    borderStyle: "solid",
    borderWidth: "1px",
    minWidth: 0,
    overflow: "hidden",
  },
  codeHeader: {
    alignItems: "center",
    backgroundColor: colors.surfaceSubtle,
    borderBottomColor: colors.border,
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    color: colors.foregroundMuted,
    display: "flex",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: "10px",
    justifyContent: "space-between",
    padding: "8px 11px",
  },
  code: {
    display: "flex",
    flexDirection: "column",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: "11px",
    lineHeight: 1.65,
    margin: 0,
    overflow: "auto",
    padding: "8px 0 14px",
  },
  line: {
    display: "grid",
    gridTemplateColumns: "42px minmax(max-content, 1fr)",
    minHeight: "19px",
    paddingRight: space.md,
  },
  lineNumber: {
    color: colors.foregroundMuted,
    opacity: 0.62,
    paddingRight: "10px",
    textAlign: "right",
    userSelect: "none",
  },
  lineCode: {
    paddingLeft: "11px",
    whiteSpace: "pre",
  },
  fileLine: {
    backgroundColor: colors.surfaceSubtle,
    borderTopColor: colors.border,
    borderTopStyle: "solid",
    borderTopWidth: "1px",
    fontWeight: typography.weightSemibold,
    marginTop: "7px",
  },
  hunkLine: {
    backgroundColor: colors.infoSurface,
    color: colors.info,
  },
  addedLine: {
    backgroundColor: colors.successSurface,
    color: colors.success,
  },
  removedLine: {
    backgroundColor: colors.dangerSurface,
    color: colors.danger,
  },
  inspector: {
    borderLeftColor: colors.border,
    borderLeftStyle: "solid",
    borderLeftWidth: "1px",
    display: {
      default: "flex",
      "@media (max-width: 1060px)": "none",
    },
    flexDirection: "column",
    gap: space.lg,
    minWidth: 0,
    padding: "17px",
  },
  inspectorTitle: {
    fontSize: typography.sizeLg,
    fontWeight: typography.weightSemibold,
    margin: 0,
    overflowWrap: "anywhere",
  },
  inspectorText: {
    color: colors.foregroundMuted,
    fontSize: typography.sizeSm,
    lineHeight: 1.55,
    margin: "4px 0 0",
  },
  factGroup: {
    display: "flex",
    flexDirection: "column",
  },
  factTitle: {
    color: colors.foregroundMuted,
    fontSize: "10px",
    fontWeight: typography.weightSemibold,
    letterSpacing: "0.07em",
    marginBottom: "5px",
    textTransform: "uppercase",
  },
  fact: {
    borderBottomColor: colors.border,
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    display: "flex",
    fontSize: typography.sizeSm,
    gap: space.md,
    justifyContent: "space-between",
    padding: "7px 0",
  },
  factValue: {
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    overflowWrap: "anywhere",
    textAlign: "right",
  },
  chips: {
    display: "flex",
    flexWrap: "wrap",
    gap: "5px",
  },
  chip: {
    backgroundColor: colors.surfaceSubtle,
    borderRadius: radii.sm,
    color: colors.foregroundMuted,
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: "10px",
    padding: "3px 6px",
  },
  footnote: {
    color: colors.foregroundMuted,
    fontSize: typography.sizeSm,
    lineHeight: 1.6,
    margin: 0,
  },
  command: {
    backgroundColor: colors.surfaceSubtle,
    borderColor: colors.border,
    borderRadius: radii.sm,
    borderStyle: "solid",
    borderWidth: "1px",
    color: colors.foreground,
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: typography.sizeXs,
    padding: "3px 6px",
  },
});
