import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  viewport: {
    backgroundColor: "var(--foldworks-ui-canvas)",
    minHeight: 0,
    overflow: "hidden",
    padding: { default: "18px", "@media (max-width: 820px)": "10px" },
  },
  card: {
    backgroundColor: "var(--foldworks-ui-surface)",
    borderColor: "var(--foldworks-ui-border)",
    borderRadius: "12px",
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: "var(--foldworks-ui-shadow-sm)",
    display: "grid",
    gridTemplateRows: "auto auto minmax(0, 1fr)",
    height: "100%",
    minHeight: 0,
    overflow: "hidden",
    position: "relative",
  },
  viewBar: {
    alignItems: "center",
    borderBottomColor: "var(--foldworks-ui-border)",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    display: "flex",
    flexWrap: "wrap",
    gap: "8px",
    padding: "10px 12px",
  },
  button: {
    alignItems: "center",
    backgroundColor: "var(--foldworks-ui-surface)",
    borderColor: "var(--foldworks-ui-border-strong)",
    borderRadius: "7px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--foldworks-ui-foreground)",
    cursor: "pointer",
    display: "inline-flex",
    fontFamily: "inherit",
    fontSize: "12px",
    fontWeight: 650,
    gap: "7px",
    height: "32px",
    padding: "0 10px",
  },
  primaryButton: {
    backgroundColor: "var(--foldworks-ui-primary)",
    borderColor: "var(--foldworks-ui-primary)",
    color: "var(--foldworks-ui-primary-foreground)",
  },
  search: {
    backgroundColor: "var(--foldworks-ui-surface)",
    borderColor: "var(--foldworks-ui-border-strong)",
    borderRadius: "7px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--foldworks-ui-foreground)",
    fontFamily: "inherit",
    fontSize: "12px",
    height: "32px",
    minWidth: "190px",
    padding: "0 10px",
  },
  spacer: { flexGrow: 1 },
  chipBar: {
    alignItems: "center",
    backgroundColor: "var(--foldworks-ui-surface-subtle)",
    borderBottomColor: "var(--foldworks-ui-border)",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    display: "flex",
    gap: "8px",
    minHeight: "40px",
    padding: "6px 12px",
  },
  chip: {
    backgroundColor: "var(--foldworks-ui-surface)",
    borderColor: "var(--foldworks-ui-border)",
    borderRadius: "999px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--foldworks-ui-foreground-muted)",
    fontSize: "11px",
    padding: "5px 9px",
  },
  bulk: {
    alignItems: "center",
    color: "var(--foldworks-ui-foreground)",
    display: "flex",
    fontSize: "12px",
    fontWeight: 700,
    gap: "8px",
  },
  tableFrame: { minHeight: 0, overflow: "hidden" },
  person: { alignItems: "center", display: "flex", gap: "9px", minWidth: 0 },
  avatar: {
    alignItems: "center",
    backgroundColor: "var(--foldworks-ui-info-surface)",
    borderRadius: "999px",
    color: "var(--foldworks-ui-info)",
    display: "inline-flex",
    flexShrink: 0,
    fontSize: "9px",
    fontWeight: 800,
    height: "24px",
    justifyContent: "center",
    width: "24px",
  },
  company: { alignItems: "center", display: "flex", gap: "7px", minWidth: 0 },
  companyIcon: {
    alignItems: "center",
    backgroundColor: "var(--foldworks-ui-surface-subtle)",
    borderRadius: "5px",
    color: "var(--foldworks-ui-foreground-muted)",
    display: "inline-flex",
    flexShrink: 0,
    height: "20px",
    justifyContent: "center",
    width: "20px",
  },
  email: { color: "var(--foldworks-ui-link, #2563eb)", textDecoration: "none" },
  status: {
    alignItems: "center",
    display: "inline-flex",
    fontSize: "11px",
    gap: "6px",
  },
  dot: { borderRadius: "999px", height: "7px", width: "7px" },
  strong: { backgroundColor: "var(--foldworks-ui-success)" },
  warm: { backgroundColor: "var(--foldworks-ui-warning)" },
  weak: { backgroundColor: "var(--foldworks-ui-danger)" },
  muted: { color: "var(--foldworks-ui-foreground-muted)" },
  actionButton: {
    backgroundColor: "transparent",
    borderWidth: 0,
    color: "var(--foldworks-ui-foreground-muted)",
    cursor: "pointer",
    padding: "5px",
  },
  detail: {
    backgroundColor: "var(--foldworks-ui-surface)",
    borderLeftColor: "var(--foldworks-ui-border-strong)",
    borderLeftStyle: "solid",
    borderLeftWidth: "1px",
    bottom: 0,
    boxShadow: "var(--foldworks-ui-shadow-lg)",
    display: "flex",
    flexDirection: "column",
    padding: "20px",
    position: "absolute",
    right: 0,
    top: 0,
    width: { default: "360px", "@media (max-width: 640px)": "min(360px, 92vw)" },
    zIndex: 20,
  },
  detailHeader: { alignItems: "center", display: "flex", justifyContent: "space-between" },
  detailTitle: { fontSize: "18px", margin: 0 },
  detailClose: { color: "var(--foldworks-ui-foreground-muted)", padding: "6px" },
  detailCompany: { color: "var(--foldworks-ui-foreground-muted)", fontSize: "12px", marginTop: "6px" },
  detailList: { display: "grid", gap: "14px", marginTop: "28px" },
  detailLabel: { color: "var(--foldworks-ui-foreground-muted)", fontSize: "10px", fontWeight: 750, textTransform: "uppercase" },
  detailValue: { color: "var(--foldworks-ui-foreground)", fontSize: "13px", marginTop: "3px" },
});
