import * as stylex from "@stylexjs/stylex";

export const className = (...values: ReadonlyArray<stylex.StyleXStyles>) =>
  stylex.props(...values).className ?? "";

export const nodeTransitionClass = stylex.viewTransitionClass({
  group: {
    animationDuration: "260ms",
    animationTimingFunction: "cubic-bezier(0.22, 1, 0.36, 1)",
  },
});

export const styles = stylex.create({
  app: {
    backgroundColor: "var(--foldworks-ui-canvas)",
    color: "var(--foldworks-ui-foreground)",
    display: "grid",
    fontFamily:
      'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    gridTemplateColumns: {
      default: "252px minmax(0, 1fr)",
      "@media (max-width: 820px)": "1fr",
    },
    height: "100vh",
    overflow: "hidden",
  },
  appFormPreview: {
    gridTemplateColumns: "1fr",
  },
  palette: {
    backgroundColor: "var(--foldworks-ui-sidebar)",
    borderRightColor: "var(--foldworks-ui-sidebar-border)",
    borderRightStyle: "solid",
    borderRightWidth: "1px",
    color: "var(--foldworks-ui-foreground)",
    display: {
      default: "flex",
      "@media (max-width: 820px)": "none",
    },
    flexDirection: "column",
    minHeight: 0,
    overflowY: "auto",
    padding: "16px 14px",
    zIndex: 4,
  },
  brandRow: {
    alignItems: "center",
    display: "flex",
    gap: "10px",
    marginBottom: "20px",
    paddingLeft: "4px",
  },
  demoNav: {
    display: "flex",
    flexDirection: "column",
    gap: "5px",
    marginBottom: "24px",
  },
  demoNavItem: {
    alignItems: "center",
    backgroundColor: {
      default: "transparent",
      ":hover": "var(--foldworks-ui-brand-surface)",
    },
    borderWidth: 0,
    borderRadius: "9px",
    color: {
      default: "var(--foldworks-ui-foreground-muted)",
      ":hover": "var(--foldworks-ui-brand-foreground)",
    },
    cursor: "pointer",
    display: "flex",
    fontFamily: "inherit",
    fontSize: "13px",
    fontWeight: 600,
    gap: "9px",
    minHeight: "36px",
    outline: {
      default: "none",
      ":focus-visible": "2px solid var(--foldworks-ui-focus)",
    },
    outlineOffset: "2px",
    paddingLeft: "10px",
    paddingRight: "10px",
    textAlign: "left",
    textDecoration: "none",
    transform: {
      default: "translateX(0) scale(1)",
      ":hover": "translateX(2px) scale(1)",
      ":active": "translateX(1px) scale(0.985)",
    },
    transitionDuration: "150ms",
    transitionProperty: "background-color, color, transform",
    transitionTimingFunction: "var(--foldworks-ui-ease-out)",
  },
  demoNavItemActive: {
    backgroundColor: "var(--foldworks-ui-brand-surface)",
    color: "var(--foldworks-ui-brand-foreground)",
  },
  brandMark: {
    alignItems: "center",
    backgroundColor: "var(--foldworks-ui-brand)",
    backgroundImage: "linear-gradient(145deg, var(--foldworks-ui-brand), color-mix(in oklch, var(--foldworks-ui-brand) 68%, var(--foldworks-ui-info)))",
    borderRadius: "9px",
    color: "var(--foldworks-ui-primary-foreground)",
    display: "flex",
    fontSize: "18px",
    fontWeight: 800,
    height: "32px",
    justifyContent: "center",
    boxShadow: "var(--foldworks-ui-shadow-interactive)",
    width: "32px",
  },
  brand: {
    fontSize: "15px",
    fontWeight: 750,
    letterSpacing: "-0.01em",
    margin: 0,
  },
  paletteLabel: {
    color: "var(--foldworks-ui-foreground-subtle)",
    fontSize: "10px",
    fontWeight: 700,
    letterSpacing: "0.12em",
    marginBottom: "10px",
    marginTop: 0,
    paddingLeft: "6px",
    textTransform: "uppercase",
  },
  paletteList: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    margin: 0,
    padding: 0,
  },
  gridFeatureList: {
    color: "var(--foldworks-ui-foreground-muted)",
    fontSize: "12px",
    lineHeight: 1.45,
  },
  paletteItem: {
    alignItems: "center",
    backgroundColor: {
      default: "var(--foldworks-ui-background)",
      ":hover": "var(--foldworks-ui-surface-subtle)",
    },
    borderColor: {
      default: "var(--foldworks-ui-border)",
      ":hover": "var(--foldworks-ui-border-strong)",
    },
    borderRadius: "10px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--foldworks-ui-foreground)",
    cursor: "grab",
    display: "grid",
    gap: "11px",
    gridTemplateColumns: "34px 1fr 16px",
    minHeight: "58px",
    outline: {
      default: "none",
      ":focus-visible": "2px solid var(--foldworks-ui-focus)",
    },
    outlineOffset: "2px",
    padding: "9px 10px",
    transitionDuration: "150ms",
    transitionProperty: "background-color, border-color, transform",
    transitionTimingFunction: "ease-out",
    transform: {
      default: "translateX(0)",
      ":hover": "translateY(-1px)",
      ":active": "scale(0.99)",
    },
  },
  paletteItemDragging: {
    opacity: 0.42,
  },
  paletteIcon: {
    alignItems: "center",
    backgroundColor: "var(--foldworks-ui-surface-subtle)",
    borderRadius: "9px",
    display: "flex",
    fontSize: "16px",
    fontWeight: 800,
    height: "34px",
    justifyContent: "center",
    width: "34px",
  },
  paletteName: {
    fontSize: "13px",
    fontWeight: 700,
    margin: 0,
  },
  paletteDescription: {
    color: "var(--foldworks-ui-foreground-muted)",
    fontSize: "11px",
    lineHeight: 1.35,
    marginBottom: 0,
    marginTop: "2px",
  },
  paletteHandle: {
    color: "var(--foldworks-ui-foreground-subtle)",
    fontSize: "15px",
    letterSpacing: "-2px",
  },
  paletteHint: {
    borderColor: "var(--foldworks-ui-border)",
    borderStyle: "solid",
    borderWidth: "1px 0 0",
    color: "var(--foldworks-ui-foreground-muted)",
    fontSize: "11px",
    lineHeight: 1.5,
    marginBottom: 0,
    marginTop: "auto",
    padding: "20px 6px 0",
  },
  workspace: {
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr)",
    minHeight: 0,
    minWidth: 0,
  },
  toolbar: {
    alignItems: "center",
    backgroundColor: "var(--foldworks-ui-background)",
    borderBottomColor: "var(--foldworks-ui-border)",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    display: "flex",
    gap: "16px",
    justifyContent: "space-between",
    padding: "0 24px",
    zIndex: 3,
  },
  toolbarTitle: {
    fontSize: "16px",
    fontWeight: 760,
    letterSpacing: "-0.02em",
    margin: 0,
  },
  toolbarMeta: {
    color: "var(--foldworks-ui-foreground-muted)",
    fontSize: "12px",
    marginBottom: 0,
    marginTop: "3px",
  },
  toolbarActions: {
    alignItems: "center",
    display: "flex",
    gap: "10px",
  },
  status: {
    alignItems: "center",
    backgroundColor: "var(--foldworks-ui-success-surface)",
    borderRadius: "999px",
    color: "var(--foldworks-ui-success)",
    display: "flex",
    fontSize: "12px",
    fontWeight: 700,
    gap: "7px",
    padding: "7px 11px",
  },
  statusDot: {
    backgroundColor: "var(--foldworks-ui-success)",
    borderRadius: "999px",
    height: "7px",
    width: "7px",
  },
  quietButton: {
    backgroundColor: {
      default: "var(--foldworks-ui-surface)",
      ":hover": "var(--foldworks-ui-surface-hover)",
    },
    borderColor: "var(--foldworks-ui-input)",
    borderRadius: "9px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--foldworks-ui-foreground)",
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: "12px",
    fontWeight: 700,
    minHeight: "36px",
    outline: {
      default: "none",
      ":focus-visible": "2px solid var(--foldworks-ui-focus)",
    },
    outlineOffset: "2px",
    paddingLeft: "13px",
    paddingRight: "13px",
  },
  quietBadge: {
    backgroundColor: "var(--foldworks-ui-surface-subtle)",
    borderColor: "var(--foldworks-ui-border)",
    borderRadius: "9px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--foldworks-ui-foreground-muted)",
    fontSize: "11px",
    fontWeight: 700,
    padding: "8px 11px",
  },
  canvasViewport: {
    backgroundColor: "var(--foldworks-ui-canvas)",
    backgroundImage:
      "radial-gradient(circle, color-mix(in oklch, var(--foldworks-ui-foreground-subtle) 32%, transparent) 1px, transparent 1px)",
    backgroundPosition: "0 0",
    backgroundSize: "12px 12px",
    minHeight: 0,
    overflow: "auto",
    position: "relative",
  },
  canvas: {
    marginLeft: "auto",
    marginRight: "auto",
    position: "relative",
  },
  edgeLayer: {
    inset: 0,
    overflow: "visible",
    pointerEvents: "none",
    position: "absolute",
  },
  edgePath: {
    fill: "none",
    stroke: "var(--foldworks-ui-border-strong)",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    strokeWidth: 1.5,
    transitionDuration: "240ms",
    transitionProperty: "opacity, stroke, d",
    transitionTimingFunction: "cubic-bezier(0.22, 1, 0.36, 1)",
  },
  edgePathActive: {
    stroke: "var(--foldworks-ui-success)",
    strokeWidth: 2.5,
  },
  edgePathDraggingSubtree: {
    opacity: 0.5,
    stroke: "var(--foldworks-ui-foreground-subtle)",
    strokeDasharray: "4 5",
  },
  junction: {
    fill: "var(--foldworks-ui-surface)",
    stroke: "var(--foldworks-ui-border-strong)",
    strokeWidth: 1.5,
  },
  junctionDraggingSubtree: {
    fill: "var(--foldworks-ui-surface-subtle)",
    opacity: 0.5,
    strokeDasharray: "2 2",
  },
  branchLabel: {
    backgroundColor: "var(--foldworks-ui-surface)",
    borderColor: "var(--foldworks-ui-border)",
    borderRadius: "999px",
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: "var(--foldworks-ui-shadow-sm)",
    color: "var(--foldworks-ui-foreground)",
    fontSize: "10px",
    fontWeight: 750,
    minWidth: "62px",
    padding: "4px 10px",
    pointerEvents: "none",
    position: "absolute",
    textAlign: "center",
    transform: "translate(-50%, -50%)",
    whiteSpace: "nowrap",
    zIndex: 2,
  },
  branchLabelDraggingSubtree: {
    backgroundColor: "color-mix(in oklch, var(--foldworks-ui-surface-subtle) 84%, transparent)",
    borderStyle: "dashed",
    boxShadow: "none",
    opacity: 0.58,
  },
  edgeLabel: {
    backgroundColor: "var(--foldworks-ui-surface)",
    borderColor: "var(--foldworks-ui-border)",
    borderRadius: "999px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--foldworks-ui-foreground-muted)",
    fontSize: "10px",
    fontWeight: 700,
    left: 0,
    padding: "3px 7px",
    pointerEvents: "none",
    position: "absolute",
    top: 0,
    transform: "translate(-50%, -50%)",
    whiteSpace: "nowrap",
    zIndex: 1,
  },
  edgeTargetZone: {
    alignItems: "center",
    display: "flex",
    height: "54px",
    justifyContent: "center",
    left: 0,
    position: "absolute",
    top: 0,
    transform: "translate(-50%, -50%)",
    width: "72px",
    zIndex: 3,
  },
  edgeTarget: {
    alignItems: "center",
    backgroundColor: {
      default: "color-mix(in oklch, var(--foldworks-ui-surface) 82%, transparent)",
      ":hover": "var(--foldworks-ui-primary)",
    },
    borderColor: {
      default: "var(--foldworks-ui-border-strong)",
      ":hover": "var(--foldworks-ui-primary)",
    },
    borderRadius: "999px",
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: "var(--foldworks-ui-shadow-sm)",
    color: {
      default: "var(--foldworks-ui-foreground-muted)",
      ":hover": "var(--foldworks-ui-primary-foreground)",
    },
    cursor: "pointer",
    display: "flex",
    fontFamily: "inherit",
    fontSize: "17px",
    fontWeight: 500,
    height: "28px",
    justifyContent: "center",
    opacity: {
      default: 0.2,
      ":hover": 1,
      ":focus-visible": 1,
    },
    outline: {
      default: "none",
      ":focus-visible": "2px solid var(--foldworks-ui-focus)",
    },
    outlineOffset: "3px",
    transform: "scale(0.9)",
    transitionDuration: "160ms",
    transitionProperty: "opacity, transform, background-color, border-color",
    transitionTimingFunction: "cubic-bezier(0.22, 1, 0.36, 1)",
    width: "28px",
    zIndex: 2,
  },
  edgeTargetDragging: {
    backgroundColor: "var(--foldworks-ui-drop-target)",
    borderColor: "var(--foldworks-ui-drop-target-border)",
    color: "var(--foldworks-ui-selection-foreground)",
    height: "34px",
    opacity: 0.88,
    transform: "scale(1)",
    width: "34px",
  },
  edgeTargetActive: {
    backgroundColor: {
      default: "var(--foldworks-ui-drop-target-active)",
      ":hover": "var(--foldworks-ui-drop-target-active)",
    },
    borderColor: {
      default: "var(--foldworks-ui-drop-target-active-border)",
      ":hover": "var(--foldworks-ui-drop-target-active-border)",
    },
    boxShadow: "0 0 0 7px color-mix(in oklch, var(--foldworks-ui-drop-target-active-border) 18%, transparent), var(--foldworks-ui-shadow-panel)",
    color: {
      default: "var(--foldworks-ui-selection-foreground)",
      ":hover": "var(--foldworks-ui-selection-foreground)",
    },
    height: "40px",
    opacity: 1,
    transform: "scale(1.06)",
    width: "40px",
  },
  node: {
    backgroundColor: "var(--foldworks-ui-surface)",
    borderColor: "var(--foldworks-ui-border)",
    borderRadius: "12px",
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: "var(--foldworks-ui-shadow-sm)",
    color: "var(--foldworks-ui-foreground)",
    cursor: "grab",
    display: "block",
    left: 0,
    outline: {
      default: "none",
      ":focus-visible": "2px solid var(--foldworks-ui-focus)",
    },
    outlineOffset: "3px",
    padding: 0,
    position: "absolute",
    textAlign: "left",
    top: 0,
    transitionDuration: "220ms",
    transitionProperty: "transform, opacity, box-shadow, border-color",
    transitionTimingFunction: "cubic-bezier(0.22, 1, 0.36, 1)",
    userSelect: "none",
    willChange: "transform",
    zIndex: 2,
  },
  nodeCompact: {
    borderRadius: "9px",
  },
  nodeHoverable: {
    boxShadow: {
      default: "var(--foldworks-ui-shadow-sm)",
      ":hover": "var(--foldworks-ui-shadow-panel)",
    },
    borderColor: {
      default: "var(--foldworks-ui-border)",
      ":hover": "var(--foldworks-ui-border-strong)",
    },
  },
  nodeDragging: {
    backgroundColor: "color-mix(in oklch, var(--foldworks-ui-surface) 28%, transparent)",
    borderColor: "var(--foldworks-ui-drop-target-border)",
    borderStyle: "dashed",
    boxShadow: "none",
    opacity: 1,
  },
  nodeDraggingDescendant: {
    backgroundColor: "color-mix(in oklch, var(--foldworks-ui-surface-subtle) 72%, transparent)",
    borderColor: "var(--foldworks-ui-border-strong)",
    borderStyle: "dashed",
    boxShadow: "none",
    opacity: 0.58,
  },
  nodeDraggingContent: {
    opacity: 0,
  },
  nodeSelected: {
    borderColor: "var(--foldworks-ui-selection-border)",
    boxShadow: "0 0 0 2px color-mix(in oklch, var(--foldworks-ui-selection-border) 24%, transparent), var(--foldworks-ui-shadow-panel)",
  },
  nodePreview: {
    borderColor: "var(--foldworks-ui-drop-target-active-border)",
    borderStyle: "dashed",
    opacity: 0.78,
  },
  nodeHeader: {
    alignItems: "center",
    display: "flex",
    justifyContent: "space-between",
    minHeight: "34px",
    padding: "7px 10px 6px",
  },
  nodeHeaderCompact: {
    height: "36px",
    minHeight: "36px",
    paddingBottom: "5px",
    paddingTop: "5px",
  },
  nodeIdentity: {
    alignItems: "center",
    display: "inline-flex",
    gap: "7px",
  },
  nodeIcon: {
    alignItems: "center",
    borderRadius: "5px",
    display: "inline-flex",
    fontSize: "10px",
    fontWeight: 800,
    height: "18px",
    justifyContent: "center",
    width: "18px",
  },
  nodeRemoveHint: {
    alignItems: "center",
    backgroundColor: "var(--foldworks-ui-surface-subtle)",
    borderRadius: "5px",
    color: "var(--foldworks-ui-foreground-subtle)",
    display: "inline-flex",
    fontSize: "13px",
    height: "17px",
    justifyContent: "center",
    width: "17px",
  },
  nodeTitle: {
    color: "var(--foldworks-ui-foreground)",
    fontSize: "11px",
    fontWeight: 750,
    letterSpacing: "-0.005em",
    lineHeight: 1.2,
  },
  nodeDescription: {
    borderTopColor: "var(--foldworks-ui-border)",
    borderTopStyle: "solid",
    borderTopWidth: "1px",
    color: "var(--foldworks-ui-foreground-muted)",
    fontSize: "9px",
    lineHeight: "20px",
    margin: 0,
    overflow: "hidden",
    paddingLeft: "10px",
    paddingRight: "10px",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  ports: {
    alignItems: "center",
    display: "flex",
    justifyContent: "space-between",
    marginTop: "8px",
  },
  portLabel: {
    color: "var(--foldworks-ui-foreground-muted)",
    fontSize: "9px",
    fontWeight: 700,
  },
  portDot: {
    backgroundColor: "var(--foldworks-ui-surface)",
    borderColor: "var(--foldworks-ui-foreground-subtle)",
    borderRadius: "999px",
    borderStyle: "solid",
    borderWidth: "2px",
    height: "9px",
    left: "50%",
    position: "absolute",
    transform: "translateX(-50%)",
    width: "9px",
    zIndex: 2,
  },
  portDotIn: {
    top: "-5px",
  },
  portDotOut: {
    bottom: "-5px",
  },
  ghost: {
    backgroundColor: "var(--foldworks-ui-surface)",
    borderColor: "var(--foldworks-ui-drop-target-active-border)",
    borderRadius: "10px",
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: "var(--foldworks-ui-shadow-float)",
    alignItems: "center",
    display: "flex",
    justifyContent: "space-between",
    minHeight: "44px",
    padding: "10px 12px",
    pointerEvents: "none",
    transform: "rotate(1.5deg) scale(1.02)",
    width: "252px",
    zIndex: 100,
  },
  ghostCount: {
    backgroundColor: "var(--foldworks-ui-success-surface)",
    borderRadius: "999px",
    color: "var(--foldworks-ui-success)",
    fontSize: "10px",
    fontWeight: 750,
    padding: "4px 7px",
  },
  ghostTitle: {
    fontSize: "13px",
    fontWeight: 750,
    marginBottom: 0,
    marginTop: "8px",
  },
  srOnly: {
    clip: "rect(0, 0, 0, 0)",
    height: "1px",
    margin: "-1px",
    overflow: "hidden",
    padding: 0,
    position: "absolute",
    whiteSpace: "nowrap",
    width: "1px",
  },
  dialog: {
    backgroundColor: "transparent",
    borderWidth: 0,
    height: "100%",
    inset: 0,
    margin: 0,
    maxHeight: "none",
    maxWidth: "none",
    overflow: "hidden",
    padding: 0,
    width: "100%",
  },
  backdrop: {
    backgroundColor: "var(--foldworks-ui-overlay)",
    inset: 0,
    opacity: {
      default: 1,
      ":is([data-closed])": 0,
    },
    position: "fixed",
    transitionDuration: "200ms",
    transitionProperty: "opacity",
    zIndex: 0,
  },
  sheet: {
    backgroundColor: "var(--foldworks-ui-surface)",
    borderLeftColor: "var(--foldworks-ui-border)",
    borderLeftStyle: "solid",
    borderLeftWidth: "1px",
    boxShadow: "var(--foldworks-ui-shadow-sheet)",
    display: "flex",
    flexDirection: "column",
    height: "100%",
    maxWidth: "420px",
    overflowY: "auto",
    position: "fixed",
    right: 0,
    top: 0,
    transform: {
      default: "translateX(0)",
      ":is([data-closed])": "translateX(100%)",
    },
    transitionDuration: "260ms",
    transitionProperty: "transform",
    transitionTimingFunction: "cubic-bezier(0.22, 1, 0.36, 1)",
    width: "min(420px, 92vw)",
    zIndex: 1,
  },
  sheetHeader: {
    alignItems: "flex-start",
    borderBottomColor: "var(--foldworks-ui-border)",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    display: "flex",
    justifyContent: "space-between",
    padding: "25px 26px 20px",
  },
  sheetEyebrow: {
    color: "var(--foldworks-ui-selection-foreground)",
    fontSize: "10px",
    fontWeight: 800,
    letterSpacing: "0.11em",
    marginBottom: "7px",
    marginTop: 0,
    textTransform: "uppercase",
  },
  sheetTitle: {
    fontSize: "21px",
    fontWeight: 780,
    letterSpacing: "-0.03em",
    margin: 0,
  },
  sheetDescription: {
    color: "var(--foldworks-ui-foreground-muted)",
    fontSize: "12px",
    lineHeight: 1.5,
    marginBottom: 0,
    marginTop: "7px",
  },
  closeButton: {
    alignItems: "center",
    backgroundColor: {
      default: "var(--foldworks-ui-surface-subtle)",
      ":hover": "var(--foldworks-ui-surface-hover)",
    },
    borderWidth: 0,
    borderRadius: "9px",
    color: "var(--foldworks-ui-foreground-muted)",
    cursor: "pointer",
    display: "flex",
    fontSize: "18px",
    height: "34px",
    justifyContent: "center",
    minWidth: "34px",
  },
  sheetBody: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
    padding: "24px 26px",
  },
  field: {
    display: "flex",
    flexDirection: "column",
    gap: "7px",
  },
  label: {
    color: "var(--foldworks-ui-foreground)",
    fontSize: "12px",
    fontWeight: 750,
  },
  input: {
    backgroundColor: "var(--foldworks-ui-surface)",
    borderColor: {
      default: "var(--foldworks-ui-input)",
      ":focus": "var(--foldworks-ui-focus)",
    },
    borderRadius: "10px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--foldworks-ui-foreground)",
    cursor: {
      default: "auto",
      ":disabled": "not-allowed",
    },
    fontFamily: "inherit",
    fontSize: "13px",
    minHeight: "42px",
    outline: "none",
    paddingLeft: "12px",
    paddingRight: "12px",
    opacity: {
      default: 1,
      ":disabled": 0.62,
    },
    width: "100%",
  },
  textarea: {
    lineHeight: 1.5,
    minHeight: "96px",
    paddingBottom: "10px",
    paddingTop: "10px",
    resize: "vertical",
  },
  fieldGrid: {
    display: "grid",
    gap: "14px",
    gridTemplateColumns: "1fr 1fr",
  },
  sheetNote: {
    backgroundColor: "var(--foldworks-ui-surface-subtle)",
    borderColor: "var(--foldworks-ui-border)",
    borderRadius: "11px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--foldworks-ui-foreground-muted)",
    fontSize: "11px",
    lineHeight: 1.5,
    margin: 0,
    padding: "11px 12px",
  },
  deleteButton: {
    backgroundColor: {
      default: "var(--foldworks-ui-surface)",
      ":hover": "var(--foldworks-ui-danger-surface)",
    },
    borderColor: "var(--foldworks-ui-danger-border)",
    borderRadius: "10px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--foldworks-ui-danger)",
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: "12px",
    fontWeight: 750,
    minHeight: "40px",
    width: "100%",
  },
});

export const kindStyles = stylex.create({
  start: { backgroundColor: "var(--foldworks-ui-surface-subtle)", color: "var(--foldworks-ui-foreground-muted)" },
  action: { backgroundColor: "var(--foldworks-ui-surface-subtle)", color: "var(--foldworks-ui-foreground-muted)" },
  approval: { backgroundColor: "var(--foldworks-ui-info-surface)", color: "var(--foldworks-ui-info)" },
  condition: { backgroundColor: "var(--foldworks-ui-surface-subtle)", color: "var(--foldworks-ui-foreground-muted)" },
  delay: { backgroundColor: "var(--foldworks-ui-info-surface)", color: "var(--foldworks-ui-info)" },
  switch: { backgroundColor: "var(--foldworks-ui-surface-subtle)", color: "var(--foldworks-ui-foreground-muted)" },
  end: { backgroundColor: "var(--foldworks-ui-surface-subtle)", color: "var(--foldworks-ui-foreground-muted)" },
});
