import type { Page } from "playwright";
import { expect, it } from "vitest";

export const workspaceScenarios = (getPage: () => Page, appUrl: string): void => {
  it("workspace panes resize, collapse, restore and retain editor state", async () => {
    const page = getPage();
    await page.goto(`${appUrl}/code-editor`, { waitUntil: "networkidle" });
    const handle = page.getByRole("separator", { name: "Reference", exact: true });
    const value = async () => Number(await handle.getAttribute("aria-valuenow"));
    const initial = await value();
    await handle.press("ArrowLeft");
    await expect.poll(value).toBe(initial + 10);
    await handle.press("Home");
    await expect.poll(value).toBe(280);
    await handle.press("End");
    await expect.poll(value).toBe(Number(await handle.getAttribute("aria-valuemax")));
    const beforeDrag = await value();
    const rect = await handle.boundingBox();
    if (!rect) throw new Error("Missing workspace splitter");
    await page.mouse.move(rect.x + rect.width / 2, rect.y + rect.height / 2);
    await page.mouse.down();
    await page.mouse.move(rect.x + 64, rect.y + rect.height / 2, { steps: 5 });
    await page.mouse.up();
    await expect.poll(value).toBeLessThan(beforeDrag);
    const resized = await value();
    const cancelRect = await handle.boundingBox();
    if (!cancelRect) throw new Error("Missing workspace splitter");
    await page.mouse.move(cancelRect.x + 4, cancelRect.y + 40);
    await page.mouse.down();
    await page.mouse.move(cancelRect.x + 40, cancelRect.y + 40);
    await expect.poll(value).not.toBe(resized);
    await page.keyboard.press("Escape");
    await page.mouse.up();
    await expect.poll(value).toBe(resized);
    await page.getByRole("button", { name: "Enable reference editing", exact: true }).click();
    const reference = page.getByRole("textbox", { name: "TypeScript reference", exact: true });
    await reference.fill("const retained = true;");
    await page.getByRole("button", { name: "Hide Reference", exact: true }).click();
    await expect.poll(value).toBe(0);
    await expect.poll(() => reference.isVisible()).toBe(false);
    await expect.poll(() => handle.evaluate(el => el === document.activeElement)).toBe(true);
    await page.getByRole("button", { name: "Show Reference", exact: true }).click();
    await expect.poll(value).toBe(resized);
    await expect.poll(() => reference.inputValue()).toBe("const retained = true;");
    await handle.press("Enter");
    await expect.poll(value).toBe(0);
    await handle.press("Enter");
    await expect.poll(value).toBe(resized);

    await page.getByRole("button", { name: "Stack documents", exact: true }).click();
    await expect.poll(() => handle.getAttribute("aria-orientation")).toBe("horizontal");
    const stacked = await value();
    await handle.press("ArrowUp");
    await expect.poll(value).toBe(stacked + 10);
    await handle.press("ArrowLeft");
    expect(await value()).toBe(stacked + 10);
    await handle.press("End");
    await expect.poll(value).toBe(390);
    await page.getByRole("button", { name: "Side by side", exact: true }).click();
    await page.setViewportSize({ width: 390, height: 650 });
    const workspace = page.locator('[data-workspace="code-workspace"]');
    await expect.poll(() => workspace.evaluate(el => el.scrollWidth > el.clientWidth)).toBe(true);
    await expect.poll(() => page.locator("body").evaluate(el => el.scrollWidth <= window.innerWidth)).toBe(true);
  });

  it("workspace panes nest without coupling form structure and settings", async () => {
    const page = getPage();
    await page.goto(`${appUrl}/form-builder?example=Handoff&mode=Editor`, { waitUntil: "networkidle" });
    const structure = page.getByRole("separator", { name: "Structure", exact: true });
    const settings = page.getByRole("separator", { name: "Settings", exact: true });
    await structure.press("ArrowRight");
    await expect.poll(() => structure.getAttribute("aria-valuenow")).toBe("260");
    await settings.press("Enter");
    await expect.poll(() => settings.getAttribute("aria-valuenow")).toBe("0");
    expect(await structure.getAttribute("aria-valuenow")).toBe("260");
    await structure.press("Enter");
    await expect.poll(() => page.getByRole("button", { name: "Show Structure", exact: true }).isVisible()).toBe(true);
    await page.getByRole("button", { name: "Show Structure", exact: true }).click();
    await page.getByRole("button", { name: "Show Settings", exact: true }).click();
    await expect.poll(() => page.getByRole("complementary", { name: "Item settings" }).isVisible()).toBe(true);
    await page.setViewportSize({ width: 760, height: 500 });
    const outline = page.locator('[data-workspace="form-outline"] > div > section').first().locator(':scope > div').last();
    await outline.hover();
    await page.mouse.wheel(0, 700);
    await expect.poll(() => outline.evaluate(el => el.scrollTop)).toBeGreaterThan(0);
    expect(await page.locator("body").evaluate(el => el.scrollWidth <= window.innerWidth)).toBe(true);
  });
};
