import * as stylex from "@stylexjs/stylex";

import { colors, motion, radii, shadows, space, typography } from "./tokens.stylex.js";

const spin = stylex.keyframes({
  to: { transform: "rotate(360deg)" },
});

const pulse = stylex.keyframes({
  "0%, 100%": { opacity: 0.55 },
  "50%": { opacity: 1 },
});

export const catalogStyles = stylex.create({
  focusable: {
    outline: { default: "none", ":focus-visible": `3px solid ${colors.focusGlow}` },
    outlineOffset: "0px",
  },
  surface: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.lg,
    borderStyle: "solid",
    borderWidth: "1px",
    color: colors.foreground,
  },
  inset: {
    backgroundColor: colors.surfaceSubtle,
    borderColor: colors.border,
    borderRadius: radii.md,
    borderStyle: "solid",
    borderWidth: "1px",
  },
  alert: {
    display: "grid",
    gap: space.xs,
    padding: space.md,
  },
  alertDanger: {
    backgroundColor: colors.dangerSurface,
    borderColor: colors.dangerBorder,
    color: colors.danger,
  },
  title: {
    color: "inherit",
    fontFamily: typography.fontFamily,
    fontSize: "14px",
    fontWeight: 600,
    lineHeight: 1.3,
  },
  description: {
    color: colors.foregroundMuted,
    fontFamily: typography.fontFamily,
    fontSize: "13px",
    lineHeight: 1.5,
  },
  aspectRatio: {
    overflow: "hidden",
    position: "relative",
    width: "100%",
  },
  aspectRatioContent: {
    height: "100%",
    inset: 0,
    position: "absolute",
    width: "100%",
  },
  avatar: {
    alignItems: "center",
    backgroundColor: colors.surfaceSubtle,
    borderColor: colors.border,
    borderRadius: radii.full,
    borderStyle: "solid",
    borderWidth: "1px",
    color: colors.foregroundMuted,
    display: "inline-flex",
    flexShrink: 0,
    fontFamily: typography.fontFamily,
    fontSize: "12px",
    fontWeight: 600,
    height: "32px",
    justifyContent: "center",
    overflow: "hidden",
    width: "32px",
  },
  avatarSm: { height: "24px", width: "24px", fontSize: "10px" },
  avatarLg: { height: "40px", width: "40px", fontSize: "14px" },
  avatarImage: { height: "100%", objectFit: "cover", width: "100%" },
  breadcrumb: {
    alignItems: "center",
    color: colors.foregroundMuted,
    display: "flex",
    flexWrap: "wrap",
    fontFamily: typography.fontFamily,
    fontSize: "13px",
    gap: space.sm,
    listStyle: "none",
  },
  breadcrumbItem: { alignItems: "center", display: "inline-flex", gap: space.sm },
  breadcrumbLink: { color: { default: colors.foregroundMuted, ":hover": colors.foreground }, textDecoration: "none" },
  breadcrumbCurrent: { color: colors.foreground, fontWeight: 550 },
  card: { display: "flex", flexDirection: "column", overflow: "hidden" },
  cardHeader: { alignItems: "start", display: "grid", gap: space.md, gridTemplateColumns: "minmax(0, 1fr) auto", padding: "16px 16px 0" },
  cardHeading: { display: "grid", gap: space.xs, minWidth: 0 },
  cardAction: { alignItems: "center", display: "flex", justifyContent: "flex-end" },
  cardContent: { padding: "16px" },
  cardFooter: { alignItems: "center", display: "flex", gap: space.sm, padding: "0 16px 16px" },
  separatorHorizontal: { backgroundColor: colors.border, border: 0, height: "1px", width: "100%" },
  separatorVertical: { alignSelf: "stretch", backgroundColor: colors.border, minHeight: "16px", width: "1px" },
  item: { alignItems: "center", display: "flex", gap: space.md, padding: space.md },
  itemMedia: { alignItems: "center", display: "flex", flexShrink: 0, justifyContent: "center" },
  itemContent: { display: "grid", flex: 1, gap: "2px", minWidth: 0 },
  kbd: {
    alignItems: "center",
    backgroundColor: colors.surfaceSubtle,
    borderColor: colors.border,
    borderRadius: radii.sm,
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: shadows.sm,
    color: colors.foregroundMuted,
    display: "inline-flex",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    fontSize: "11px",
    fontWeight: 550,
    height: "20px",
    justifyContent: "center",
    minWidth: "20px",
    padding: "0 5px",
  },
  empty: { alignItems: "center", display: "flex", flexDirection: "column", gap: space.sm, padding: "36px 20px", textAlign: "center" },
  emptyMedia: { alignItems: "center", backgroundColor: colors.surfaceSubtle, borderRadius: radii.full, display: "flex", height: "40px", justifyContent: "center", width: "40px" },
  progress: { backgroundColor: colors.surfaceSubtle, borderRadius: radii.full, height: "8px", overflow: "hidden", width: "100%" },
  progressIndicator: { backgroundColor: colors.primary, borderRadius: radii.full, height: "100%", transitionDuration: motion.normal, transitionProperty: "width", transitionTimingFunction: motion.easeOut },
  skeleton: { animationDuration: "1.6s", animationIterationCount: "infinite", animationName: pulse, animationTimingFunction: "ease-in-out", backgroundColor: colors.surfaceSubtle, borderRadius: radii.md, minHeight: "16px", width: "100%" },
  spinner: { animationDuration: "700ms", animationIterationCount: "infinite", animationName: spin, animationTimingFunction: "linear", borderColor: colors.border, borderRadius: radii.full, borderStyle: "solid", borderTopColor: colors.primary, borderWidth: "2px", display: "inline-block", height: "16px", width: "16px" },
  control: {
    backgroundColor: "color-mix(in oklch, var(--input) 12%, transparent)",
    borderColor: { default: colors.input, ":focus": colors.primary },
    borderRadius: radii.md,
    borderStyle: "solid",
    borderWidth: "1px",
    color: colors.foreground,
    fontFamily: typography.fontFamily,
    fontSize: "14px",
    minHeight: "32px",
    padding: "6px 10px",
    width: "100%",
  },
  textarea: { lineHeight: 1.5, minHeight: "84px", resize: "vertical" },
  label: { color: colors.foreground, display: "inline-block", fontFamily: typography.fontFamily, fontSize: "14px", fontWeight: 550 },
  inputGroup: { alignItems: "stretch", display: "flex", overflow: "hidden" },
  inputGroupControl: { border: 0, borderRadius: 0, minWidth: 0 },
  inputGroupAddon: { alignItems: "center", color: colors.foregroundMuted, display: "inline-flex", flexShrink: 0, fontFamily: typography.fontFamily, fontSize: "13px", padding: "0 10px" },
  otp: { display: "flex", gap: space.sm },
  otpSlot: { alignItems: "center", display: "flex", fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace", fontSize: "16px", height: "36px", justifyContent: "center", width: "32px" },
  radioGroup: { borderStyle: "none", borderWidth: 0, display: "grid", gap: space.sm, margin: 0, padding: 0 },
  radioItem: { alignItems: "center", color: colors.foreground, display: "flex", fontFamily: typography.fontFamily, fontSize: "14px", gap: space.sm },
  radioControl: { accentColor: colors.primary, height: "16px", width: "16px" },
  range: { accentColor: colors.primary, cursor: "pointer", width: "100%" },
  toggle: {
    alignItems: "center",
    backgroundColor: { default: "transparent", ":hover": colors.surfaceSubtle },
    borderColor: "transparent",
    borderRadius: radii.md,
    borderStyle: "solid",
    borderWidth: "1px",
    color: colors.foregroundMuted,
    cursor: "pointer",
    display: "inline-flex",
    fontFamily: typography.fontFamily,
    fontSize: "13px",
    fontWeight: 550,
    height: "32px",
    justifyContent: "center",
    padding: "0 10px",
  },
  togglePressed: { backgroundColor: colors.surfaceSubtle, color: colors.foreground },
  group: { alignItems: "center", display: "inline-flex" },
  groupConnected: { borderRadius: 0, marginLeft: "-1px" },
  groupFirst: { borderBottomLeftRadius: radii.md, borderTopLeftRadius: radii.md, marginLeft: 0 },
  groupLast: { borderBottomRightRadius: radii.md, borderTopRightRadius: radii.md },
  tabs: { display: "grid", gap: space.md },
  tabsList: { alignItems: "center", backgroundColor: colors.surfaceSubtle, borderRadius: radii.lg, display: "inline-flex", gap: "2px", padding: "3px", width: "fit-content" },
  tabsTrigger: { backgroundColor: "transparent", border: 0, borderRadius: radii.md, color: colors.foregroundMuted, cursor: "pointer", fontFamily: typography.fontFamily, fontSize: "13px", fontWeight: 550, minHeight: "28px", padding: "0 10px" },
  tabsTriggerActive: { backgroundColor: colors.surface, boxShadow: shadows.sm, color: colors.foreground },
  pagination: { alignItems: "center", display: "flex", gap: "4px", justifyContent: "center" },
  pageButton: { alignItems: "center", backgroundColor: { default: "transparent", ":hover": colors.surfaceSubtle }, borderColor: "transparent", borderRadius: radii.md, borderStyle: "solid", borderWidth: "1px", color: colors.foreground, cursor: "pointer", display: "inline-flex", fontFamily: typography.fontFamily, fontSize: "13px", height: "32px", justifyContent: "center", minWidth: "32px", padding: "0 8px" },
  pageButtonCurrent: { backgroundColor: colors.surface, borderColor: colors.border, boxShadow: shadows.sm },
  nav: { alignItems: "center", display: "flex", flexWrap: "wrap", gap: space.xs, listStyle: "none" },
  navLink: { backgroundColor: { default: "transparent", ":hover": colors.surfaceSubtle }, borderRadius: radii.md, color: colors.foreground, display: "inline-flex", fontFamily: typography.fontFamily, fontSize: "13px", fontWeight: 550, padding: "7px 10px", textDecoration: "none" },
  sidebar: { backgroundColor: "var(--sidebar)", borderColor: "var(--sidebar-border)", borderRadius: radii.lg, borderStyle: "solid", borderWidth: "1px", color: "var(--sidebar-foreground)", display: "flex", flexDirection: "column", gap: space.md, minWidth: "220px", padding: space.md },
  sidebarGroup: { display: "grid", gap: space.xs },
  sidebarLabel: { color: colors.foregroundMuted, fontFamily: typography.fontFamily, fontSize: "11px", fontWeight: 600, letterSpacing: "0.04em", textTransform: "uppercase" },
  sidebarItem: { backgroundColor: { default: "transparent", ":hover": "var(--sidebar-accent)" }, borderRadius: radii.md, color: "var(--sidebar-foreground)", display: "flex", fontFamily: typography.fontFamily, fontSize: "13px", gap: space.sm, padding: "7px 8px", textDecoration: "none" },
  overlay: { alignItems: "center", backgroundColor: colors.overlay, display: "flex", inset: 0, justifyContent: "center", padding: space.lg, position: "fixed" },
  dialog: { backgroundColor: "transparent", border: 0, height: "100%", inset: 0, margin: 0, maxHeight: "none", maxWidth: "none", padding: 0, position: "fixed", width: "100%" },
  dialogBackdrop: { backgroundColor: "transparent", border: 0, cursor: "default", inset: 0, position: "absolute" },
  dialogPanel: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.lg, borderStyle: "solid", borderWidth: "1px", boxShadow: shadows.float, color: colors.foreground, display: "grid", gap: space.md, maxWidth: "460px", padding: space.lg, position: "relative", width: "min(100%, 460px)" },
  dialogHeader: { display: "grid", gap: space.xs },
  dialogFooter: { display: "flex", gap: space.sm, justifyContent: "flex-end" },
  sheetPanel: { borderRadius: 0, height: "100%", marginLeft: "auto", maxWidth: "420px" },
  drawerPanel: { alignSelf: "flex-end", borderBottomLeftRadius: 0, borderBottomRightRadius: 0, maxWidth: "none", width: "100%" },
  floating: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.md, borderStyle: "solid", borderWidth: "1px", boxShadow: shadows.float, color: colors.foreground, minWidth: "180px", padding: space.sm, position: "relative" },
  menu: { display: "grid", gap: "2px", listStyle: "none", margin: 0, padding: "4px" },
  menuItem: { alignItems: "center", backgroundColor: { default: "transparent", ":hover": colors.surfaceSubtle }, border: 0, borderRadius: radii.sm, color: colors.foreground, cursor: "pointer", display: "flex", fontFamily: typography.fontFamily, fontSize: "13px", gap: space.sm, minHeight: "30px", padding: "5px 8px", textAlign: "left", width: "100%" },
  menuLabel: { color: colors.foregroundMuted, fontFamily: typography.fontFamily, fontSize: "11px", fontWeight: 600, padding: "6px 8px" },
  tooltip: { backgroundColor: colors.foreground, borderRadius: radii.sm, color: colors.background, fontFamily: typography.fontFamily, fontSize: "12px", padding: "5px 8px", width: "fit-content" },
  command: { display: "grid", gap: space.sm, overflow: "hidden" },
  commandList: { display: "grid", gap: "2px", maxHeight: "240px", overflowY: "auto" },
  scrollArea: { overflow: "auto", scrollbarColor: `${colors.borderStrong} transparent`, scrollbarWidth: "thin" },
  resizable: { minHeight: "96px", minWidth: "160px", overflow: "auto", resize: "both" },
  carousel: { display: "flex", gap: space.md, overflowX: "auto", scrollSnapType: "x mandatory", scrollbarWidth: "thin" },
  carouselItem: { flex: "0 0 82%", scrollSnapAlign: "start" },
  calendar: { display: "grid", gap: space.sm, width: "280px" },
  calendarHeader: { alignItems: "center", display: "flex", justifyContent: "space-between" },
  calendarGrid: { display: "grid", gap: "2px", gridTemplateColumns: "repeat(7, 1fr)" },
  calendarCell: { alignItems: "center", backgroundColor: { default: "transparent", ":hover": colors.surfaceSubtle }, border: 0, borderRadius: radii.sm, color: colors.foreground, cursor: "pointer", display: "flex", fontFamily: typography.fontFamily, fontSize: "12px", height: "32px", justifyContent: "center" },
  calendarCellSelected: { backgroundColor: colors.primary, color: colors.primaryForeground },
  tableWrap: { overflowX: "auto", width: "100%" },
  table: { borderCollapse: "collapse", fontFamily: typography.fontFamily, fontSize: "13px", width: "100%" },
  tableHead: { borderBottomColor: colors.border, borderBottomStyle: "solid", borderBottomWidth: "1px", color: colors.foregroundMuted, fontWeight: 550, padding: "8px 10px", textAlign: "left" },
  tableCell: { borderBottomColor: colors.border, borderBottomStyle: "solid", borderBottomWidth: "1px", color: colors.foreground, padding: "9px 10px" },
  chart: { alignItems: "end", display: "flex", gap: space.sm, height: "120px", paddingTop: space.md },
  chartBar: { backgroundColor: "var(--chart-1)", borderRadius: `${radii.sm} ${radii.sm} 0 0`, flex: 1, minWidth: "16px" },
  message: { alignItems: "flex-start", display: "flex", gap: space.sm },
  messageOwn: { flexDirection: "row-reverse" },
  bubble: { backgroundColor: colors.surfaceSubtle, borderRadius: radii.lg, color: colors.foreground, fontFamily: typography.fontFamily, fontSize: "13px", lineHeight: 1.5, maxWidth: "80%", padding: "9px 12px" },
  bubbleOwn: { backgroundColor: colors.primary, color: colors.primaryForeground },
  marker: { backgroundColor: colors.warningSurface, borderRadius: radii.sm, color: colors.warning, padding: "1px 4px" },
  attachment: { alignItems: "center", display: "flex", gap: space.sm, padding: "8px 10px" },
  messageScroller: { display: "flex", flexDirection: "column", gap: space.md, maxHeight: "260px", overflowY: "auto", scrollBehavior: "smooth" },
});
