import * as stylex from "@stylexjs/stylex";
import { colors, typography, radii, space } from "./tokens.stylex.js";
const appear = stylex.keyframes({ from: { opacity: 0 }, to: { opacity: 1 } });
export const desktopStyles = stylex.create({
  column: { display: "grid", gap: space.sm, minWidth: 0 },
  row: { display: "flex", alignItems: "center", gap: space.sm, minWidth: 0 },
  wrap: { flexWrap: "wrap" },
  surface: {
    backgroundColor: colors.surface,
    color: colors.surfaceForeground,
    borderColor: colors.border,
    borderStyle: "solid",
    borderWidth: "1px",
    borderRadius: radii.md,
    padding: space.md,
    minWidth: 0,
  },
  control: {
    fontFamily: typography.fontFamily,
    fontSize: "13px",
    fontWeight: 400,
    color: colors.foreground,
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderStyle: "solid",
    borderWidth: "1px",
    borderRadius: radii.sm,
    padding: "6px 8px",
    minWidth: 0,
    width: "100%",
    outline: { default: "none", ":focus-visible": "2px solid var(--ring)" },
  },
  button: {
    textAlign: "start",
    fontFamily: typography.fontFamily,
    fontSize: "13px",
    fontWeight: 500,
    borderRadius: radii.sm,
    padding: "6px 8px",
    color: colors.foreground,
    backgroundColor: { default: "transparent", ":hover": colors.surfaceHover },
    cursor: "pointer",
    outline: { default: "none", ":focus-visible": "2px solid var(--ring)" },
  },
  muted: { color: colors.foregroundMuted, fontSize: "12px" },
  error: { color: colors.danger, fontSize: "12px" },
  overflow: { position: "relative", minWidth: 0 },
  scroller: {
    overflowX: "auto",
    display: "flex",
    alignItems: "flex-start",
    gap: "8px",
    minWidth: 0,
  },
  item: { flexShrink: 0, whiteSpace: "nowrap" },
  probes: {
    position: "absolute",
    visibility: "hidden",
    pointerEvents: "none",
    display: "flex",
    width: "max-content",
    top: 0,
    left: 0,
    height: 0,
    overflow: "hidden",
  },
  menu: {
    backgroundColor: colors.popover,
    color: colors.popoverForeground,
    borderColor: colors.border,
    borderStyle: "solid",
    borderWidth: "1px",
    borderRadius: radii.md,
    padding: space.xs,
    boxShadow: "0 8px 24px #0002",
    minWidth: "180px",
    maxWidth: "calc(100vw - 16px)",
  },
  panel: {
    animationName: appear,
    animationDuration: {
      default: "120ms",
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
  },
  selected: {
    backgroundColor: colors.selection,
    color: colors.selectionForeground,
  },
  calendar: { display: "grid", gap: "4px", width: "280px", maxWidth: "100%" },
  week: {
    display: "grid",
    gridTemplateColumns: "repeat(7, minmax(0, 1fr))",
    textAlign: "center",
  },
  calendarCell: { width: "100%", textAlign: "center" },
  focused: { outline: "2px solid var(--ring)", outlineOffset: "-2px" },
  months: { display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))" },
});
