import * as stylex from "@stylexjs/stylex";

import { colors, radii, space, typography } from "./tokens.stylex.js";

/** Marker colors for Legend tones; `muted` is a quiet gray swatch. */
export const toneColorStyles = stylex.create({
  neutral: { color: colors.foregroundMuted },
  muted: { color: colors.borderStrong },
  accent: { color: colors.primary },
  success: { color: colors.success },
  warning: { color: colors.warning },
  danger: { color: colors.danger },
  info: { color: colors.info },
});

export const descriptionListStyles = stylex.create({
  root: {
    fontFamily: typography.fontFamily,
    fontSize: typography.sizeMd,
    lineHeight: typography.lineHeightNormal,
    margin: 0,
    minWidth: 0,
  },
  sm: { fontSize: typography.sizeSm },
  horizontal: {
    columnGap: space.lg,
    display: "grid",
    gridTemplateColumns: "fit-content(40%) minmax(0, 1fr)",
    rowGap: space.sm,
  },
  stacked: { display: "flex", flexDirection: "column", gap: space.md },
  divided: { rowGap: 0 },
  rowHorizontal: {
    alignItems: "baseline",
    display: "grid",
    gridColumn: "1 / -1",
    gridTemplateColumns: "subgrid",
  },
  rowStacked: { display: "flex", flexDirection: "column", gap: space.xxs, minWidth: 0 },
  rowDivided: { paddingBlock: space.sm },
  rowDivider: { borderTopColor: colors.border, borderTopStyle: "solid", borderTopWidth: "1px" },
  term: {
    color: colors.foregroundMuted,
    fontWeight: typography.weightMedium,
    minWidth: 0,
    overflowWrap: "anywhere",
  },
  value: { color: colors.foreground, margin: 0, minWidth: 0, overflowWrap: "anywhere" },
  code: { fontFamily: typography.fontMono, fontSize: "0.923em" },
  codeChip: {
    backgroundColor: colors.surfaceSubtle,
    borderRadius: radii.sm,
    color: colors.secondaryForeground,
    paddingBlock: "1px",
    paddingInline: space.xs,
  },
  muted: { color: colors.foregroundMuted },
  chips: { alignItems: "center", display: "flex", flexWrap: "wrap", gap: space.xs },
  empty: { color: colors.foregroundMuted },
});

export const statStyles = stylex.create({
  root: {
    display: "flex",
    flexDirection: "column",
    fontFamily: typography.fontFamily,
    gap: space.xs,
    margin: 0,
    minWidth: 0,
  },
  tile: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.lg,
    borderStyle: "solid",
    borderWidth: "1px",
    color: colors.surfaceForeground,
    padding: space.lg,
  },
  tileSm: { padding: space.md },
  tileAccent: {
    backgroundColor: `color-mix(in oklch, ${colors.primary} 5%, ${colors.surface})`,
    borderColor: `color-mix(in oklch, ${colors.primary} 28%, ${colors.border})`,
  },
  tileSuccess: {
    backgroundColor: `color-mix(in oklch, ${colors.successSurface} 60%, ${colors.surface})`,
    borderColor: `color-mix(in oklch, ${colors.success} 28%, ${colors.border})`,
  },
  tileWarning: {
    backgroundColor: `color-mix(in oklch, ${colors.warningSurface} 60%, ${colors.surface})`,
    borderColor: `color-mix(in oklch, ${colors.warning} 32%, ${colors.border})`,
  },
  tileDanger: {
    backgroundColor: `color-mix(in oklch, ${colors.dangerSurface} 70%, ${colors.surface})`,
    borderColor: colors.dangerBorder,
  },
  tileInfo: {
    backgroundColor: `color-mix(in oklch, ${colors.infoSurface} 60%, ${colors.surface})`,
    borderColor: `color-mix(in oklch, ${colors.info} 28%, ${colors.border})`,
  },
  label: {
    alignItems: "center",
    color: colors.foregroundMuted,
    display: "flex",
    fontSize: typography.sizeMd,
    fontWeight: typography.weightMedium,
    gap: space.xs,
    lineHeight: typography.lineHeightTight,
    minWidth: 0,
  },
  valueRow: { alignItems: "baseline", display: "flex", flexWrap: "wrap", gap: space.sm, margin: 0 },
  value: {
    color: colors.foreground,
    fontSize: "24px",
    fontVariantNumeric: "tabular-nums",
    fontWeight: typography.weightSemibold,
    letterSpacing: "-0.02em",
    lineHeight: typography.lineHeightTight,
  },
  valueSm: { fontSize: typography.sizeXl },
  valueMuted: { color: colors.foregroundMuted },
  delta: {
    alignItems: "center",
    display: "inline-flex",
    fontSize: typography.sizeSm,
    fontVariantNumeric: "tabular-nums",
    fontWeight: typography.weightMedium,
    gap: space.xxs,
  },
  deltaLabel: { color: colors.foregroundMuted, fontWeight: 400 },
  description: {
    color: colors.foregroundMuted,
    fontSize: typography.sizeSm,
    lineHeight: typography.lineHeightNormal,
    margin: 0,
  },
  extra: { margin: 0, marginTop: space.xs },
});

export const legendStyles = stylex.create({
  root: {
    color: colors.foreground,
    display: "flex",
    fontFamily: typography.fontFamily,
    fontSize: typography.sizeSm,
    listStyle: "none",
    margin: 0,
    padding: 0,
  },
  horizontal: { alignItems: "center", columnGap: space.lg, flexWrap: "wrap", rowGap: space.xs },
  vertical: { flexDirection: "column", gap: space.xs },
  item: {
    alignItems: "center",
    display: "flex",
    gap: space.sm,
    lineHeight: typography.lineHeightTight,
    minWidth: 0,
  },
  itemWithDescription: { alignItems: "flex-start" },
  copy: { display: "flex", flexDirection: "column", gap: space.xxs, minWidth: 0 },
  labelRow: { alignItems: "baseline", display: "flex", gap: space.xs },
  value: { color: colors.foregroundMuted, fontVariantNumeric: "tabular-nums" },
  description: { color: colors.foregroundMuted, fontSize: typography.sizeXs },
  marker: {
    alignItems: "center",
    display: "inline-flex",
    flexShrink: 0,
    height: "14px",
    justifyContent: "center",
    width: "14px",
  },
  swatch: {
    borderColor: "currentColor",
    borderStyle: "solid",
    borderWidth: "1px",
    height: "10px",
    width: "10px",
  },
  square: { borderRadius: "2px" },
  circle: { borderRadius: radii.full },
  line: { borderRadius: radii.full, borderWidth: 0, height: "3px", width: "14px" },
  solid: { backgroundColor: "currentColor" },
  soft: { backgroundColor: "color-mix(in oklch, currentColor 22%, transparent)" },
  outline: { backgroundColor: "transparent", borderWidth: "1.5px" },
  dashed: { backgroundColor: "transparent", borderStyle: "dashed", borderWidth: "1.5px" },
  lineDashed: {
    backgroundColor: "transparent",
    borderStyle: "dashed",
    borderTopWidth: "2px",
    height: 0,
  },
  symbol: { fontSize: typography.sizeSm, fontWeight: typography.weightSemibold, lineHeight: 1 },
});

export const codeBlockStyles = stylex.create({
  root: {
    backgroundColor: colors.surfaceSubtle,
    borderColor: colors.border,
    borderRadius: radii.md,
    borderStyle: "solid",
    borderWidth: "1px",
    color: colors.foreground,
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    overflow: "hidden",
    position: "relative",
  },
  header: {
    alignItems: "center",
    borderBottomColor: colors.border,
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    display: "flex",
    gap: space.sm,
    justifyContent: "space-between",
    minHeight: "32px",
    paddingBlock: space.xxs,
    paddingInlineEnd: space.xs,
    paddingInlineStart: space.md,
  },
  title: {
    color: colors.foregroundMuted,
    fontFamily: typography.fontFamily,
    fontSize: typography.sizeSm,
    fontWeight: typography.weightMedium,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  copy: {
    alignItems: "center",
    backgroundColor: { default: "transparent", ":hover": colors.surfaceHover },
    border: 0,
    borderRadius: radii.sm,
    color: { default: colors.foregroundMuted, ":hover": colors.foreground },
    cursor: "pointer",
    display: "inline-flex",
    flexShrink: 0,
    fontFamily: typography.fontFamily,
    fontSize: typography.sizeSm,
    fontWeight: typography.weightMedium,
    gap: space.xs,
    height: "24px",
    outline: { default: "none", ":focus-visible": `3px solid ${colors.focusGlow}` },
    paddingInline: space.sm,
  },
  copyFloating: {
    backgroundColor: { default: colors.surface, ":hover": colors.surfaceHover },
    insetBlockStart: space.xs,
    insetInlineEnd: space.xs,
    position: "absolute",
    zIndex: 1,
  },
  viewport: {
    minHeight: 0,
    overflow: "auto",
    scrollbarColor: `${colors.borderStrong} transparent`,
    scrollbarWidth: "thin",
  },
  viewportFocusable: {
    outline: { default: "none", ":focus-visible": `3px solid ${colors.focusGlow}` },
    outlineOffset: "-3px",
  },
  pre: {
    fontFamily: typography.fontMono,
    fontSize: typography.sizeSm,
    lineHeight: 1.6,
    margin: 0,
    padding: space.md,
    tabSize: 2,
    whiteSpace: "pre",
    width: "max-content",
    minWidth: "100%",
  },
  preFloatingCopy: { paddingInlineEnd: "72px" },
  wrap: { overflowWrap: "anywhere", whiteSpace: "pre-wrap", width: "auto" },
  code: { fontFamily: "inherit", fontSize: "inherit" },
  line: { display: "block", minHeight: "1.6em" },
  lineNumber: {
    color: colors.foregroundMuted,
    display: "inline-block",
    fontVariantNumeric: "tabular-nums",
    marginInlineEnd: space.md,
    opacity: 0.7,
    textAlign: "end",
    userSelect: "none",
  },
  keyword: { color: "var(--foldworks-ui-code-keyword)" },
  string: { color: "var(--foldworks-ui-code-string)" },
  number: { color: "var(--foldworks-ui-code-number)" },
  comment: { color: "var(--foldworks-ui-code-comment)", fontStyle: "italic" },
  type: { color: "var(--foldworks-ui-code-type)" },
  property: { color: "var(--foldworks-ui-code-property)" },
  punctuation: { color: colors.foregroundMuted },
});
