import * as stylex from "@stylexjs/stylex";

import { colors, motion, radii, shadows, space, typography } from "./tokens.stylex.js";

export const contentStyles = stylex.create({
  text: { fontFamily: typography.fontFamily, lineHeight: typography.lineHeightNormal, margin: 0 },
  textXs: { fontSize: typography.sizeXs },
  textSm: { fontSize: typography.sizeSm },
  textMd: { fontSize: typography.sizeMd },
  textLg: { fontSize: typography.sizeLg },
  textXl: { fontSize: typography.sizeXl },
  toneDefault: { color: colors.foreground },
  toneMuted: { color: colors.foregroundMuted },
  toneSuccess: { color: colors.success },
  toneWarning: { color: colors.warning },
  toneDanger: { color: colors.danger },
  weightRegular: { fontWeight: 400 },
  weightMedium: { fontWeight: typography.weightMedium },
  weightSemibold: { fontWeight: typography.weightSemibold },
  weightBold: { fontWeight: typography.weightBold },
  alignCenter: { textAlign: "center" },
  alignEnd: { textAlign: "end" },
  truncate: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  heading: { fontFamily: typography.fontFamily, fontWeight: typography.weightSemibold, letterSpacing: "-0.02em", lineHeight: typography.lineHeightTight, margin: 0 },
  headingSm: { fontSize: typography.sizeMd },
  headingMd: { fontSize: typography.sizeXl },
  headingLg: { fontSize: "20px" },
  headingXl: { fontSize: "28px" },
  link: {
    borderRadius: radii.sm, color: colors.primary, fontFamily: typography.fontFamily,
    outline: { default: "none", ":focus-visible": `3px solid ${colors.focusGlow}` },
    textDecorationLine: { default: "underline", ":hover": "none" }, textUnderlineOffset: "3px",
  },
  visuallyHidden: { border: 0, clip: "rect(0 0 0 0)", clipPath: "inset(50%)", height: "1px", margin: "-1px", overflow: "hidden", padding: 0, position: "absolute", whiteSpace: "nowrap", width: "1px" },
  visuallyHiddenFocusable: {
    border: 0, clip: { default: "rect(0 0 0 0)", ":focus": "auto" }, clipPath: { default: "inset(50%)", ":focus": "none" },
    height: { default: "1px", ":focus": "auto" }, margin: { default: "-1px", ":focus": 0 },
    overflow: { default: "hidden", ":focus": "visible" }, padding: { default: 0, ":focus": space.sm },
    position: { default: "absolute", ":focus": "fixed" }, whiteSpace: "nowrap", width: { default: "1px", ":focus": "auto" },
    backgroundColor: colors.surface, color: colors.foreground, insetBlockStart: "8px", insetInlineStart: "8px", zIndex: 100,
  },
});

export const primitiveStyles = stylex.create({
  tag: { alignItems: "center", backgroundColor: colors.surfaceSubtle, borderColor: colors.border, borderRadius: radii.full, borderStyle: "solid", borderWidth: "1px", color: colors.foreground, display: "inline-flex", fontFamily: typography.fontFamily, fontSize: typography.sizeSm, fontWeight: typography.weightMedium, gap: space.xs, minHeight: "24px", padding: "2px 8px" },
  tagSelected: { backgroundColor: colors.selection, borderColor: colors.selectionBorder, color: colors.selectionForeground },
  tagDanger: { backgroundColor: colors.dangerSurface, borderColor: colors.dangerBorder, color: colors.danger },
  tagSuccess: { backgroundColor: colors.successSurface, borderColor: colors.success, color: colors.success },
  tagButton: { backgroundColor: "transparent", border: 0, color: "inherit", cursor: "pointer", font: "inherit", margin: "-2px -4px", padding: "2px 4px" },
  tagRemove: { alignItems: "center", backgroundColor: { default: "transparent", ":hover": "color-mix(in oklch, currentColor 12%, transparent)" }, border: 0, borderRadius: radii.full, color: "inherit", cursor: "pointer", display: "inline-flex", font: "inherit", height: "18px", justifyContent: "center", marginInlineEnd: "-4px", padding: 0, width: "18px" },
  numberRoot: { display: "grid", gap: space.xs },
  numberControl: { alignItems: "stretch", display: "grid", gridTemplateColumns: "32px minmax(72px, 1fr) 32px" },
  numberInput: { appearance: "textfield", borderRadius: 0, minWidth: 0, textAlign: "center" },
  numberButton: { alignItems: "center", backgroundColor: { default: colors.surface, ":hover": colors.surfaceHover }, borderColor: colors.borderStrong, borderStyle: "solid", borderWidth: "1px", color: colors.foreground, cursor: "pointer", display: "inline-flex", fontFamily: typography.fontFamily, fontSize: typography.sizeLg, justifyContent: "center", padding: 0 },
  numberButtonStart: { borderBottomLeftRadius: radii.md, borderRightWidth: 0, borderTopLeftRadius: radii.md },
  numberButtonEnd: { borderBottomRightRadius: radii.md, borderLeftWidth: 0, borderTopRightRadius: radii.md },
  stepper: { listStyle: "none", margin: 0, padding: 0 },
  stepperHorizontal: { display: "grid", gridAutoColumns: "minmax(0, 1fr)", gridAutoFlow: "column" },
  stepperVertical: { display: "grid", gap: space.sm },
  step: { alignItems: "flex-start", display: "grid", gap: space.sm, gridTemplateColumns: "28px minmax(0, 1fr)", minWidth: 0, position: "relative" },
  stepHorizontal: { gridTemplateColumns: "1fr", justifyItems: "center", paddingInline: space.xs, textAlign: "center" },
  stepConnectorHorizontal: { backgroundColor: colors.border, height: "1px", insetInline: "calc(50% + 18px) calc(-50% + 18px)", insetBlockStart: "14px", position: "absolute" },
  stepConnectorVertical: { backgroundColor: colors.border, bottom: "-8px", insetInlineStart: "13px", position: "absolute", top: "28px", width: "1px" },
  stepMarker: { alignItems: "center", backgroundColor: colors.surface, borderColor: colors.borderStrong, borderRadius: radii.full, borderStyle: "solid", borderWidth: "1px", color: colors.foregroundMuted, display: "inline-flex", fontFamily: typography.fontFamily, fontSize: typography.sizeXs, fontWeight: typography.weightSemibold, height: "28px", justifyContent: "center", position: "relative", width: "28px", zIndex: 1 },
  stepCurrent: { backgroundColor: colors.primary, borderColor: colors.primary, color: colors.primaryForeground },
  stepComplete: { backgroundColor: colors.successSurface, borderColor: colors.success, color: colors.success },
  stepError: { backgroundColor: colors.dangerSurface, borderColor: colors.danger, color: colors.danger },
  stepButton: { backgroundColor: "transparent", border: 0, color: "inherit", cursor: "pointer", display: "grid", font: "inherit", gap: "2px", minWidth: 0, padding: 0, textAlign: "start" },
  stepCopyHorizontal: { justifyItems: "center", textAlign: "center" },
  stepLabel: { color: colors.foreground, fontFamily: typography.fontFamily, fontSize: typography.sizeMd, fontWeight: typography.weightMedium },
  stepDescription: { color: colors.foregroundMuted, fontFamily: typography.fontFamily, fontSize: typography.sizeSm, lineHeight: typography.lineHeightNormal },
  toastViewport: { display: "flex", gap: space.sm, maxWidth: "min(380px, calc(100vw - 32px))", pointerEvents: "none", position: "fixed", zIndex: 100 },
  toast: { backgroundColor: colors.popover, borderColor: colors.border, borderRadius: radii.lg, borderStyle: "solid", borderWidth: "1px", boxShadow: shadows.float, color: colors.popoverForeground, display: "grid", gap: space.xs, minWidth: "280px", padding: space.md, pointerEvents: "auto", transitionDuration: { default: motion.fast, "@media (prefers-reduced-motion: reduce)": "0s" }, transitionProperty: "opacity, transform" },
  toastClosed: { opacity: 0, transform: "translateY(4px)" },
  toastTitle: { fontFamily: typography.fontFamily, fontSize: typography.sizeMd, fontWeight: typography.weightSemibold },
  toastDescription: { color: colors.foregroundMuted, fontFamily: typography.fontFamily, fontSize: typography.sizeSm, lineHeight: typography.lineHeightNormal },
  toastDismiss: { backgroundColor: "transparent", border: 0, borderRadius: radii.sm, color: colors.foregroundMuted, cursor: "pointer", fontFamily: typography.fontFamily, fontSize: typography.sizeSm, justifySelf: "end", padding: "2px 4px" },
  toastSuccess: { borderInlineStartColor: colors.success, borderInlineStartWidth: "3px" },
  toastWarning: { borderInlineStartColor: colors.warning, borderInlineStartWidth: "3px" },
  toastError: { borderInlineStartColor: colors.danger, borderInlineStartWidth: "3px" },
  toastInfo: { borderInlineStartColor: colors.info, borderInlineStartWidth: "3px" },
});
