import * as stylex from "@stylexjs/stylex";
import { colors, metrics, motion, space } from "./tokens.stylex.js";

export const statefulStyles = stylex.create({
  verticalTabs: { alignItems: "stretch", flexDirection: "column" },
  disabled: { cursor: "not-allowed", opacity: 0.5 },
  dialogLayout: {
    alignItems: "center", display: "flex", inset: 0, justifyContent: "center",
    padding: space.lg, position: "fixed", pointerEvents: "none",
  },
  backdrop: { backgroundColor: colors.overlay, inset: 0, position: "fixed" },
  panel: {
    backgroundColor: colors.popover, color: colors.popoverForeground,
    maxHeight: "calc(100dvh - 32px)", overflowY: "auto", pointerEvents: "auto",
  },
  dialogSm: { maxWidth: "600px", width: "min(100%, 600px)" },
  dialogMd: { maxWidth: "900px", width: "min(100%, 900px)" },
  dialogHeading: { alignItems: "start", display: "grid", gap: space.md, gridTemplateColumns: "minmax(0, 1fr) auto" },
  dialogHeaderActions: { alignItems: "center", display: "flex", gap: space.xs, justifyContent: "flex-end" },
  dialogDividedContent: { borderBlockColor: colors.border, borderBlockStyle: "solid", borderBlockWidth: "1px", paddingBlock: space.md },
  transition: {
    opacity: { default: 1, ':is([data-closed])': 0 },
    transitionProperty: "opacity",
    transitionDuration: { default: motion.fast, "@media (prefers-reduced-motion: reduce)": "0s" },
  },
  selectRoot: { display: "inline-block", position: "relative" },
  selectButton: {
    alignItems: "center", display: "flex", gap: space.sm, justifyContent: "space-between",
    opacity: { default: 1, ':is([data-disabled])': 0.5 },
  },
  selectContent: {
    backgroundColor: colors.popover, color: colors.popoverForeground,
    maxHeight: "min(320px, var(--available-height, 320px))", overflowY: "auto",
    minWidth: "var(--button-width, 180px)", zIndex: 50,
  },
  selectItem: { color: "inherit", cursor: "default" },
  activeItem: { backgroundColor: colors.surfaceHover, color: colors.accentForeground },
  selectedItem: { fontWeight: 600 },
  selectBackdrop: { inset: 0, position: "fixed" },
  layerRoot: { display: "inline-block", position: "relative" },
  layerBackdrop: { backgroundColor: "transparent", inset: 0, position: "fixed", zIndex: 49 },
  layerPanel: {
    backgroundColor: colors.popover, borderColor: colors.border, borderRadius: metrics.radiusMd,
    borderStyle: "solid", borderWidth: "1px", boxShadow: metrics.shadowFloat,
    color: colors.popoverForeground, maxHeight: "min(360px, var(--available-height, 360px))",
    maxWidth: "min(420px, var(--available-width, 420px))", overflowY: "auto", padding: space.sm, zIndex: 50,
  },
  layerArrow: { backgroundColor: colors.popover, borderColor: colors.border, borderStyle: "solid", borderWidth: "1px", height: "8px", position: "absolute", transform: "rotate(45deg)", width: "8px" },
  menuContent: { minWidth: "max(180px, var(--button-width, 180px))" },
  menuGroup: { display: "grid", gap: "2px" },
  menuSeparator: { backgroundColor: colors.border, height: "1px", marginBlock: space.xs },
  menuShortcut: { color: colors.foregroundMuted, marginInlineStart: "auto" },
  destructiveItem: { color: colors.danger },
  tooltipPanel: { maxWidth: "280px", zIndex: 60 },
  comboboxRoot: { display: "grid", minWidth: 0, position: "relative" },
  comboboxInputWrapper: { alignItems: "stretch", display: "grid", gridTemplateColumns: "minmax(0, 1fr) 32px" },
  comboboxInput: { borderBottomRightRadius: 0, borderTopRightRadius: 0, minWidth: 0 },
  comboboxButton: { backgroundColor: colors.surface, borderColor: colors.borderStrong, borderBottomRightRadius: metrics.radiusMd, borderStyle: "solid", borderTopRightRadius: metrics.radiusMd, borderWidth: "1px", borderInlineStartWidth: 0, color: colors.foregroundMuted, cursor: "pointer" },
  comboboxContent: { minWidth: "var(--button-width, 220px)" },
  comboboxScroll: { display: "grid", gap: "2px", maxHeight: "min(320px, var(--available-height, 320px))", overflowY: "auto" },
  toastTopLeft: { alignItems: "flex-start", flexDirection: "column", insetBlockStart: space.lg, insetInlineStart: space.lg },
  toastTopCenter: { alignItems: "center", flexDirection: "column", insetBlockStart: space.lg, insetInlineStart: "50%", transform: "translateX(-50%)" },
  toastTopRight: { alignItems: "flex-end", flexDirection: "column", insetBlockStart: space.lg, insetInlineEnd: space.lg },
  toastBottomLeft: { alignItems: "flex-start", flexDirection: "column-reverse", insetBlockEnd: space.lg, insetInlineStart: space.lg },
  toastBottomCenter: { alignItems: "center", flexDirection: "column-reverse", insetBlockEnd: space.lg, insetInlineStart: "50%", transform: "translateX(-50%)" },
  toastBottomRight: { alignItems: "flex-end", flexDirection: "column-reverse", insetBlockEnd: space.lg, insetInlineEnd: space.lg },
});
