import * as stylex from "@stylexjs/stylex";

import {
  colors,
  metrics,
  motion,
  radii,
  shadows,
  sizes,
  space,
  typography,
} from "./tokens.stylex.js";

export const buttonStyles = stylex.create({
  base: {
    alignItems: "center",
    borderColor: "transparent",
    borderRadius: "var(--radius-button)",
    borderStyle: "solid",
    borderWidth: "1px",
    cursor: "pointer",
    display: "inline-flex",
    flexShrink: 0,
    fontFamily: metrics.font,
    fontSize: typography.sizeMd,
    fontWeight: 550,
    gap: "6px",
    justifyContent: "center",
    outline: { default: "none", ":focus-visible": `3px solid ${colors.focusGlow}` },
    outlineOffset: "0px",
    transitionDuration: metrics.durationFast,
    transitionProperty: "background-color, border-color, box-shadow, color, opacity, transform",
    transitionTimingFunction: metrics.easeOut,
    transform: {
      default: "translateY(0) scale(1)",
      ":active": "translateY(1px) scale(1)",
    },
    willChange: "transform",
    whiteSpace: "nowrap",
  },
  primary: {
    backgroundColor: { default: colors.primary, ":hover": colors.primaryHover },
    borderColor: { default: colors.primary, ":hover": colors.primaryHover },
    color: colors.primaryForeground,
  },
  secondary: {
    backgroundColor: { default: colors.surfaceSubtle, ":hover": colors.surfaceHover },
    color: colors.foreground,
  },
  outline: {
    boxShadow: "var(--button-outline-shadow)",
    backgroundColor: { default: "var(--button-outline-surface)", ":hover": colors.surfaceSubtle },
    borderColor: colors.border,
    color: colors.foreground,
  },
  ghost: {
    backgroundColor: { default: "transparent", ":hover": colors.surfaceSubtle },
    borderColor: "transparent",
    color: colors.foregroundMuted,
  },
  danger: {
    backgroundColor: { default: colors.dangerSurface, ":hover": colors.dangerBorder },
    borderColor: "transparent",
    color: colors.danger,
  },
  xs: { borderRadius: "var(--radius-button-sm)", fontSize: typography.sizeSm, height: "24px", paddingLeft: "8px", paddingRight: "8px" },
  sm: { fontSize: typography.sizeSm, height: "28px", paddingLeft: "10px", paddingRight: "10px" },
  md: { height: "32px", paddingLeft: "10px", paddingRight: "10px" },
  lg: { fontSize: typography.sizeLg, height: "36px", paddingLeft: "12px", paddingRight: "12px" },
  icon: { height: "32px", padding: 0, width: "32px" },
  fullWidth: { width: "100%" },
  disabled: { cursor: "not-allowed", opacity: 0.5, pointerEvents: "none", transform: "none" },
});

export const badgeStyles = stylex.create({
  base: {
    alignItems: "center",
    borderRadius: "var(--radius-badge)",
    display: "inline-flex",
    fontSize: "12px",
    borderColor: "var(--badge-border)",
    borderStyle: "solid",
    borderWidth: "1px",
    fontWeight: 550,
    gap: "4px",
    height: "20px",
    lineHeight: 1,
    padding: "2px 8px",
    whiteSpace: "nowrap",
  },
  neutral: { backgroundColor: colors.surfaceSubtle, color: colors.foregroundMuted },
  success: { backgroundColor: colors.successSurface, color: colors.success },
  warning: { backgroundColor: colors.warningSurface, color: colors.warning },
  danger: { backgroundColor: colors.dangerSurface, color: colors.danger },
  info: { backgroundColor: colors.infoSurface, color: colors.info },
  dot: { backgroundColor: "currentColor", borderRadius: "999px", height: "6px", width: "6px" },
});

export const layoutStyles = stylex.create({
  stack: { display: "flex", flexDirection: "column" },
  row: { alignItems: "center", display: "flex" },
  gapXs: { gap: "4px" },
  gapSm: { gap: "8px" },
  gapMd: { gap: "12px" },
  gapLg: { gap: "16px" },
  between: { justifyContent: "space-between" },
  start: { alignItems: "flex-start" },
  wrap: { flexWrap: "wrap" },
});

export const toolbarStyles = stylex.create({
  root: {
    alignItems: "center",
    backgroundColor: colors.background,
    borderBottomColor: colors.border,
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    display: "flex",
    gap: "16px",
    justifyContent: "space-between",
    minHeight: "56px",
    padding: "8px 16px",
  },
  copy: { minWidth: 0 },
  title: {
    color: colors.foreground,
    fontSize: "14px",
    fontWeight: 550,
    letterSpacing: "-0.015em",
    margin: 0,
  },
  description: { color: colors.foregroundMuted, fontSize: "12px", marginBottom: 0, marginTop: "2px" },
  actions: { alignItems: "center", display: "flex", flexWrap: "wrap", gap: "8px", justifyContent: "flex-end" },
});

export const segmentedStyles = stylex.create({
  root: {
    backgroundColor: colors.surfaceSubtle,
    borderRadius: metrics.radiusLg,
    display: "inline-flex",
    height: "32px",
    padding: "3px",
  },
  item: {
    backgroundColor: { default: "transparent", ":hover": colors.surfaceHover },
    borderColor: "transparent",
    borderRadius: metrics.radiusMd,
    borderStyle: "solid",
    borderWidth: "1px",
    color: colors.foregroundMuted,
    cursor: "pointer",
    fontFamily: metrics.font,
    fontSize: "14px",
    fontWeight: 550,
    height: "26px",
    outline: { default: "none", ":focus-visible": `3px solid ${colors.focusGlow}` },
    paddingLeft: "8px",
    paddingRight: "8px",
    transform: { default: "translateY(0)", ":active": "translateY(1px)" },
    transitionDuration: motion.fast,
    transitionProperty: "background-color, box-shadow, color, transform",
    transitionTimingFunction: motion.easeOut,
  },
  active: {
    backgroundColor: colors.surface,
    boxShadow: metrics.shadowSm,
    color: colors.foreground,
  },
});

export const fieldStyles = stylex.create({
  root: { display: "flex", flexDirection: "column", gap: "8px", minWidth: 0 },
  label: { color: colors.foreground, fontSize: "14px", fontWeight: 550, lineHeight: 1 },
  description: { color: colors.foregroundMuted, fontSize: "12px", lineHeight: 1.4, margin: 0 },
  control: {
    backgroundColor: "color-mix(in oklch, var(--input) 12%, transparent)",
    borderColor: {
      default: colors.input,
      ":focus": colors.brand,
    },
    borderRadius: metrics.radiusMd,
    borderStyle: "solid",
    borderWidth: "1px",
    color: colors.foreground,
    fontFamily: metrics.font,
    fontSize: "14px",
    minHeight: "32px",
    outline: { default: "none", ":focus-visible": `3px solid ${colors.focusGlow}` },
    outlineOffset: "0px",
    paddingLeft: "10px",
    paddingRight: "10px",
    width: "100%",
    boxShadow: {
      default: "none",
    },
    transitionDuration: motion.fast,
    transitionProperty: "border-color, box-shadow",
    transitionTimingFunction: motion.easeOut,
  },
  compact: { minHeight: "28px" },
  selectControl: { minHeight: "32px", paddingRight: "28px", width: "auto" },
  textarea: { lineHeight: 1.5, minHeight: "84px", paddingBottom: "9px", paddingTop: "9px", resize: "vertical" },
  invalid: {
    borderColor: colors.danger,
    boxShadow: `0 0 0 3px color-mix(in oklch, ${colors.danger} 20%, transparent)`,
  },
  required: { color: colors.danger, marginLeft: space.xs },
  error: { color: colors.danger },
});

export const choiceStyles = stylex.create({
  root: {
    alignItems: "flex-start",
    color: colors.foreground,
    display: "flex",
    fontFamily: typography.fontFamily,
    gap: space.sm,
  },
  disabled: { cursor: "not-allowed", opacity: 0.5 },
  control: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.borderStrong,
    borderRadius: radii.sm,
    borderStyle: "solid",
    borderWidth: "1px",
    color: colors.primaryForeground,
    cursor: "pointer",
    display: "inline-flex",
    flexShrink: 0,
    height: "16px",
    justifyContent: "center",
    marginTop: "1px",
    outline: { default: "none", ":focus-visible": `3px solid ${colors.focusGlow}` },
    outlineOffset: "0px",
    padding: 0,
    transitionDuration: motion.fast,
    transitionProperty: "background-color, border-color, box-shadow",
    transitionTimingFunction: motion.easeOut,
    width: "16px",
  },
  checked: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  indeterminate: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  content: { display: "flex", flexDirection: "column", gap: "4px", minWidth: 0 },
  label: { cursor: "pointer", fontSize: "14px", fontWeight: 550, lineHeight: 1.35 },
  description: { color: colors.foregroundMuted, fontSize: "12px", lineHeight: 1.4, margin: 0 },
  hiddenInput: {
    clip: "rect(0 0 0 0)",
    clipPath: "inset(50%)",
    height: "1px",
    overflow: "hidden",
    position: "absolute",
    whiteSpace: "nowrap",
    width: "1px",
  },
});

export const switchStyles = stylex.create({
  root: {
    alignItems: "flex-start",
    color: colors.foreground,
    display: "flex",
    fontFamily: typography.fontFamily,
    gap: space.sm,
    justifyContent: "space-between",
  },
  disabled: { cursor: "not-allowed", opacity: 0.5 },
  copy: { display: "flex", flexDirection: "column", gap: "4px", minWidth: 0 },
  label: { cursor: "pointer", fontSize: "14px", fontWeight: 550, lineHeight: 1.35 },
  description: { color: colors.foregroundMuted, fontSize: "12px", lineHeight: 1.4, margin: 0 },
  control: {
    alignItems: "center",
    backgroundColor: colors.input,
    borderColor: "transparent",
    borderRadius: radii.full,
    borderStyle: "solid",
    borderWidth: "1px",
    cursor: "pointer",
    display: "inline-flex",
    flexShrink: 0,
    height: "18px",
    outline: { default: "none", ":focus-visible": `3px solid ${colors.focusGlow}` },
    outlineOffset: "0px",
    padding: "1px",
    transitionDuration: motion.fast,
    transitionProperty: "background-color, box-shadow",
    transitionTimingFunction: motion.easeOut,
    width: "32px",
  },
  checked: { backgroundColor: colors.primary },
  thumb: {
    backgroundColor: colors.surface,
    borderRadius: radii.full,
    boxShadow: shadows.sm,
    height: "16px",
    transform: "translateX(0)",
    transitionDuration: motion.fast,
    transitionProperty: "transform",
    transitionTimingFunction: motion.easeOut,
    width: "16px",
  },
  thumbChecked: { transform: "translateX(12px)" },
  hiddenInput: {
    clip: "rect(0 0 0 0)",
    clipPath: "inset(50%)",
    height: "1px",
    overflow: "hidden",
    position: "absolute",
    whiteSpace: "nowrap",
    width: "1px",
  },
});

export const fieldsetStyles = stylex.create({
  root: {
    borderColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    margin: 0,
    minWidth: 0,
    padding: 0,
  },
  disabled: { opacity: 0.55 },
  legend: {
    color: colors.foreground,
    fontFamily: typography.fontFamily,
    fontSize: "14px",
    fontWeight: 550,
    marginBottom: space.xs,
    padding: 0,
  },
  description: {
    color: colors.foregroundMuted,
    fontFamily: typography.fontFamily,
    fontSize: "12px",
    lineHeight: 1.4,
    margin: 0,
  },
  content: { display: "flex", flexDirection: "column", gap: space.sm },
});

export const disclosureStyles = stylex.create({
  root: {
    borderBottomColor: colors.border,
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
  },
  trigger: {
    alignItems: "center",
    backgroundColor: "transparent",
    border: 0,
    color: colors.foreground,
    cursor: "pointer",
    display: "flex",
    fontFamily: typography.fontFamily,
    fontSize: "14px",
    fontWeight: 550,
    gap: space.sm,
    justifyContent: "space-between",
    minHeight: sizes.controlLg,
    outline: { default: "none", ":focus-visible": `3px solid ${colors.focusGlow}` },
    outlineOffset: "0px",
    paddingLeft: "0px",
    paddingRight: "0px",
    textDecoration: { default: "none", ":hover": "underline" },
    textUnderlineOffset: "4px",
    width: "100%",
  },
  icon: {
    color: colors.foregroundMuted,
    transform: "rotate(0deg)",
    transitionDuration: motion.normal,
    transitionProperty: "transform",
    transitionTimingFunction: motion.easeOut,
  },
  iconOpen: { transform: "rotate(180deg)" },
  panel: { color: colors.foregroundMuted, fontSize: "14px", lineHeight: 1.5 },
  panelInner: { padding: "0 0 10px" },
});

export const panelStyles = stylex.create({
  root: {
    backgroundColor: colors.surface,
    borderRadius: "var(--radius-panel)",
    boxShadow: metrics.shadowPanel,
    overflow: "hidden",
  },
  header: { borderBottomColor: colors.border, borderBottomStyle: "solid", borderBottomWidth: "1px", padding: "16px" },
  title: { color: colors.foreground, fontSize: "16px", fontWeight: 550, lineHeight: 1.35, margin: 0 },
  description: { color: colors.foregroundMuted, fontSize: "14px", lineHeight: 1.45, marginBottom: 0, marginTop: "4px" },
  body: { padding: "16px" },
});
