import * as stylex from "@stylexjs/stylex";

import {
  colors,
  metrics,
  motion,
  radii,
  shadows,
  sizes,
  space,
  typography,
} from "./tokens.stylex";

export const buttonStyles = stylex.create({
  base: {
    alignItems: "center",
    borderRadius: metrics.radiusMd,
    borderStyle: "solid",
    borderWidth: "1px",
    cursor: "pointer",
    display: "inline-flex",
    flexShrink: 0,
    fontFamily: metrics.font,
    fontSize: "13px",
    fontWeight: 600,
    gap: "6px",
    justifyContent: "center",
    outline: { default: "none", ":focus-visible": `2px solid ${colors.focus}` },
    outlineOffset: "2px",
    transitionDuration: metrics.durationFast,
    transitionProperty: "background-color, border-color, box-shadow, color, opacity, transform",
    transitionTimingFunction: metrics.easeOut,
    transform: {
      default: "translateY(0) scale(1)",
      ":hover": "translateY(-1px) scale(1)",
      ":active": "translateY(0) scale(0.975)",
    },
    willChange: "transform",
    whiteSpace: "nowrap",
  },
  primary: {
    backgroundColor: { default: colors.primary, ":hover": colors.primaryHover },
    borderColor: { default: colors.primary, ":hover": colors.primaryHover },
    boxShadow: { default: metrics.shadowControl, ":hover": metrics.shadowInteractive },
    color: colors.primaryForeground,
  },
  secondary: {
    backgroundColor: { default: colors.brandSurface, ":hover": colors.surfaceHover },
    borderColor: colors.brandBorder,
    color: colors.brandForeground,
  },
  outline: {
    backgroundColor: { default: colors.surface, ":hover": colors.surfaceSubtle },
    borderColor: colors.borderStrong,
    boxShadow: { default: metrics.shadowControl, ":hover": metrics.shadowInteractive },
    color: colors.foreground,
  },
  ghost: {
    backgroundColor: { default: "transparent", ":hover": colors.surfaceSubtle },
    borderColor: "transparent",
    color: colors.foregroundMuted,
  },
  danger: {
    backgroundColor: { default: colors.surface, ":hover": colors.dangerSurface },
    borderColor: colors.dangerBorder,
    color: colors.danger,
  },
  sm: { height: "30px", paddingLeft: "10px", paddingRight: "10px" },
  md: { height: "36px", paddingLeft: "13px", paddingRight: "13px" },
  icon: { height: "32px", padding: 0, width: "32px" },
  fullWidth: { width: "100%" },
  disabled: { cursor: "not-allowed", opacity: 0.45, transform: "none" },
});

export const badgeStyles = stylex.create({
  base: {
    alignItems: "center",
    borderRadius: "999px",
    display: "inline-flex",
    fontSize: "11px",
    borderColor: "transparent",
    borderStyle: "solid",
    borderWidth: "1px",
    fontWeight: 650,
    gap: "5px",
    lineHeight: 1,
    padding: "5px 8px",
    whiteSpace: "nowrap",
  },
  neutral: { backgroundColor: colors.surfaceSubtle, color: colors.foregroundMuted },
  success: { backgroundColor: colors.successSurface, color: colors.success },
  warning: { backgroundColor: colors.warningSurface, color: colors.warning },
  danger: { backgroundColor: colors.dangerSurface, color: colors.danger },
  info: { backgroundColor: colors.infoSurface, color: colors.info },
  dot: { backgroundColor: "currentColor", borderRadius: "999px", height: "6px", width: "6px" },
});

export const layoutStyles = stylex.create({
  stack: { display: "flex", flexDirection: "column" },
  row: { alignItems: "center", display: "flex" },
  gapXs: { gap: "4px" },
  gapSm: { gap: "8px" },
  gapMd: { gap: "12px" },
  gapLg: { gap: "16px" },
  between: { justifyContent: "space-between" },
  start: { alignItems: "flex-start" },
  wrap: { flexWrap: "wrap" },
});

export const toolbarStyles = stylex.create({
  root: {
    alignItems: "center",
    backgroundColor: colors.background,
    borderBottomColor: colors.border,
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    display: "flex",
    gap: "16px",
    justifyContent: "space-between",
    minHeight: "60px",
    padding: "10px 18px",
  },
  copy: { minWidth: 0 },
  title: {
    color: colors.foreground,
    fontSize: "15px",
    fontWeight: 700,
    letterSpacing: "-0.015em",
    margin: 0,
  },
  description: { color: colors.foregroundMuted, fontSize: "11px", marginBottom: 0, marginTop: "3px" },
  actions: { alignItems: "center", display: "flex", flexWrap: "wrap", gap: "8px", justifyContent: "flex-end" },
});

export const segmentedStyles = stylex.create({
  root: {
    backgroundColor: colors.surfaceSubtle,
    borderColor: colors.border,
    borderRadius: metrics.radiusMd,
    borderStyle: "solid",
    borderWidth: "1px",
    display: "inline-flex",
    padding: "2px",
  },
  item: {
    backgroundColor: { default: "transparent", ":hover": colors.surfaceHover },
    borderRadius: metrics.radiusSm,
    borderWidth: 0,
    color: colors.foregroundMuted,
    cursor: "pointer",
    fontFamily: metrics.font,
    fontSize: "12px",
    fontWeight: 650,
    height: "29px",
    outline: { default: "none", ":focus-visible": `2px solid ${colors.focus}` },
    paddingLeft: "10px",
    paddingRight: "10px",
    transform: { default: "scale(1)", ":active": "scale(0.96)" },
    transitionDuration: motion.fast,
    transitionProperty: "background-color, box-shadow, color, transform",
    transitionTimingFunction: motion.easeOut,
  },
  active: {
    backgroundColor: colors.surface,
    boxShadow: metrics.shadowControl,
    color: colors.brandForeground,
  },
});

export const fieldStyles = stylex.create({
  root: { display: "flex", flexDirection: "column", gap: "6px", minWidth: 0 },
  label: { color: colors.foreground, fontSize: "11px", fontWeight: 600 },
  description: { color: colors.foregroundMuted, fontSize: "10px", lineHeight: 1.45, margin: 0 },
  control: {
    backgroundColor: colors.surface,
    borderColor: {
      default: colors.input,
      ":hover": colors.borderStrong,
      ":focus": colors.brand,
    },
    borderRadius: metrics.radiusMd,
    borderStyle: "solid",
    borderWidth: "1px",
    color: colors.foreground,
    fontFamily: metrics.font,
    fontSize: "12px",
    minHeight: "38px",
    outline: { default: "none", ":focus-visible": `2px solid ${colors.focus}` },
    outlineOffset: "1px",
    paddingLeft: "10px",
    paddingRight: "10px",
    width: "100%",
    boxShadow: {
      default: "inset 0 1px 1px oklch(0.29 0.055 252 / 3%)",
      ":hover": shadows.control,
      ":focus": `0 0 0 3px ${colors.focusGlow}`,
    },
    transitionDuration: motion.fast,
    transitionProperty: "border-color, box-shadow",
    transitionTimingFunction: motion.easeOut,
  },
  compact: { minHeight: "32px" },
  selectControl: { minHeight: "32px", paddingRight: "28px", width: "auto" },
  textarea: { lineHeight: 1.5, minHeight: "84px", paddingBottom: "9px", paddingTop: "9px", resize: "vertical" },
  invalid: {
    borderColor: colors.danger,
    outlineColor: colors.danger,
  },
  required: { color: colors.danger, marginLeft: space.xs },
  error: { color: colors.danger },
});

export const choiceStyles = stylex.create({
  root: {
    alignItems: "flex-start",
    color: colors.foreground,
    display: "flex",
    fontFamily: typography.fontFamily,
    gap: space.sm,
  },
  disabled: { cursor: "not-allowed", opacity: 0.5 },
  control: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.borderStrong,
    borderRadius: radii.sm,
    borderStyle: "solid",
    borderWidth: "1px",
    color: colors.primaryForeground,
    cursor: "pointer",
    display: "inline-flex",
    flexShrink: 0,
    height: "18px",
    justifyContent: "center",
    marginTop: "1px",
    outline: { default: "none", ":focus-visible": `2px solid ${colors.focus}` },
    outlineOffset: "2px",
    padding: 0,
    transitionDuration: motion.fast,
    transitionProperty: "background-color, border-color, box-shadow",
    transitionTimingFunction: motion.easeOut,
    width: "18px",
  },
  checked: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
    boxShadow: `0 1px 3px ${colors.focusGlow}`,
  },
  indeterminate: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  content: { display: "flex", flexDirection: "column", gap: space.xs, minWidth: 0 },
  label: { cursor: "pointer", fontSize: typography.sizeSm, fontWeight: typography.weightMedium, lineHeight: 1.35 },
  description: { color: colors.foregroundMuted, fontSize: typography.sizeXs, lineHeight: typography.lineHeightNormal, margin: 0 },
  hiddenInput: {
    clip: "rect(0 0 0 0)",
    clipPath: "inset(50%)",
    height: "1px",
    overflow: "hidden",
    position: "absolute",
    whiteSpace: "nowrap",
    width: "1px",
  },
});

export const switchStyles = stylex.create({
  root: {
    alignItems: "flex-start",
    color: colors.foreground,
    display: "flex",
    fontFamily: typography.fontFamily,
    gap: space.sm,
    justifyContent: "space-between",
  },
  disabled: { cursor: "not-allowed", opacity: 0.5 },
  copy: { display: "flex", flexDirection: "column", gap: space.xs, minWidth: 0 },
  label: { cursor: "pointer", fontSize: typography.sizeSm, fontWeight: typography.weightMedium, lineHeight: 1.35 },
  description: { color: colors.foregroundMuted, fontSize: typography.sizeXs, lineHeight: typography.lineHeightNormal, margin: 0 },
  control: {
    alignItems: "center",
    backgroundColor: colors.input,
    borderColor: "transparent",
    borderRadius: radii.full,
    borderStyle: "solid",
    borderWidth: "1px",
    cursor: "pointer",
    display: "inline-flex",
    flexShrink: 0,
    height: "20px",
    outline: { default: "none", ":focus-visible": `2px solid ${colors.focus}` },
    outlineOffset: "2px",
    padding: "2px",
    transitionDuration: motion.fast,
    boxShadow: "inset 0 0 0 1px oklch(0.29 0.055 252 / 4%)",
    transitionProperty: "background-color, box-shadow",
    transitionTimingFunction: motion.easeOut,
    width: "36px",
  },
  checked: { backgroundColor: colors.primary, boxShadow: `0 1px 4px ${colors.focusGlow}` },
  thumb: {
    backgroundColor: colors.surface,
    borderRadius: radii.full,
    boxShadow: shadows.sm,
    height: "14px",
    transform: "translateX(0)",
    transitionDuration: motion.fast,
    transitionProperty: "transform",
    transitionTimingFunction: motion.easeOut,
    width: "14px",
  },
  thumbChecked: { transform: "translateX(16px)" },
  hiddenInput: {
    clip: "rect(0 0 0 0)",
    clipPath: "inset(50%)",
    height: "1px",
    overflow: "hidden",
    position: "absolute",
    whiteSpace: "nowrap",
    width: "1px",
  },
});

export const fieldsetStyles = stylex.create({
  root: {
    borderColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: space.md,
    margin: 0,
    minWidth: 0,
    padding: 0,
  },
  disabled: { opacity: 0.55 },
  legend: {
    color: colors.foreground,
    fontFamily: typography.fontFamily,
    fontSize: typography.sizeSm,
    fontWeight: typography.weightSemibold,
    marginBottom: space.xs,
    padding: 0,
  },
  description: {
    color: colors.foregroundMuted,
    fontFamily: typography.fontFamily,
    fontSize: typography.sizeXs,
    lineHeight: typography.lineHeightNormal,
    margin: 0,
  },
  content: { display: "flex", flexDirection: "column", gap: space.sm },
});

export const disclosureStyles = stylex.create({
  root: {
    borderTopColor: colors.border,
    borderTopStyle: "solid",
    borderTopWidth: "1px",
    borderBottomColor: colors.border,
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
  },
  trigger: {
    alignItems: "center",
    backgroundColor: { default: "transparent", ":hover": colors.surfaceSubtle },
    border: 0,
    color: colors.foreground,
    cursor: "pointer",
    display: "flex",
    fontFamily: typography.fontFamily,
    fontSize: typography.sizeSm,
    fontWeight: typography.weightSemibold,
    gap: space.sm,
    justifyContent: "space-between",
    minHeight: sizes.controlLg,
    outline: { default: "none", ":focus-visible": `2px solid ${colors.focus}` },
    outlineOffset: "-2px",
    paddingLeft: space.xs,
    paddingRight: space.xs,
    width: "100%",
  },
  icon: {
    color: colors.foregroundMuted,
    transform: "rotate(0deg)",
    transitionDuration: motion.normal,
    transitionProperty: "transform",
    transitionTimingFunction: motion.easeOut,
  },
  iconOpen: { transform: "rotate(180deg)" },
  panel: { color: colors.foregroundMuted, fontSize: typography.sizeSm, lineHeight: typography.lineHeightNormal },
  panelInner: { padding: `${space.sm} ${space.sm} ${space.lg}` },
});

export const panelStyles = stylex.create({
  root: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: metrics.radiusLg,
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: metrics.shadowPanel,
    overflow: "hidden",
  },
  header: { borderBottomColor: colors.border, borderBottomStyle: "solid", borderBottomWidth: "1px", padding: "15px 18px" },
  title: { color: colors.foreground, fontSize: "13px", fontWeight: 700, letterSpacing: "-0.01em", margin: 0 },
  description: { color: colors.foregroundMuted, fontSize: "11px", lineHeight: 1.45, marginBottom: 0, marginTop: "4px" },
  body: { padding: "18px" },
});
