import * as stylex from "@stylexjs/stylex";

export const colors = stylex.defineConsts({
  background: "var(--foldworks-ui-background)",
  canvas: "var(--foldworks-ui-canvas)",
  surface: "var(--foldworks-ui-surface)",
  surfaceSubtle: "var(--foldworks-ui-surface-subtle)",
  surfaceHover: "var(--foldworks-ui-surface-hover)",
  foreground: "var(--foldworks-ui-foreground)",
  foregroundMuted: "var(--foldworks-ui-foreground-muted)",
  foregroundSubtle: "var(--foldworks-ui-foreground-subtle)",
  border: "var(--foldworks-ui-border)",
  borderStrong: "var(--foldworks-ui-border-strong)",
  input: "var(--foldworks-ui-input)",
  primary: "var(--foldworks-ui-primary)",
  primaryHover: "var(--foldworks-ui-primary-hover)",
  primaryForeground: "var(--foldworks-ui-primary-foreground)",
  focus: "var(--foldworks-ui-focus)",
  success: "var(--foldworks-ui-success)",
  successSurface: "var(--foldworks-ui-success-surface)",
  warning: "var(--foldworks-ui-warning)",
  warningSurface: "var(--foldworks-ui-warning-surface)",
  danger: "var(--foldworks-ui-danger)",
  dangerSurface: "var(--foldworks-ui-danger-surface)",
  dangerBorder: "var(--foldworks-ui-danger-border)",
  info: "var(--foldworks-ui-info)",
  infoSurface: "var(--foldworks-ui-info-surface)",
  selection: "var(--foldworks-ui-selection)",
  selectionForeground: "var(--foldworks-ui-selection-foreground)",
  selectionBorder: "var(--foldworks-ui-selection-border)",
  dropTarget: "var(--foldworks-ui-drop-target)",
  dropTargetBorder: "var(--foldworks-ui-drop-target-border)",
  dropTargetActive: "var(--foldworks-ui-drop-target-active)",
  dropTargetActiveBorder: "var(--foldworks-ui-drop-target-active-border)",
  overlay: "var(--foldworks-ui-overlay)",
});

export const metrics = stylex.defineConsts({
  radiusSm: "var(--foldworks-ui-radius-sm)",
  radiusMd: "var(--foldworks-ui-radius-md)",
  radiusLg: "var(--foldworks-ui-radius-lg)",
  shadowSm: "var(--foldworks-ui-shadow-sm)",
  shadowPanel: "var(--foldworks-ui-shadow-panel)",
  shadowFloat: "var(--foldworks-ui-shadow-float)",
  shadowSheet: "var(--foldworks-ui-shadow-sheet)",
  durationFast: "var(--foldworks-ui-duration-fast)",
  durationNormal: "var(--foldworks-ui-duration-normal)",
  easeOut: "var(--foldworks-ui-ease-out)",
  font: "var(--foldworks-ui-font)",
});
