import * as stylex from "@stylexjs/stylex";

export const className = (...values: ReadonlyArray<stylex.StyleXStyles>) =>
  stylex.props(...values).className ?? "";

const focusRing = {
  default: "none",
  ":focus-visible": "2px solid var(--foldworks-ui-focus)",
};

export const styles = stylex.create({
  workspace: {
    display: "grid",
    gridTemplateColumns: {
      default: "minmax(0, 1fr) 300px",
      "@media (max-width: 1100px)": "minmax(0, 1fr) 260px",
      "@media (max-width: 820px)": "1fr",
    },
    height: "100%",
    minHeight: 0,
    minWidth: 0,
  },
  stage: {
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr)",
    minHeight: 0,
    minWidth: 0,
    position: "relative",
  },
  breadcrumbs: {
    alignItems: "center",
    backgroundColor: "var(--foldworks-ui-background)",
    borderBottomColor: "var(--foldworks-ui-border)",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    display: "flex",
    flexWrap: "wrap",
    fontSize: "12px",
    gap: "6px",
    minHeight: "40px",
    padding: "6px 16px",
  },
  crumb: {
    backgroundColor: {
      default: "transparent",
      ":hover": "var(--foldworks-ui-surface-hover)",
    },
    borderRadius: "6px",
    borderWidth: 0,
    color: "var(--foldworks-ui-foreground-muted)",
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: "12px",
    fontWeight: 600,
    outline: focusRing,
    padding: "4px 7px",
  },
  crumbCurrent: {
    color: "var(--foldworks-ui-foreground)",
    cursor: "default",
    fontWeight: 750,
  },
  crumbSeparator: {
    color: "var(--foldworks-ui-foreground-subtle)",
  },
  crumbMeta: {
    color: "var(--foldworks-ui-foreground-subtle)",
    marginLeft: "auto",
  },
  viewport: {
    backgroundColor: "var(--foldworks-ui-canvas)",
    backgroundImage:
      "radial-gradient(circle, color-mix(in oklch, var(--foldworks-ui-foreground-subtle) 32%, transparent) 1px, transparent 1px)",
    backgroundSize: "14px 14px",
    cursor: "grab",
    minHeight: 0,
    overflow: "hidden",
    position: "relative",
    userSelect: "none",
  },
  viewportPanning: {
    cursor: "grabbing",
  },
  world: {
    left: 0,
    position: "absolute",
    top: 0,
    transformOrigin: "0 0",
  },
  edgeLayer: {
    left: 0,
    maxWidth: "none",
    overflow: "visible",
    pointerEvents: "none",
    position: "absolute",
    top: 0,
    zIndex: 1,
  },
  edgePath: {
    fill: "none",
    stroke: "color-mix(in oklch, var(--foldworks-ui-foreground) 42%, transparent)",
    strokeLinecap: "round",
    strokeWidth: 1.6,
    transitionDuration: "160ms",
    transitionProperty: "stroke, stroke-width, opacity",
  },
  edgeArrow: {
    fill: "color-mix(in oklch, var(--foldworks-ui-foreground) 42%, transparent)",
    stroke: "none",
  },
  edgeSelected: {
    stroke: "var(--foldworks-ui-primary)",
    strokeWidth: 2.4,
  },
  edgeEnabled: {
    stroke: "var(--foldworks-ui-success)",
    strokeWidth: 2.4,
  },
  arrowSelected: {
    fill: "var(--foldworks-ui-primary)",
  },
  arrowEnabled: {
    fill: "var(--foldworks-ui-success)",
  },
  edgeDimmed: {
    opacity: 0.35,
  },
  edgeHit: {
    cursor: "pointer",
    fill: "none",
    pointerEvents: "stroke",
    stroke: "transparent",
    strokeWidth: 14,
  },
  attachment: {
    fill: "none",
    stroke: "color-mix(in oklch, var(--foldworks-ui-warning, #d59b00) 60%, transparent)",
    strokeDasharray: "3 4",
    strokeWidth: 1.2,
  },
  preview: {
    fill: "none",
    stroke: "var(--foldworks-ui-primary)",
    strokeDasharray: "6 5",
    strokeWidth: 2,
  },
  previewInvalid: {
    stroke: "var(--foldworks-ui-danger)",
  },
  node: {
    backgroundColor: "var(--foldworks-ui-surface)",
    borderColor: "var(--foldworks-ui-border)",
    borderRadius: "12px",
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: "var(--foldworks-ui-shadow-sm)",
    boxSizing: "border-box",
    color: "var(--foldworks-ui-foreground)",
    cursor: "grab",
    left: 0,
    outline: focusRing,
    outlineOffset: "3px",
    position: "absolute",
    top: 0,
    transitionDuration: "160ms",
    transitionProperty: "border-color, box-shadow, background-color, opacity",
    zIndex: 2,
  },
  container: {
    backgroundColor: "color-mix(in oklch, var(--foldworks-ui-surface-subtle) 72%, transparent)",
    borderRadius: "16px",
    boxShadow: "none",
    zIndex: 0,
  },
  parallel: {
    borderStyle: "dashed",
  },
  submachine: {
    borderWidth: "1.5px",
    boxShadow: "var(--foldworks-ui-shadow-sm), inset 0 0 0 3px var(--foldworks-ui-surface-subtle)",
  },
  pseudo: {
    backgroundColor: "var(--foldworks-ui-foreground)",
    borderColor: "var(--foldworks-ui-foreground)",
    borderRadius: "999px",
    boxShadow: "none",
  },
  final: {
    backgroundColor: "var(--foldworks-ui-surface)",
    borderColor: "var(--foldworks-ui-foreground)",
    borderRadius: "999px",
    borderWidth: "2px",
    boxShadow:
      "inset 0 0 0 4px var(--foldworks-ui-surface), inset 0 0 0 12px var(--foldworks-ui-foreground)",
  },
  selected: {
    borderColor: "var(--foldworks-ui-primary)",
    boxShadow: "0 0 0 3px color-mix(in oklch, var(--foldworks-ui-primary) 22%, transparent)",
  },
  dragging: {
    opacity: 0.86,
    zIndex: 5,
  },
  dropTarget: {
    backgroundColor: "var(--foldworks-ui-drop-target)",
    borderColor: "var(--foldworks-ui-drop-target-active-border)",
    borderStyle: "solid",
  },
  connectTarget: {
    borderColor: "var(--foldworks-ui-primary)",
    boxShadow: "0 0 0 4px color-mix(in oklch, var(--foldworks-ui-primary) 28%, transparent)",
  },
  connectInvalid: {
    borderColor: "var(--foldworks-ui-danger)",
  },
  active: {
    borderColor: "var(--foldworks-ui-success)",
    boxShadow: "0 0 0 3px color-mix(in oklch, var(--foldworks-ui-success) 26%, transparent)",
  },
  activeContainer: {
    borderColor: "color-mix(in oklch, var(--foldworks-ui-success) 70%, var(--foldworks-ui-border))",
  },
  nodeHeader: {
    alignItems: "center",
    display: "flex",
    gap: "8px",
    height: "100%",
    justifyContent: "space-between",
    padding: "0 12px",
  },
  containerHeader: {
    alignItems: "center",
    display: "flex",
    gap: "8px",
    height: "36px",
    justifyContent: "space-between",
    padding: "0 14px",
  },
  nodeName: {
    fontSize: "13px",
    fontWeight: 700,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  nodeKind: {
    color: "var(--foldworks-ui-foreground-subtle)",
    fontSize: "10px",
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    whiteSpace: "nowrap",
  },
  openButton: {
    backgroundColor: {
      default: "var(--foldworks-ui-surface-subtle)",
      ":hover": "var(--foldworks-ui-surface-hover)",
    },
    borderColor: "var(--foldworks-ui-border)",
    borderRadius: "6px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--foldworks-ui-foreground)",
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: "11px",
    fontWeight: 700,
    outline: focusRing,
    padding: "3px 8px",
  },
  port: {
    backgroundColor: "var(--foldworks-ui-surface)",
    borderColor: "var(--foldworks-ui-primary)",
    borderRadius: "999px",
    borderStyle: "solid",
    borderWidth: "2px",
    cursor: "crosshair",
    height: "12px",
    opacity: {
      default: 0,
      ":hover": 1,
    },
    position: "absolute",
    transform: "translate(-50%, -50%)",
    transitionDuration: "120ms",
    transitionProperty: "opacity, transform",
    width: "12px",
    zIndex: 3,
  },
  portVisible: {
    opacity: 1,
  },
  label: {
    backgroundColor: "var(--foldworks-ui-surface)",
    borderColor: "var(--foldworks-ui-border)",
    borderRadius: "999px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--foldworks-ui-foreground-muted)",
    cursor: "pointer",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: "10px",
    fontWeight: 700,
    left: 0,
    outline: focusRing,
    padding: "2px 8px",
    position: "absolute",
    top: 0,
    transform: "translate(-50%, -50%)",
    whiteSpace: "nowrap",
    zIndex: 4,
  },
  labelSelected: {
    borderColor: "var(--foldworks-ui-primary)",
    color: "var(--foldworks-ui-primary)",
  },
  labelEnabled: {
    backgroundColor: "var(--foldworks-ui-success-surface)",
    borderColor: "var(--foldworks-ui-success)",
    color: "var(--foldworks-ui-success)",
  },
  guard: {
    color: "var(--foldworks-ui-foreground-subtle)",
    fontWeight: 500,
    marginLeft: "4px",
  },
  note: {
    backgroundColor: "color-mix(in oklch, #f7d774 30%, var(--foldworks-ui-surface))",
    borderColor: "color-mix(in oklch, #d59b00 40%, var(--foldworks-ui-border))",
    borderRadius: "4px 4px 12px 4px",
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: "var(--foldworks-ui-shadow-sm)",
    boxSizing: "border-box",
    color: "var(--foldworks-ui-foreground)",
    cursor: "grab",
    fontSize: "12px",
    left: 0,
    lineHeight: 1.45,
    outline: focusRing,
    outlineOffset: "3px",
    overflow: "hidden",
    padding: "10px 12px",
    position: "absolute",
    top: 0,
    zIndex: 3,
  },
  zoomBar: {
    alignItems: "center",
    backgroundColor: "var(--foldworks-ui-surface)",
    borderColor: "var(--foldworks-ui-border)",
    borderRadius: "10px",
    borderStyle: "solid",
    borderWidth: "1px",
    bottom: "14px",
    boxShadow: "var(--foldworks-ui-shadow-sm)",
    display: "flex",
    gap: "2px",
    left: "14px",
    padding: "3px",
    position: "absolute",
    zIndex: 6,
  },
  zoomValue: {
    color: "var(--foldworks-ui-foreground-muted)",
    fontSize: "11px",
    fontVariantNumeric: "tabular-nums",
    fontWeight: 700,
    minWidth: "44px",
    textAlign: "center",
  },
  hint: {
    backgroundColor: "color-mix(in oklch, var(--foldworks-ui-surface) 88%, transparent)",
    borderRadius: "8px",
    bottom: "14px",
    color: "var(--foldworks-ui-foreground-muted)",
    fontSize: "11px",
    padding: "6px 10px",
    pointerEvents: "none",
    position: "absolute",
    right: "14px",
    zIndex: 6,
  },
  inspector: {
    backgroundColor: "var(--foldworks-ui-background)",
    borderLeftColor: "var(--foldworks-ui-border)",
    borderLeftStyle: "solid",
    borderLeftWidth: "1px",
    display: {
      default: "flex",
      "@media (max-width: 820px)": "none",
    },
    flexDirection: "column",
    gap: "14px",
    minHeight: 0,
    overflowY: "auto",
    padding: "18px 16px 24px",
  },
  eyebrow: {
    color: "var(--foldworks-ui-foreground-subtle)",
    fontSize: "10px",
    fontWeight: 700,
    letterSpacing: "0.12em",
    margin: 0,
    textTransform: "uppercase",
  },
  heading: {
    fontSize: "15px",
    fontWeight: 760,
    letterSpacing: "-0.01em",
    margin: 0,
  },
  muted: {
    color: "var(--foldworks-ui-foreground-muted)",
    fontSize: "12px",
    lineHeight: 1.5,
    margin: 0,
  },
  list: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    listStyle: "none",
    margin: 0,
    padding: 0,
  },
  listButton: {
    alignItems: "center",
    backgroundColor: {
      default: "var(--foldworks-ui-surface)",
      ":hover": "var(--foldworks-ui-surface-hover)",
    },
    borderColor: "var(--foldworks-ui-border)",
    borderRadius: "8px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--foldworks-ui-foreground)",
    cursor: "pointer",
    display: "flex",
    fontFamily: "inherit",
    fontSize: "12px",
    gap: "8px",
    justifyContent: "space-between",
    outline: focusRing,
    padding: "7px 10px",
    textAlign: "left",
    width: "100%",
  },
  eventButton: {
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: "11px",
    fontWeight: 700,
  },
  issue: {
    borderColor:
      "color-mix(in oklch, var(--foldworks-ui-warning, #d59b00) 50%, var(--foldworks-ui-border))",
  },
  log: {
    color: "var(--foldworks-ui-foreground-muted)",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: "11px",
    lineHeight: 1.6,
    margin: 0,
    paddingLeft: "16px",
  },
  stats: {
    display: "grid",
    gap: "8px",
    gridTemplateColumns: "repeat(3, 1fr)",
  },
  stat: {
    backgroundColor: "var(--foldworks-ui-surface-subtle)",
    borderRadius: "8px",
    display: "flex",
    flexDirection: "column",
    gap: "2px",
    padding: "8px 10px",
  },
  statValue: {
    fontSize: "16px",
    fontWeight: 760,
  },
  statLabel: {
    color: "var(--foldworks-ui-foreground-subtle)",
    fontSize: "10px",
    fontWeight: 700,
    textTransform: "uppercase",
  },
  paletteList: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    listStyle: "none",
    margin: 0,
    padding: 0,
  },
  paletteButton: {
    alignItems: "center",
    backgroundColor: {
      default: "var(--foldworks-ui-background)",
      ":hover": "var(--foldworks-ui-surface-subtle)",
    },
    borderColor: {
      default: "var(--foldworks-ui-border)",
      ":hover": "var(--foldworks-ui-border-strong)",
    },
    borderRadius: "10px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--foldworks-ui-foreground)",
    cursor: "pointer",
    display: "grid",
    fontFamily: "inherit",
    gap: "10px",
    gridTemplateColumns: "30px 1fr",
    outline: focusRing,
    padding: "8px 10px",
    textAlign: "left",
    width: "100%",
  },
  paletteIcon: {
    alignItems: "center",
    backgroundColor: "var(--foldworks-ui-surface-subtle)",
    borderRadius: "8px",
    display: "flex",
    height: "30px",
    justifyContent: "center",
    width: "30px",
  },
  paletteName: {
    fontSize: "12px",
    fontWeight: 700,
    margin: 0,
  },
  paletteDescription: {
    color: "var(--foldworks-ui-foreground-muted)",
    fontSize: "11px",
    lineHeight: 1.35,
    margin: 0,
  },
  paletteSection: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    marginBottom: "18px",
  },
  paletteLabel: {
    color: "var(--foldworks-ui-foreground-subtle)",
    fontSize: "10px",
    fontWeight: 700,
    letterSpacing: "0.12em",
    margin: 0,
    paddingLeft: "4px",
    textTransform: "uppercase",
  },
  toolbar: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: "6px",
  },
});
