import * as stylex from "@stylexjs/stylex";

export const className = (...values: ReadonlyArray<stylex.StyleXStyles>) =>
  stylex.props(...values).className ?? "";

export const formStyles = stylex.create({
  workspace: {
    backgroundColor: "#f5f6f8",
    display: "grid",
    gridTemplateColumns: {
      default: "260px minmax(420px, 1fr) 280px",
      "@media (max-width: 1120px)": "230px minmax(380px, 1fr)",
    },
    minHeight: 0,
    overflow: "hidden",
  },
  outline: {
    backgroundColor: "#ffffff",
    borderRightColor: "#e1e5ea",
    borderRightStyle: "solid",
    borderRightWidth: "1px",
    minHeight: 0,
    overflowY: "auto",
    padding: "16px 12px 24px",
  },
  panelHeader: {
    alignItems: "center",
    display: "flex",
    justifyContent: "space-between",
    marginBottom: "12px",
    paddingLeft: "4px",
    paddingRight: "4px",
  },
  panelTitle: {
    color: "#727d8c",
    fontSize: "10px",
    fontWeight: 800,
    letterSpacing: "0.12em",
    margin: 0,
    textTransform: "uppercase",
  },
  paletteButton: {
    alignItems: "center",
    backgroundColor: {
      default: "var(--foldworks-ui-background)",
      ":hover": "var(--foldworks-ui-surface-subtle)",
    },
    borderColor: "var(--foldworks-ui-border)",
    borderRadius: "10px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--foldworks-ui-foreground)",
    cursor: "grab",
    display: "flex",
    fontFamily: "inherit",
    fontSize: "11px",
    fontWeight: 700,
    gap: "8px",
    minHeight: "38px",
    outline: { default: "none", ":focus-visible": "2px solid var(--foldworks-ui-focus)" },
    paddingLeft: "10px",
    textAlign: "left",
    width: "100%",
  },
  paletteRow: {
    alignItems: "stretch",
    display: "grid",
    gap: "5px",
    gridTemplateColumns: "minmax(0, 1fr) 34px",
    marginTop: "7px",
  },
  paletteAdd: {
    backgroundColor: {
      default: "var(--foldworks-ui-surface-subtle)",
      ":hover": "var(--foldworks-ui-surface-hover)",
    },
    borderColor: "var(--foldworks-ui-border)",
    borderRadius: "10px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--foldworks-ui-foreground)",
    cursor: "pointer",
    fontSize: "16px",
    outline: { default: "none", ":focus-visible": "2px solid var(--foldworks-ui-focus)" },
  },
  addIconButton: {
    alignItems: "center",
    backgroundColor: {
      default: "#f4f6f8",
      ":hover": "#e9f5f0",
    },
    borderColor: "#dfe4e9",
    borderRadius: "7px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "#4c5a69",
    cursor: "pointer",
    display: "flex",
    fontSize: "16px",
    height: "28px",
    justifyContent: "center",
    outline: { default: "none", ":focus-visible": "3px solid #83cdb0" },
    width: "28px",
  },
  sectionCard: {
    backgroundColor: "#f7f8fa",
    borderColor: "#e4e7eb",
    borderRadius: "10px",
    borderStyle: "solid",
    borderWidth: "1px",
    marginBottom: "8px",
    overflow: "hidden",
  },
  sectionHeader: {
    alignItems: "center",
    display: "grid",
    gap: "8px",
    gridTemplateColumns: "14px minmax(0, 1fr)",
    padding: "10px",
  },
  dragHandle: {
    color: "#9aa3af",
    cursor: "grab",
    fontSize: "12px",
    userSelect: "none",
  },
  outlineButton: {
    backgroundColor: "transparent",
    borderWidth: 0,
    color: "#26313e",
    cursor: "pointer",
    minWidth: 0,
    outline: { default: "none", ":focus-visible": "2px solid #58b58f" },
    padding: 0,
    textAlign: "left",
  },
  outlineTitle: {
    display: "block",
    fontSize: "11px",
    fontWeight: 750,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  actorBadge: {
    backgroundColor: "#eaf6f1",
    borderRadius: "999px",
    color: "#34785e",
    display: "inline-block",
    fontSize: "9px",
    fontWeight: 750,
    marginTop: "4px",
    padding: "3px 6px",
  },
  pageList: {
    borderTopColor: "#e6e9ed",
    borderTopStyle: "solid",
    borderTopWidth: "1px",
    padding: "6px",
  },
  pageRow: {
    alignItems: "center",
    borderRadius: "7px",
    display: "grid",
    gap: "7px",
    gridTemplateColumns: "12px minmax(0, 1fr)",
    minHeight: "31px",
    padding: "4px 7px",
  },
  pageRowActive: {
    backgroundColor: "#eaf6f1",
  },
  addPageButton: {
    backgroundColor: "transparent",
    borderWidth: 0,
    color: "#778392",
    cursor: "pointer",
    fontSize: "10px",
    fontWeight: 700,
    padding: "7px 8px 5px 26px",
    textAlign: "left",
    width: "100%",
  },
  dropLine: {
    backgroundColor: "transparent",
    borderRadius: "999px",
    height: "6px",
    marginBottom: "2px",
    marginTop: "2px",
    transition: "background-color 120ms ease, height 120ms ease",
  },
  dropLineActive: {
    backgroundColor: "#38bd88",
    height: "8px",
  },
  pageReceiver: {
    borderColor: "transparent",
    borderRadius: "7px",
    borderStyle: "solid",
    borderWidth: "1px",
  },
  pageReceiverActive: {
    backgroundColor: "#eaf8f2",
    borderColor: "#42bd8b",
  },
  canvasViewport: {
    minHeight: 0,
    overflowY: "auto",
    padding: "24px 28px 80px",
  },
  canvas: {
    marginLeft: "auto",
    marginRight: "auto",
    maxWidth: "680px",
  },
  canvasEyebrow: {
    color: "#278463",
    fontSize: "10px",
    fontWeight: 800,
    letterSpacing: "0.1em",
    marginBottom: "8px",
    marginTop: 0,
    textTransform: "uppercase",
  },
  canvasTitle: {
    color: "#17202b",
    fontSize: "24px",
    fontWeight: 780,
    letterSpacing: "-0.03em",
    margin: 0,
  },
  canvasDescription: {
    color: "#7a8593",
    fontSize: "12px",
    lineHeight: 1.5,
    marginBottom: "20px",
    marginTop: "6px",
  },
  fieldCard: {
    backgroundColor: "#ffffff",
    borderColor: {
      default: "#e1e5ea",
      ":hover": "#a9cdbc",
    },
    borderRadius: "11px",
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: "0 3px 12px rgba(31, 41, 55, 0.035)",
    cursor: "pointer",
    marginBottom: "8px",
    outline: { default: "none", ":focus-visible": "3px solid #88d4b6" },
    padding: "14px 15px",
    position: "relative",
    transition: "border-color 150ms ease, transform 180ms ease, box-shadow 150ms ease",
  },
  fieldCardSelected: {
    borderColor: "#34af80",
    boxShadow: "0 0 0 2px rgba(52, 175, 128, 0.13)",
  },
  draggingSource: {
    backgroundColor: "transparent",
    borderStyle: "dashed",
    boxShadow: "none",
  },
  draggingContent: { opacity: 0.28 },
  fieldChrome: {
    alignItems: "center",
    display: "flex",
    justifyContent: "space-between",
    marginBottom: "10px",
  },
  fieldType: {
    color: "#8b95a2",
    fontSize: "9px",
    fontWeight: 800,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  fieldHandle: { color: "#a5adb8", cursor: "grab", fontSize: "12px" },
  fieldLabel: {
    color: "#242e3b",
    display: "block",
    fontSize: "12px",
    fontWeight: 720,
    marginBottom: "7px",
  },
  required: { color: "#c6534b", marginLeft: "3px" },
  fieldDescription: {
    color: "#838d9a",
    fontSize: "10px",
    lineHeight: 1.45,
    marginBottom: "8px",
    marginTop: "-3px",
  },
  previewInput: {
    backgroundColor: "#ffffff",
    borderColor: "#d8dde4",
    borderRadius: "8px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "#26313e",
    fontFamily: "inherit",
    fontSize: "12px",
    minHeight: "39px",
    outline: { default: "none", ":focus": "2px solid #55b98f" },
    paddingLeft: "11px",
    paddingRight: "11px",
    width: "100%",
  },
  previewTextarea: { minHeight: "82px", paddingBottom: "9px", paddingTop: "9px", resize: "vertical" },
  checkboxRow: {
    alignItems: "center",
    color: "#303b48",
    display: "flex",
    fontSize: "12px",
    gap: "8px",
  },
  contentBlock: {
    backgroundColor: "#f4f8f6",
    borderColor: "#dceae4",
    borderRadius: "9px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "#66746e",
    fontSize: "11px",
    lineHeight: 1.55,
    overflowX: "auto",
    padding: "14px",
  },
  contentHeading: { color: "#24342e", fontSize: "14px", lineHeight: 1.3, marginBottom: "7px", marginTop: "12px" },
  contentParagraph: { marginBottom: "7px", marginTop: "6px" },
  markdownInlineCode: {
    backgroundColor: "#e3ece8",
    borderRadius: "4px",
    color: "#344c42",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    paddingLeft: "4px",
    paddingRight: "4px",
  },
  markdownCodeBlock: {
    backgroundColor: "#24342e",
    borderRadius: "7px",
    color: "#e8f3ee",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    overflowX: "auto",
    padding: "10px",
    whiteSpace: "pre-wrap",
  },
  markdownError: {
    color: "#a84740",
    fontWeight: 700,
    marginBottom: "8px",
    marginTop: 0,
  },
  markdownSource: {
    margin: 0,
    overflowX: "auto",
    whiteSpace: "pre-wrap",
  },
  emptyPage: {
    borderColor: "#ced6df",
    borderRadius: "12px",
    borderStyle: "dashed",
    borderWidth: "1px",
    color: "#8b95a2",
    fontSize: "12px",
    padding: "38px 20px",
    textAlign: "center",
  },
  settings: {
    backgroundColor: "#ffffff",
    borderLeftColor: "#e1e5ea",
    borderLeftStyle: "solid",
    borderLeftWidth: "1px",
    minHeight: 0,
    overflowY: "auto",
    padding: "18px",
  },
  settingsHidden: {
    display: {
      default: "block",
      "@media (max-width: 1120px)": "none",
    },
  },
  settingsEmpty: { color: "#87919f", fontSize: "11px", lineHeight: 1.6, marginTop: "36px" },
  field: { display: "flex", flexDirection: "column", gap: "6px", marginBottom: "14px" },
  modeBar: {
    alignItems: "center",
    display: "flex",
    gap: "10px",
  },
  runnerViewport: { backgroundColor: "#eef1f4", minHeight: 0, overflowY: "auto", padding: "26px" },
  runner: { marginLeft: "auto", marginRight: "auto", maxWidth: "760px" },
  runnerTop: { alignItems: "center", display: "flex", justifyContent: "space-between", marginBottom: "16px" },
  progressText: { color: "#687585", fontSize: "10px", fontWeight: 750 },
  progressTrack: { backgroundColor: "#dfe4e8", borderRadius: "999px", height: "5px", marginBottom: "18px", overflow: "hidden" },
  progressFill: { backgroundColor: "#38ae81", borderRadius: "999px", height: "100%", transition: "width 220ms ease" },
  runnerCard: { backgroundColor: "#ffffff", borderRadius: "15px", boxShadow: "0 12px 35px rgba(34, 44, 56, 0.08)", padding: "28px" },
  runnerField: { marginBottom: "22px" },
  viewedBadge: { color: "#2f8564", fontSize: "9px", fontWeight: 750, marginTop: "7px" },
  runnerNav: { alignItems: "center", display: "flex", justifyContent: "space-between", marginTop: "18px" },
  ghost: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#53b98f",
    borderRadius: "10px",
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: "0 12px 28px rgba(29, 44, 38, 0.18)",
    color: "#27342f",
    display: "flex",
    fontSize: "11px",
    fontWeight: 750,
    gap: "8px",
    padding: "11px 13px",
    pointerEvents: "none",
    zIndex: 20,
  },
});
