import * as stylex from "@stylexjs/stylex";

export const className = (...values: ReadonlyArray<stylex.StyleXStyles>) =>
  stylex.props(...values).className ?? "";

export const formStyles = stylex.create({
  workspace: {
    backgroundColor: "var(--foldworks-ui-canvas)",
    display: "grid",
    gridTemplateColumns: {
      default: "260px minmax(420px, 1fr) 280px",
      "@media (max-width: 1120px)": "230px minmax(380px, 1fr)",
    },
    minHeight: 0,
    overflow: "hidden",
  },
  outline: {
    backgroundColor: "var(--foldworks-ui-surface)",
    borderRightColor: "var(--foldworks-ui-border)",
    borderRightStyle: "solid",
    borderRightWidth: "1px",
    minHeight: 0,
    overflowY: "auto",
    padding: "18px 14px 24px",
  },
  panelHeader: {
    alignItems: "center",
    display: "flex",
    justifyContent: "space-between",
    marginBottom: "12px",
    paddingLeft: "4px",
    paddingRight: "4px",
  },
  panelTitle: {
    color: "var(--foldworks-ui-foreground-muted)",
    fontSize: "9px",
    fontWeight: 800,
    letterSpacing: "0.12em",
    margin: 0,
    textTransform: "uppercase",
  },
  paletteButton: {
    alignItems: "center",
    backgroundColor: {
      default: "var(--foldworks-ui-background)",
      ":hover": "var(--foldworks-ui-surface-subtle)",
    },
    borderColor: "var(--foldworks-ui-border)",
    borderRadius: "8px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--foldworks-ui-foreground)",
    cursor: "grab",
    display: "flex",
    fontFamily: "inherit",
    fontSize: "12px",
    fontWeight: 700,
    gap: "8px",
    minHeight: "36px",
    outline: { default: "none", ":focus-visible": "2px solid var(--foldworks-ui-focus)" },
    paddingLeft: "10px",
    textAlign: "left",
    width: "100%",
  },
  paletteRow: {
    alignItems: "stretch",
    display: "grid",
    gap: "5px",
    gridTemplateColumns: "minmax(0, 1fr) 34px",
    marginTop: "7px",
  },
  paletteAdd: {
    backgroundColor: {
      default: "var(--foldworks-ui-surface-subtle)",
      ":hover": "var(--foldworks-ui-surface-hover)",
    },
    borderColor: "var(--foldworks-ui-border)",
    borderRadius: "8px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--foldworks-ui-foreground)",
    cursor: "pointer",
    fontSize: "16px",
    outline: { default: "none", ":focus-visible": "2px solid var(--foldworks-ui-focus)" },
  },
  addIconButton: {
    alignItems: "center",
    backgroundColor: {
      default: "var(--foldworks-ui-surface)",
      ":hover": "var(--foldworks-ui-surface-hover)",
    },
    borderColor: "var(--foldworks-ui-border)",
    borderRadius: "8px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--foldworks-ui-foreground-muted)",
    cursor: "pointer",
    display: "flex",
    fontSize: "16px",
    height: "28px",
    justifyContent: "center",
    outline: { default: "none", ":focus-visible": "2px solid var(--foldworks-ui-focus)" },
    boxShadow: "var(--foldworks-ui-shadow-sm)",
    width: "28px",
  },
  sectionCard: {
    backgroundColor: "var(--foldworks-ui-surface)",
    borderColor: "var(--foldworks-ui-border)",
    borderRadius: "8px",
    borderStyle: "solid",
    borderWidth: "1px",
    marginBottom: "8px",
    overflow: "hidden",
    boxShadow: "var(--foldworks-ui-shadow-sm)",
  },
  sectionHeader: {
    alignItems: "center",
    display: "grid",
    gap: "8px",
    gridTemplateColumns: "14px minmax(0, 1fr)",
    padding: "11px 10px",
  },
  dragHandle: {
    color: "var(--foldworks-ui-foreground-subtle)",
    cursor: "grab",
    fontSize: "12px",
    userSelect: "none",
  },
  outlineButton: {
    backgroundColor: "transparent",
    borderWidth: 0,
    color: "var(--foldworks-ui-foreground)",
    cursor: "pointer",
    minWidth: 0,
    outline: { default: "none", ":focus-visible": "2px solid var(--foldworks-ui-focus)" },
    padding: 0,
    textAlign: "left",
  },
  outlineTitle: {
    display: "block",
    fontSize: "12px",
    fontWeight: 750,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  actorBadge: {
    backgroundColor: "var(--foldworks-ui-success-surface)",
    borderRadius: "999px",
    color: "var(--foldworks-ui-success)",
    display: "inline-block",
    fontSize: "9px",
    fontWeight: 750,
    marginTop: "4px",
    padding: "3px 6px",
  },
  pageList: {
    backgroundColor: "var(--foldworks-ui-surface-subtle)",
    borderTopColor: "var(--foldworks-ui-border)",
    borderTopStyle: "solid",
    borderTopWidth: "1px",
    padding: "6px",
  },
  pageRow: {
    alignItems: "center",
    backgroundColor: { default: "transparent", ":hover": "var(--foldworks-ui-surface-hover)" },
    borderColor: "transparent",
    borderRadius: "6px",
    borderStyle: "solid",
    borderWidth: "1px",
    display: "grid",
    gap: "7px",
    gridTemplateColumns: "12px minmax(0, 1fr)",
    minHeight: "34px",
    padding: "3px 7px",
    position: "relative",
  },
  pageRowActive: {
    backgroundColor: "var(--foldworks-ui-selection)",
    borderColor: "var(--foldworks-ui-selection-border)",
    color: "var(--foldworks-ui-selection-foreground)",
  },
  addPageButton: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    color: "var(--foldworks-ui-foreground-muted)",
    cursor: "pointer",
    display: "flex",
    fontSize: "12px",
    fontWeight: 600,
    gap: "5px",
    padding: "8px 8px 6px 26px",
    textAlign: "left",
    width: "100%",
  },
  dropLine: {
    backgroundColor: "transparent",
    borderColor: "transparent",
    borderRadius: "999px",
    borderStyle: "solid",
    borderWidth: "0px",
    boxSizing: "border-box",
    height: "8px",
    transition: "background-color 120ms ease, border-color 120ms ease, box-shadow 120ms ease, height 140ms ease, margin 140ms ease",
  },
  dropLineAvailable: {
    backgroundColor: "var(--foldworks-ui-drop-target)",
    borderColor: "var(--foldworks-ui-drop-target-border)",
    borderStyle: "dashed",
    borderWidth: "1px",
    height: "18px",
    marginBottom: "2px",
    marginTop: "2px",
  },
  dropLineActive: {
    backgroundColor: "var(--foldworks-ui-drop-target-active)",
    borderColor: "var(--foldworks-ui-drop-target-active-border)",
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: "0 0 0 2px color-mix(in oklch, var(--foldworks-ui-drop-target-active-border) 22%, transparent)",
    height: "18px",
    marginBottom: "2px",
    marginTop: "2px",
  },
  pageReceiver: {
    borderColor: "transparent",
    borderRadius: "6px",
    borderStyle: "solid",
    borderWidth: "1px",
    inset: "2px",
    position: "absolute",
    zIndex: 1,
  },
  pageReceiverAvailable: {
    borderColor: "var(--foldworks-ui-drop-target-border)",
    borderStyle: "dashed",
  },
  pageReceiverActive: {
    backgroundColor: "color-mix(in oklch, var(--foldworks-ui-drop-target-active) 34%, transparent)",
    borderColor: "var(--foldworks-ui-drop-target-active-border)",
  },
  canvasViewport: {
    minHeight: 0,
    overflowY: "auto",
    padding: "30px 32px 80px",
  },
  canvas: {
    marginLeft: "auto",
    marginRight: "auto",
    maxWidth: "700px",
  },
  canvasEyebrow: {
    color: "var(--foldworks-ui-selection-foreground)",
    fontSize: "10px",
    fontWeight: 800,
    letterSpacing: "0.1em",
    marginBottom: "8px",
    marginTop: 0,
    textTransform: "uppercase",
  },
  canvasTitle: {
    color: "var(--foldworks-ui-foreground)",
    fontSize: "26px",
    fontWeight: 760,
    letterSpacing: "-0.03em",
    margin: 0,
  },
  canvasDescription: {
    color: "var(--foldworks-ui-foreground-muted)",
    fontSize: "13px",
    lineHeight: 1.5,
    marginBottom: "20px",
    marginTop: "6px",
  },
  fieldCard: {
    backgroundColor: "var(--foldworks-ui-surface)",
    borderColor: {
      default: "var(--foldworks-ui-border)",
      ":hover": "var(--foldworks-ui-selection-border)",
    },
    borderRadius: "9px",
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: "var(--foldworks-ui-shadow-sm)",
    cursor: "pointer",
    marginBottom: "10px",
    outline: { default: "none", ":focus-visible": "3px solid var(--foldworks-ui-focus)" },
    padding: "16px",
    position: "relative",
    transition: "border-color 150ms ease, transform 180ms ease, box-shadow 150ms ease",
  },
  fieldCardSelected: {
    borderColor: "var(--foldworks-ui-selection-border)",
    boxShadow: "0 0 0 2px color-mix(in oklch, var(--foldworks-ui-selection-border) 22%, transparent)",
  },
  draggingSource: {
    backgroundColor: "transparent",
    borderStyle: "dashed",
    boxShadow: "none",
  },
  draggingContent: { opacity: 0.28 },
  fieldChrome: {
    alignItems: "center",
    display: "flex",
    justifyContent: "space-between",
    marginBottom: "10px",
  },
  fieldType: {
    color: "var(--foldworks-ui-foreground-muted)",
    fontSize: "9px",
    fontWeight: 800,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  fieldHandle: { color: "var(--foldworks-ui-foreground-subtle)", cursor: "grab", fontSize: "12px" },
  fieldLabel: {
    color: "var(--foldworks-ui-foreground)",
    display: "block",
    fontSize: "13px",
    fontWeight: 700,
    marginBottom: "7px",
  },
  required: { color: "var(--foldworks-ui-danger)", marginLeft: "3px" },
  fieldDescription: {
    color: "var(--foldworks-ui-foreground-muted)",
    fontSize: "10px",
    lineHeight: 1.45,
    marginBottom: "8px",
    marginTop: "-3px",
  },
  previewInput: {
    backgroundColor: "var(--foldworks-ui-surface)",
    borderColor: "var(--foldworks-ui-input)",
    borderRadius: "7px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--foldworks-ui-foreground)",
    fontFamily: "inherit",
    fontSize: "12px",
    minHeight: "40px",
    outline: { default: "none", ":focus-visible": "2px solid var(--foldworks-ui-focus)" },
    paddingLeft: "11px",
    paddingRight: "11px",
    width: "100%",
  },
  previewTextarea: { minHeight: "82px", paddingBottom: "9px", paddingTop: "9px", resize: "vertical" },
  checkboxRow: {
    alignItems: "center",
    color: "var(--foldworks-ui-foreground)",
    display: "flex",
    fontSize: "12px",
    gap: "8px",
  },
  contentBlock: {
    backgroundColor: "var(--foldworks-ui-surface-subtle)",
    borderColor: "var(--foldworks-ui-border)",
    borderRadius: "9px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--foldworks-ui-foreground-muted)",
    fontSize: "11px",
    lineHeight: 1.55,
    overflowX: "auto",
    padding: "14px",
  },
  contentHeading: { color: "var(--foldworks-ui-foreground)", fontSize: "14px", lineHeight: 1.3, marginBottom: "7px", marginTop: "12px" },
  contentParagraph: { marginBottom: "7px", marginTop: "6px" },
  markdownInlineCode: {
    backgroundColor: "var(--foldworks-ui-surface-hover)",
    borderRadius: "4px",
    color: "var(--foldworks-ui-foreground)",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    paddingLeft: "4px",
    paddingRight: "4px",
  },
  markdownCodeBlock: {
    backgroundColor: "var(--foldworks-ui-primary)",
    borderRadius: "7px",
    color: "var(--foldworks-ui-primary-foreground)",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    overflowX: "auto",
    padding: "10px",
    whiteSpace: "pre-wrap",
  },
  markdownError: {
    color: "var(--foldworks-ui-danger)",
    fontWeight: 700,
    marginBottom: "8px",
    marginTop: 0,
  },
  markdownSource: {
    margin: 0,
    overflowX: "auto",
    whiteSpace: "pre-wrap",
  },
  emptyPage: {
    borderColor: "var(--foldworks-ui-border-strong)",
    borderRadius: "9px",
    borderStyle: "dashed",
    borderWidth: "1px",
    color: "var(--foldworks-ui-foreground-muted)",
    fontSize: "12px",
    padding: "38px 20px",
    textAlign: "center",
  },
  settings: {
    backgroundColor: "var(--foldworks-ui-surface)",
    borderLeftColor: "var(--foldworks-ui-border)",
    borderLeftStyle: "solid",
    borderLeftWidth: "1px",
    minHeight: 0,
    overflowY: "auto",
    padding: "18px",
  },
  settingsHidden: {
    display: {
      default: "block",
      "@media (max-width: 1120px)": "none",
    },
  },
  settingsEmpty: { color: "var(--foldworks-ui-foreground-muted)", fontSize: "11px", lineHeight: 1.6, marginTop: "36px" },
  field: { display: "flex", flexDirection: "column", gap: "6px", marginBottom: "14px" },
  modeBar: {
    alignItems: "center",
    display: "flex",
    gap: "10px",
  },
  runnerViewport: { backgroundColor: "var(--foldworks-ui-canvas)", minHeight: 0, overflowY: "auto", padding: "30px" },
  runner: { marginLeft: "auto", marginRight: "auto", maxWidth: "760px" },
  runnerTop: { alignItems: "center", display: "flex", justifyContent: "space-between", marginBottom: "16px" },
  progressText: { color: "var(--foldworks-ui-foreground-muted)", fontSize: "10px", fontWeight: 750 },
  progressTrack: { backgroundColor: "var(--foldworks-ui-surface-hover)", borderRadius: "999px", height: "5px", marginBottom: "18px", overflow: "hidden" },
  progressFill: { backgroundColor: "var(--foldworks-ui-success)", borderRadius: "999px", height: "100%", transition: "width 220ms ease" },
  runnerCard: { backgroundColor: "var(--foldworks-ui-surface)", borderColor: "var(--foldworks-ui-border)", borderRadius: "var(--foldworks-ui-radius-lg)", borderStyle: "solid", borderWidth: "1px", boxShadow: "var(--foldworks-ui-shadow-sm)", padding: "30px" },
  runnerField: { marginBottom: "22px" },
  viewedBadge: {
    alignItems: "center",
    color: "var(--foldworks-ui-success)",
    display: "flex",
    fontSize: "9px",
    fontWeight: 750,
    gap: "5px",
    marginTop: "7px",
  },
  runnerNav: { alignItems: "center", display: "flex", justifyContent: "space-between", marginTop: "18px" },
  ghost: {
    alignItems: "center",
    backgroundColor: "var(--foldworks-ui-surface)",
    borderColor: "var(--foldworks-ui-drop-target-active-border)",
    borderRadius: "8px",
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: "var(--foldworks-ui-shadow-panel)",
    color: "var(--foldworks-ui-foreground)",
    display: "flex",
    fontSize: "11px",
    fontWeight: 750,
    gap: "8px",
    padding: "11px 13px",
    pointerEvents: "none",
    zIndex: 20,
  },
});
