import * as stylex from "@stylexjs/stylex";

export const financeStyles = stylex.create({
  board: {
    alignItems: "start",
    display: "grid",
    gap: "18px",
    gridTemplateColumns: {
      default: "repeat(4, minmax(0, 1fr))",
      "@media (max-width: 1180px)": "repeat(2, minmax(0, 1fr))",
      "@media (max-width: 680px)": "minmax(0, 1fr)",
    },
  },
  card: {
    borderRadius: "var(--radius-xl)",
    boxShadow: "var(--shadow-card)",
    minWidth: 0,
  },
  spanTwo: {
    gridColumn: {
      default: "span 2",
      "@media (max-width: 680px)": "span 1",
    },
  },
  tallCard: { minHeight: "348px" },
  cardStack: { display: "grid", gap: "18px" },
  compactStack: { display: "grid", gap: "12px" },
  chartWrap: { display: "grid", gap: "8px", paddingTop: "6px" },
  chart: { height: "150px" },
  chartLabels: {
    color: "var(--muted-foreground)",
    display: "grid",
    fontSize: "11px",
    gridTemplateColumns: "repeat(6, 1fr)",
    textAlign: "center",
  },
  statGrid: { display: "grid", gap: "10px", gridTemplateColumns: "repeat(2, minmax(0, 1fr))" },
  inset: {
    backgroundColor: "var(--muted)",
    borderRadius: "var(--radius-xl)",
    display: "grid",
    gap: "4px",
    padding: "14px",
  },
  insetLabel: {
    color: "var(--muted-foreground)",
    fontSize: "10px",
    fontWeight: 600,
    letterSpacing: "0.055em",
    textTransform: "uppercase",
  },
  insetValue: { color: "var(--foreground)", fontSize: "15px", fontWeight: 650 },
  muted: { color: "var(--muted-foreground)", fontSize: "12px", lineHeight: 1.5 },
  center: { textAlign: "center" },
  formStack: { display: "grid", gap: "15px" },
  label: { color: "var(--foreground)", fontSize: "12px", fontWeight: 550 },
  formGroup: { display: "grid", gap: "7px" },
  amountRow: { alignItems: "baseline", display: "flex", gap: "12px", justifyContent: "space-between" },
  amount: { color: "var(--foreground)", fontSize: "22px", fontWeight: 700, letterSpacing: "-0.025em" },
  rangeLabels: {
    color: "var(--muted-foreground)",
    display: "flex",
    fontSize: "11px",
    justifyContent: "space-between",
  },
  pillButton: { borderRadius: "999px" },
  target: {
    backgroundColor: "var(--muted)",
    borderRadius: "var(--radius-xl)",
    display: "grid",
    gap: "10px",
    padding: "14px",
  },
  targetAmount: { color: "var(--foreground)", fontSize: "28px", fontWeight: 700, letterSpacing: "-0.035em", lineHeight: 1 },
  split: { alignItems: "center", display: "flex", gap: "12px", justifyContent: "space-between" },
  value: { color: "var(--foreground)", fontSize: "12px", fontWeight: 600 },
  metric: { color: "var(--foreground)", fontSize: "42px", fontWeight: 500, letterSpacing: "-0.05em", lineHeight: 1 },
  summary: { backgroundColor: "var(--muted)", borderRadius: "var(--radius-xl)", display: "grid", gap: "10px", padding: "14px" },
  summaryRule: { backgroundColor: "var(--border)", height: "1px", width: "100%" },
  empty: { backgroundColor: "transparent", border: 0, paddingBottom: "20px", paddingTop: "20px" },
  emptyMedia: {
    alignItems: "center",
    backgroundColor: "var(--muted)",
    borderRadius: "var(--radius-lg)",
    color: "var(--foreground)",
    display: "flex",
    height: "36px",
    justifyContent: "center",
    width: "36px",
  },
  transactionList: { display: "grid" },
  transaction: {
    alignItems: "center",
    borderBottomColor: "var(--border)",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    display: "grid",
    gap: "12px",
    gridTemplateColumns: "36px minmax(140px, 1fr) minmax(90px, .75fr) auto 28px",
    paddingBottom: "10px",
    paddingTop: "10px",
  },
  transactionLast: { borderBottomWidth: 0 },
  transactionIcon: {
    alignItems: "center",
    backgroundColor: "var(--muted)",
    borderRadius: "var(--radius-lg)",
    color: "var(--foreground)",
    display: "flex",
    height: "34px",
    justifyContent: "center",
    width: "34px",
  },
  transactionName: { color: "var(--foreground)", fontSize: "12px", fontWeight: 600 },
  transactionMeta: { color: "var(--muted-foreground)", fontSize: "11px" },
  transactionAmount: { color: "var(--foreground)", fontSize: "12px", fontWeight: 650, textAlign: "right" },
  transactionPositive: { color: "var(--foldworks-ui-success)" },
  qrFrame: {
    backgroundColor: "white",
    borderColor: "var(--border)",
    borderRadius: "var(--radius-xl)",
    borderStyle: "solid",
    borderWidth: "1px",
    marginLeft: "auto",
    marginRight: "auto",
    padding: "15px",
    width: "166px",
  },
  qr: { display: "grid", gridTemplateColumns: "repeat(15, 1fr)", width: "100%" },
  qrCell: { aspectRatio: "1 / 1", backgroundColor: "transparent" },
  qrCellOn: { backgroundColor: "#080808" },
  navPair: { display: "grid", gap: "12px", gridTemplateColumns: "repeat(2, minmax(0, 1fr))" },
  miniCards: {
    alignItems: "stretch",
    display: "grid",
    gap: "18px",
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      "@media (max-width: 420px)": "minmax(0, 1fr)",
    },
  },
  miniMetric: { color: "var(--foreground)", fontSize: "25px", fontWeight: 650, letterSpacing: "-0.035em", lineHeight: 1 },
  miniChart: { height: "74px" },
  miniChartLabels: {
    color: "var(--muted-foreground)",
    display: "grid",
    fontSize: "10px",
    gridTemplateColumns: "repeat(7, 1fr)",
    textAlign: "center",
  },
  miniSidebar: { minHeight: "190px" },
  breadcrumbPanel: { backgroundColor: "var(--muted)", borderRadius: "var(--radius-xl)", display: "grid", gap: "16px", padding: "14px" },
  dangerZone: {
    alignItems: "start",
    backgroundColor: "var(--muted)",
    borderRadius: "var(--radius-xl)",
    display: "flex",
    gap: "10px",
    padding: "14px",
  },
  dangerIcon: { color: "var(--destructive)", flexShrink: 0 },
  sectionIntro: {
    alignItems: "end",
    display: "flex",
    gap: "24px",
    justifyContent: "space-between",
    paddingTop: "22px",
  },
  sectionCopy: { display: "grid", gap: "4px" },
  eyebrow: { color: "var(--primary)", fontSize: "11px", fontWeight: 650, letterSpacing: "0.08em", textTransform: "uppercase" },
  sectionTitle: { color: "var(--foreground)", fontSize: "24px", fontWeight: 700, letterSpacing: "-0.025em", margin: 0 },
  sectionDescription: { color: "var(--muted-foreground)", fontSize: "13px", margin: 0 },
});
