import * as stylex from "@stylexjs/stylex";

export const className = (...values: ReadonlyArray<stylex.StyleXStyles>) =>
  stylex.props(...values).className ?? "";

export const uiKitStyles = stylex.create({
  viewport: {
    backgroundColor: "var(--foldworks-ui-canvas)",
    minHeight: 0,
    overflowY: "auto",
    padding: {
      default: "32px",
      "@media (max-width: 820px)": "16px",
    },
  },
  content: {
    display: "flex",
    flexDirection: "column",
    gap: "18px",
    marginLeft: "auto",
    marginRight: "auto",
    maxWidth: "1180px",
  },
  hero: {
    alignItems: "center",
    backgroundColor: "var(--foldworks-ui-surface)",
    backgroundImage: "radial-gradient(circle at 92% 10%, var(--foldworks-ui-brand-surface), transparent 42%)",
    borderColor: "var(--foldworks-ui-border)",
    borderRadius: "12px",
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: "var(--foldworks-ui-shadow-panel)",
    display: "grid",
    gap: "28px",
    gridTemplateColumns: {
      default: "minmax(0, 1fr) 290px",
      "@media (max-width: 760px)": "1fr",
    },
    overflow: "hidden",
    padding: {
      default: "30px 32px",
      "@media (max-width: 760px)": "24px",
    },
    position: "relative",
  },
  heroCopy: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    maxWidth: "690px",
  },
  eyebrow: {
    color: "var(--foldworks-ui-brand-foreground)",
    fontSize: "10px",
    fontWeight: 750,
    letterSpacing: "0.12em",
    margin: 0,
    textTransform: "uppercase",
  },
  heroTitle: {
    color: "var(--foldworks-ui-foreground)",
    fontSize: {
      default: "27px",
      "@media (max-width: 760px)": "23px",
    },
    fontWeight: 730,
    letterSpacing: "-0.035em",
    lineHeight: 1.12,
    margin: 0,
  },
  heroDescription: {
    color: "var(--foldworks-ui-foreground-muted)",
    fontSize: "13px",
    lineHeight: 1.55,
    margin: 0,
  },
  activity: {
    alignItems: "flex-start",
    backdropFilter: "blur(12px)",
    backgroundColor: "color-mix(in oklch, var(--foldworks-ui-surface) 88%, transparent)",
    borderColor: "var(--foldworks-ui-brand-border)",
    borderRadius: "10px",
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: "var(--foldworks-ui-shadow-control)",
    display: "flex",
    gap: "10px",
    padding: "14px",
  },
  activityIcon: {
    alignItems: "center",
    backgroundColor: "var(--foldworks-ui-brand)",
    borderRadius: "999px",
    color: "var(--foldworks-ui-primary-foreground)",
    display: "flex",
    flexShrink: 0,
    height: "26px",
    justifyContent: "center",
    width: "26px",
  },
  activityLabel: {
    color: "var(--foldworks-ui-foreground-subtle)",
    fontSize: "9px",
    fontWeight: 750,
    letterSpacing: "0.1em",
    margin: "1px 0 4px",
    textTransform: "uppercase",
  },
  activityMessage: {
    color: "var(--foldworks-ui-foreground)",
    fontSize: "12px",
    fontWeight: 600,
    lineHeight: 1.4,
    margin: 0,
  },
  sectionGrid: {
    alignItems: "start",
    display: "grid",
    gap: "16px",
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      "@media (max-width: 960px)": "1fr",
    },
  },
  wide: { gridColumn: "1 / -1" },
  group: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  groupLabel: {
    color: "var(--foldworks-ui-foreground-subtle)",
    fontSize: "10px",
    fontWeight: 750,
    letterSpacing: "0.1em",
    margin: 0,
    textTransform: "uppercase",
  },
  divider: {
    backgroundColor: "var(--foldworks-ui-border)",
    border: 0,
    height: "1px",
    marginBottom: "4px",
    marginTop: "4px",
    width: "100%",
  },
  fieldGrid: {
    display: "grid",
    gap: "18px",
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      "@media (max-width: 620px)": "1fr",
    },
  },
  fullWidth: { gridColumn: "1 / -1" },
  compactControl: { maxWidth: "210px" },
  iconSample: {
    alignItems: "center",
    backgroundColor: "var(--foldworks-ui-surface-subtle)",
    borderColor: "var(--foldworks-ui-border)",
    borderRadius: "var(--foldworks-ui-radius-md)",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--foldworks-ui-foreground-muted)",
    display: "flex",
    fontSize: "11px",
    gap: "8px",
    minWidth: "104px",
    padding: "11px 12px",
  },
  toolbarPreview: {
    borderColor: "var(--foldworks-ui-border)",
    borderRadius: "var(--foldworks-ui-radius-lg)",
    borderStyle: "solid",
    borderWidth: "1px",
    overflow: "hidden",
  },
  controlState: {
    alignItems: "center",
    backgroundColor: "var(--foldworks-ui-brand-surface)",
    borderColor: "var(--foldworks-ui-brand-border)",
    borderRadius: "var(--foldworks-ui-radius-md)",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--foldworks-ui-foreground-muted)",
    display: "flex",
    fontSize: "11px",
    justifyContent: "space-between",
    padding: "9px 10px",
  },
  layoutTile: {
    backgroundColor: "var(--foldworks-ui-surface-subtle)",
    borderColor: "var(--foldworks-ui-border)",
    borderRadius: "var(--foldworks-ui-radius-md)",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--foldworks-ui-foreground-muted)",
    flex: "1 1 120px",
    fontSize: "11px",
    padding: "13px",
    textAlign: "center",
  },
  tokenGrid: {
    display: "grid",
    gap: "8px",
    gridTemplateColumns: "repeat(auto-fit, minmax(110px, 1fr))",
  },
  token: {
    backgroundColor: "var(--foldworks-ui-surface)",
    borderColor: "var(--foldworks-ui-border)",
    borderRadius: "var(--foldworks-ui-radius-md)",
    borderStyle: "solid",
    borderWidth: "1px",
    overflow: "hidden",
  },
  swatch: { height: "48px" },
  tokenLabel: {
    color: "var(--foldworks-ui-foreground-muted)",
    display: "block",
    fontSize: "10px",
    padding: "8px",
  },
  swatchPrimary: { backgroundColor: "var(--foldworks-ui-primary)" },
  swatchBackground: { backgroundColor: "var(--background)" },
  swatchCard: { backgroundColor: "var(--card)" },
  swatchMuted: { backgroundColor: "var(--muted)" },
  swatchBorder: { backgroundColor: "var(--border)" },
  swatchRing: { backgroundColor: "var(--ring)" },
  swatchSuccess: { backgroundColor: "var(--foldworks-ui-success-surface)" },
  swatchWarning: { backgroundColor: "var(--foldworks-ui-warning-surface)" },
  swatchDanger: { backgroundColor: "var(--foldworks-ui-danger-surface)" },
  swatchInfo: { backgroundColor: "var(--foldworks-ui-info-surface)" },
  swatchSelection: { backgroundColor: "var(--foldworks-ui-selection)" },
  swatchDropTarget: { backgroundColor: "var(--foldworks-ui-drop-target-active)" },
});
