import * as stylex from "@stylexjs/stylex";

export const className = (...values: ReadonlyArray<stylex.StyleXStyles>) =>
  stylex.props(...values).className ?? "";

export const uiKitStyles = stylex.create({
  viewport: {
    backgroundColor: "var(--muted)",
    minHeight: 0,
    overflowY: "auto",
    padding: {
      default: "24px 28px 48px",
      "@media (max-width: 820px)": "16px",
    },
  },
  content: {
    display: "flex",
    flexDirection: "column",
    gap: "28px",
    marginLeft: "auto",
    marginRight: "auto",
    maxWidth: "1540px",
  },
  srOnly: {
    clip: "rect(0, 0, 0, 0)",
    clipPath: "inset(50%)",
    height: "1px",
    overflow: "hidden",
    position: "absolute",
    whiteSpace: "nowrap",
    width: "1px",
  },
  sectionGrid: {
    alignItems: "start",
    display: "grid",
    gap: "16px",
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      "@media (max-width: 960px)": "1fr",
    },
  },
  wide: { gridColumn: "1 / -1" },
  group: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  groupLabel: {
    color: "var(--foldworks-ui-foreground-muted)",
    fontSize: "11px",
    fontWeight: 550,
    letterSpacing: "0.04em",
    margin: 0,
    textTransform: "uppercase",
  },
  divider: {
    backgroundColor: "var(--foldworks-ui-border)",
    border: 0,
    height: "1px",
    marginBottom: "4px",
    marginTop: "4px",
    width: "100%",
  },
  fieldGrid: {
    display: "grid",
    gap: "20px",
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      "@media (max-width: 620px)": "1fr",
    },
  },
  fullWidth: { gridColumn: "1 / -1" },
  compactControl: { maxWidth: "210px" },
  iconSample: {
    alignItems: "center",
    backgroundColor: "var(--foldworks-ui-surface-subtle)",
    borderColor: "var(--foldworks-ui-border)",
    borderRadius: "var(--foldworks-ui-radius-md)",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--foldworks-ui-foreground-muted)",
    display: "flex",
    fontSize: "12px",
    gap: "8px",
    minWidth: "104px",
    padding: "11px 12px",
  },
  toolbarPreview: {
    borderColor: "var(--foldworks-ui-border)",
    borderRadius: "var(--foldworks-ui-radius-lg)",
    borderStyle: "solid",
    borderWidth: "1px",
    overflow: "hidden",
  },
  controlState: {
    alignItems: "center",
    backgroundColor: "var(--foldworks-ui-surface-subtle)",
    borderColor: "var(--foldworks-ui-border)",
    borderRadius: "var(--foldworks-ui-radius-md)",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--foldworks-ui-foreground-muted)",
    display: "flex",
    fontSize: "11px",
    justifyContent: "space-between",
    padding: "9px 10px",
  },
  layoutTile: {
    backgroundColor: "var(--foldworks-ui-surface-subtle)",
    borderColor: "var(--foldworks-ui-border)",
    borderRadius: "var(--foldworks-ui-radius-md)",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--foldworks-ui-foreground-muted)",
    flex: "1 1 120px",
    fontSize: "11px",
    padding: "13px",
    textAlign: "center",
  },
  tokenGrid: {
    display: "grid",
    gap: "8px",
    gridTemplateColumns: "repeat(auto-fit, minmax(110px, 1fr))",
  },
  token: {
    backgroundColor: "var(--foldworks-ui-surface)",
    borderColor: "var(--foldworks-ui-border)",
    borderRadius: "var(--foldworks-ui-radius-md)",
    borderStyle: "solid",
    borderWidth: "1px",
    overflow: "hidden",
  },
  swatch: { height: "48px" },
  tokenLabel: {
    color: "var(--foldworks-ui-foreground-muted)",
    display: "block",
    fontSize: "10px",
    padding: "8px",
  },
  swatchPrimary: { backgroundColor: "var(--foldworks-ui-primary)" },
  swatchBackground: { backgroundColor: "var(--background)" },
  swatchCard: { backgroundColor: "var(--card)" },
  swatchMuted: { backgroundColor: "var(--muted)" },
  swatchBorder: { backgroundColor: "var(--border)" },
  swatchRing: { backgroundColor: "var(--ring)" },
  swatchSuccess: { backgroundColor: "var(--foldworks-ui-success-surface)" },
  swatchWarning: { backgroundColor: "var(--foldworks-ui-warning-surface)" },
  swatchDanger: { backgroundColor: "var(--foldworks-ui-danger-surface)" },
  swatchInfo: { backgroundColor: "var(--foldworks-ui-info-surface)" },
  swatchSelection: { backgroundColor: "var(--foldworks-ui-selection)" },
  swatchDropTarget: { backgroundColor: "var(--foldworks-ui-drop-target-active)" },
  catalogGrid: {
    display: "grid",
    gap: "20px",
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      "@media (max-width: 760px)": "1fr",
    },
  },
  catalogSection: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    minWidth: 0,
  },
  catalogSectionWide: { gridColumn: "1 / -1" },
  catalogHeading: {
    color: "var(--foldworks-ui-foreground)",
    fontSize: "13px",
    fontWeight: 650,
    margin: 0,
  },
  catalogRow: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: "8px",
  },
  catalogStack: { display: "flex", flexDirection: "column", gap: "10px" },
  catalogTile: {
    backgroundColor: "var(--foldworks-ui-surface-subtle)",
    borderColor: "var(--foldworks-ui-border)",
    borderRadius: "var(--foldworks-ui-radius-md)",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--foldworks-ui-foreground-muted)",
    fontSize: "12px",
    minHeight: "72px",
    padding: "12px",
  },
  catalogMedia: {
    alignItems: "center",
    backgroundColor: "var(--foldworks-ui-surface-subtle)",
    display: "flex",
    height: "100%",
    justifyContent: "center",
  },
  catalogSidebar: { maxWidth: "260px" },
  catalogOverlayButtons: { alignItems: "center", display: "flex", flexWrap: "wrap", gap: "8px" },
  catalogScrollContent: { display: "grid", gap: "8px", padding: "8px" },
  catalogScrollItem: {
    borderBottomColor: "var(--foldworks-ui-border)",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    color: "var(--foldworks-ui-foreground-muted)",
    fontSize: "12px",
    padding: "8px",
  },
});
