import * as stylex from "@stylexjs/stylex";
import { colors, radii, space, typography } from "@foldworks/ui/tokens.stylex";

export const styles = stylex.create({
  srOnly: { position: "absolute", width: "1px", height: "1px", padding: 0, overflow: "hidden", clipPath: "inset(50%)", whiteSpace: "nowrap" },
  root: { padding: { default: "28px", "@media (max-width: 700px)": "12px" }, display: "flex", flexDirection: "column", gap: space.xl, minWidth: 0, color: colors.foreground },
  heading: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: space.md, flexWrap: "wrap" },
  eyebrow: { fontSize: typography.sizeXs, fontWeight: 650, letterSpacing: "0.1em", textTransform: "uppercase", color: colors.foregroundMuted },
  title: { fontSize: "28px", letterSpacing: "-0.035em", fontWeight: 650, margin: "6px 0" },
  subtitle: { fontSize: typography.sizeMd, color: colors.foregroundMuted, lineHeight: 1.6 },
  stats: { display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: space.md },
  stat: { borderWidth: "1px", borderStyle: "solid", borderColor: colors.border, borderRadius: radii.lg, padding: "16px 20px", backgroundColor: colors.surface },
  number: { fontSize: "24px", fontWeight: 600, fontVariantNumeric: "tabular-nums", letterSpacing: "-0.04em", marginBottom: space.xs },
  workspace: { display: "grid", gridTemplateColumns: { default: "minmax(0, 1fr) minmax(310px, 370px)", "@media (max-width: 1150px)": "minmax(0, 1fr)" }, alignItems: "start", gap: space.lg, minWidth: 0 },
  card: { backgroundColor: colors.surface, borderWidth: "1px", borderStyle: "solid", borderColor: colors.border, borderRadius: radii.lg, minWidth: 0, overflow: "hidden" },
  cardHeader: { display: "flex", alignItems: "center", justifyContent: "space-between", flexWrap: "wrap", gap: space.sm, padding: "16px 18px", borderBottomWidth: "1px", borderBottomStyle: "solid", borderBottomColor: colors.border },
  cardTitle: { fontSize: typography.sizeMd, fontWeight: 650 },
  row: { display: "flex", alignItems: "center", flexWrap: "wrap", gap: space.sm },
  stack: { display: "flex", flexDirection: "column", gap: space.lg },
  footer: { padding: "12px 18px", borderTopWidth: "1px", borderTopStyle: "solid", borderTopColor: colors.border, color: colors.foregroundMuted, fontSize: typography.sizeSm, lineHeight: 1.6 },
  inspector: { padding: "20px", display: "flex", flexDirection: "column", gap: space.xl },
  record: { display: "flex", alignItems: "center", gap: space.md },
  avatar: { display: "grid", placeItems: "center", width: "42px", height: "42px", borderRadius: radii.md, color: colors.foreground, backgroundColor: colors.surfaceSubtle, fontWeight: 650 },
  recordTitle: { fontSize: "18px", fontWeight: 650, letterSpacing: "-0.02em" },
  tabs: { display: "flex", gap: space.xs, flexWrap: "wrap", paddingBottom: space.md, borderBottomWidth: "1px", borderBottomStyle: "solid", borderBottomColor: colors.border },
  property: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: space.md, padding: "10px 0", borderBottomWidth: "1px", borderBottomStyle: "solid", borderBottomColor: colors.border, fontSize: typography.sizeMd },
  label: { fontSize: typography.sizeSm, color: colors.foregroundMuted },
  link: { appearance: "none", backgroundColor: "transparent", border: 0, cursor: "pointer", color: colors.foreground, fontSize: typography.sizeMd, fontWeight: 550, padding: "4px 0", textAlign: "left", outline: { default: "none", ":focus-visible": `2px solid ${colors.focus}` }, outlineOffset: "3px", textDecoration: { default: "none", ":hover": "underline" } },
  selected: { color: colors.foreground, fontWeight: 650, textDecoration: "underline" },
  hint: { padding: space.lg, backgroundColor: colors.surfaceSubtle, borderRadius: radii.md, fontSize: typography.sizeSm, lineHeight: 1.7, color: colors.foregroundMuted },
  empty: { padding: "44px 24px", display: "flex", flexDirection: "column", alignItems: "flex-start", gap: space.lg, minHeight: "300px" },
  rule: { fontFamily: "ui-monospace, SFMono-Regular, monospace", fontSize: typography.sizeXs, lineHeight: 1.8, whiteSpace: "pre-wrap", padding: space.md, backgroundColor: colors.surfaceSubtle, borderRadius: radii.md },
  evidence: { padding: 0, margin: 0, listStyle: "none", display: "flex", flexDirection: "column", gap: space.sm, fontSize: typography.sizeSm, color: colors.foregroundMuted },
});
