import * as stylex from "@stylexjs/stylex";

const mobile = "@media (max-width: 700px)" as const;
const reducedMotion = "@media (prefers-reduced-motion: reduce)" as const;

export const className = (...values: ReadonlyArray<stylex.StyleXStyles>) =>
  stylex.props(...values).className ?? "";

export const styles = stylex.create({
  root: {
    backgroundColor: "var(--muted)",
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr) auto",
    height: "100%",
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
    position: "relative",
  },
  sessionBar: {
    alignItems: "center",
    backgroundColor: "var(--background)",
    borderBottomColor: "var(--border)",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    display: "flex",
    gap: "12px",
    justifyContent: "space-between",
    minWidth: 0,
    padding: { default: "10px 20px", [mobile]: "10px 12px" },
  },
  sessionControls: { alignItems: "center", display: "flex", flexWrap: "wrap", gap: "8px", minWidth: 0 },
  modelMeta: { display: { default: "flex", [mobile]: "none" }, flexDirection: "column", minWidth: 0 },
  modelProvider: { color: "var(--muted-foreground)", fontSize: "10px", fontWeight: 650, letterSpacing: "0.04em", textTransform: "uppercase" },
  modelDescription: { color: "var(--muted-foreground)", fontSize: "11px", marginTop: "2px", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  transcript: {
    alignItems: "center",
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    overflowX: "hidden",
    overflowY: "auto",
    padding: { default: "30px 20px 42px", [mobile]: "22px 12px 32px" },
    scrollBehavior: { default: "smooth", [reducedMotion]: "auto" },
    scrollbarColor: "var(--border) transparent",
  },
  transcriptInner: { display: "flex", flexDirection: "column", gap: "24px", maxWidth: "780px", width: "100%" },
  empty: { alignItems: "center", display: "flex", flex: 1, flexDirection: "column", justifyContent: "center", margin: "auto", maxWidth: "650px", padding: "28px 0", textAlign: "center" },
  emptyIcon: { alignItems: "center", backgroundColor: "var(--accent)", borderRadius: "18px", color: "var(--primary)", display: "flex", height: "56px", justifyContent: "center", marginBottom: "18px", width: "56px" },
  emptyTitle: { color: "var(--foreground)", fontSize: { default: "28px", [mobile]: "23px" }, fontWeight: 650, letterSpacing: "-0.035em", margin: 0 },
  emptyCopy: { color: "var(--muted-foreground)", fontSize: "14px", lineHeight: 1.6, margin: "10px 0 20px", maxWidth: "560px" },
  suggestion: { whiteSpace: { default: "nowrap", [mobile]: "normal" } },
  turn: { display: "flex", gap: "11px", minWidth: 0, width: "100%" },
  userTurn: { flexDirection: "row-reverse" },
  avatar: { alignItems: "center", backgroundColor: "var(--accent)", borderRadius: "10px", color: "var(--accent-foreground)", display: "flex", flexShrink: 0, height: "30px", justifyContent: "center", width: "30px" },
  userAvatar: { backgroundColor: "var(--primary)", color: "var(--primary-foreground)" },
  turnBody: { display: "flex", flex: 1, flexDirection: "column", gap: "9px", minWidth: 0 },
  userBody: { alignItems: "flex-end" },
  author: { color: "var(--muted-foreground)", fontSize: "11px", fontWeight: 650 },
  userBubble: { backgroundColor: "var(--primary)", borderRadius: "14px 14px 4px 14px", color: "var(--primary-foreground)", fontSize: "13px", lineHeight: 1.55, maxWidth: "82%", padding: "9px 12px", whiteSpace: "pre-wrap" },
  assistantContent: { color: "var(--foreground)", display: "flex", flexDirection: "column", fontSize: "13px", gap: "12px", lineHeight: 1.65, minWidth: 0, width: "100%" },
  text: { margin: 0, whiteSpace: "pre-wrap" },
  interrupted: { color: "var(--muted-foreground)" },
  cursor: { animationName: stylex.keyframes({ "0%, 45%": { opacity: 1 }, "46%, 100%": { opacity: 0 } }), animationDuration: { default: "900ms", [reducedMotion]: "0ms" }, animationIterationCount: "infinite", backgroundColor: "var(--primary)", borderRadius: "1px", display: "inline-block", height: "1em", marginLeft: "2px", opacity: 1, verticalAlign: "-0.12em", width: "2px" },
  reasoning: { backgroundColor: "color-mix(in oklch, var(--secondary) 65%, transparent)", borderRadius: "9px", color: "var(--muted-foreground)", overflow: "hidden" },
  reasoningSummary: { alignItems: "center", cursor: "pointer", display: "flex", gap: "8px", listStyle: "none", minHeight: "36px", outline: { default: "none", ":focus-visible": "3px solid var(--ring)" }, padding: "7px 10px" },
  reasoningIcon: { alignItems: "center", display: "inline-flex" },
  reasoningLabel: { flex: 1, fontSize: "12px", fontWeight: 650 },
  reasoningText: { borderTopColor: "var(--border)", borderTopStyle: "solid", borderTopWidth: "1px", fontSize: "12px", lineHeight: 1.6, margin: 0, padding: "10px", whiteSpace: "pre-wrap" },
  messageActions: { alignItems: "center", display: "flex", gap: "2px", marginTop: "-4px" },
  tool: { backgroundColor: "var(--background)", borderColor: "var(--border)", borderRadius: "10px", borderStyle: "solid", borderWidth: "1px", overflow: "hidden", width: "100%" },
  toolSummary: { alignItems: "center", cursor: "pointer", display: "flex", gap: "8px", listStyle: "none", minHeight: "42px", outline: { default: "none", ":focus-visible": "3px solid var(--ring)" }, padding: "8px 11px" },
  toolIcon: { alignItems: "center", backgroundColor: "var(--secondary)", borderRadius: "7px", color: "var(--muted-foreground)", display: "flex", height: "25px", justifyContent: "center", width: "25px" },
  toolName: { color: "var(--foreground)", flex: 1, fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace", fontSize: "12px", fontWeight: 650 },
  toolDetails: { borderTopColor: "var(--border)", borderTopStyle: "solid", borderTopWidth: "1px", display: "grid", gap: "10px", padding: "11px" },
  codeLabel: { color: "var(--muted-foreground)", fontSize: "10px", fontWeight: 700, letterSpacing: "0.06em", textTransform: "uppercase" },
  code: { backgroundColor: "var(--secondary)", borderRadius: "7px", color: "var(--foreground)", fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace", fontSize: "11px", lineHeight: 1.55, margin: 0, overflowX: "auto", padding: "9px 10px", whiteSpace: "pre-wrap", wordBreak: "break-word" },
  permission: { backgroundColor: "var(--foldworks-ui-warning-surface)", borderColor: "color-mix(in oklch, var(--foldworks-ui-warning) 28%, var(--border))", borderRadius: "9px", borderStyle: "solid", borderWidth: "1px", display: "grid", gap: "10px", padding: "12px" },
  permissionHeading: { alignItems: "center", color: "var(--foreground)", display: "flex", fontSize: "13px", fontWeight: 700, gap: "8px", margin: 0 },
  permissionCopy: { color: "var(--muted-foreground)", fontSize: "12px", lineHeight: 1.5, margin: 0 },
  permissionActions: { alignItems: "center", display: "flex", flexWrap: "wrap", gap: "8px" },
  simulationNote: { color: "var(--muted-foreground)", fontSize: "11px" },
  composerShell: { backgroundColor: "linear-gradient(180deg, transparent, var(--background) 24%)", padding: { default: "18px 20px 20px", [mobile]: "14px 10px 12px" } },
  composer: { backgroundColor: "var(--background)", borderColor: "var(--border)", borderRadius: "14px", borderStyle: "solid", borderWidth: "1px", boxShadow: "0 10px 30px color-mix(in oklch, var(--foreground) 8%, transparent)", display: "grid", gap: "8px", margin: "0 auto", maxWidth: "780px", padding: "9px", width: "100%" },
  textarea: { borderWidth: 0, boxShadow: "none", minHeight: "54px", resize: "none" },
  composerFooter: { alignItems: "center", display: "flex", gap: "10px", justifyContent: "space-between" },
  composerHelp: { color: "var(--muted-foreground)", fontSize: "10px", paddingLeft: "3px" },
  jump: { bottom: "104px", left: "50%", position: "absolute", transform: "translateX(-50%)", zIndex: 3 },
  srOnly: { clip: "rect(0, 0, 0, 0)", clipPath: "inset(50%)", height: "1px", overflow: "hidden", position: "absolute", whiteSpace: "nowrap", width: "1px" },
});
