// One line of documentation for each special form and built-in, shown on
// hover and beside completions.

export type Doc = Readonly<{ usage: string; summary: string }>;

export const DOCS: ReadonlyMap<string, Doc> = new Map<string, Doc>([
  ["quote", { usage: "(quote form)", summary: "The form itself, unevaluated." }],
  ["def", { usage: "(def name value)", summary: "Names a value." }],
  ["defn", { usage: "(defn name [params] body…)", summary: "Names a function." }],
  ["fn", { usage: "(fn [params] body…)", summary: "A function without a name." }],
  ["let", { usage: "(let [name value …] body…)", summary: "Names values for its body." }],
  ["if", { usage: "(if test then else)", summary: "Chooses between two forms." }],
  ["when", { usage: "(when test body…)", summary: "Runs its body when the test holds." }],
  ["cond", { usage: "(cond test form …)", summary: "The form after the first test that holds." }],
  ["do", { usage: "(do form…)", summary: "Runs forms in order; the last is the value." }],
  ["section", { usage: "(section title form…)", summary: "Groups forms under a title." }],
  ["and", { usage: "(and form…)", summary: "True when every form is." }],
  ["or", { usage: "(or form…)", summary: "The first form that is true." }],
  ["->", { usage: "(-> value (f args)…)", summary: "Threads a value through calls." }],
  [
    "defstep",
    {
      usage: "(defstep name {:system … :reads […] :writes […]})",
      summary: "Declares a step, the system it calls, and the data it reads and writes.",
    },
  ],
  ["workflow", { usage: "(workflow name flow…)", summary: "Names a flow of steps, run in order." }],
  ["sequence", { usage: "(sequence flow…)", summary: "Runs flows one after another." }],
  ["parallel", { usage: "(parallel flow…)", summary: "Runs flows at the same time." }],
  ["branch", { usage: "(branch label flow)", summary: "A flow that runs only on one path." }],
  ["+", { usage: "(+ x …)", summary: "Adds numbers." }],
  ["-", { usage: "(- x …)", summary: "Subtracts, or negates one number." }],
  ["*", { usage: "(* x …)", summary: "Multiplies numbers." }],
  ["/", { usage: "(/ x y …)", summary: "Divides numbers." }],
  ["mod", { usage: "(mod x y)", summary: "The remainder of x divided by y." }],
  ["max", { usage: "(max x …)", summary: "The largest number." }],
  ["min", { usage: "(min x …)", summary: "The smallest number." }],
  ["<", { usage: "(< x y …)", summary: "True when numbers increase." }],
  [">", { usage: "(> x y …)", summary: "True when numbers decrease." }],
  ["<=", { usage: "(<= x y …)", summary: "True when numbers never decrease." }],
  [">=", { usage: "(>= x y …)", summary: "True when numbers never increase." }],
  ["=", { usage: "(= x y …)", summary: "True when values are equal." }],
  ["not=", { usage: "(not= x y …)", summary: "True when values differ." }],
  ["not", { usage: "(not x)", summary: "True when x is false or nil." }],
  ["inc", { usage: "(inc x)", summary: "x plus one." }],
  ["dec", { usage: "(dec x)", summary: "x minus one." }],
  ["round", { usage: "(round x digits)", summary: "Rounds x to a number of decimal places." }],
  ["str", { usage: "(str x …)", summary: "Joins values into a string." }],
  ["list", { usage: "(list x …)", summary: "A list of values." }],
  ["vector", { usage: "(vector x …)", summary: "A vector of values." }],
  ["hash-map", { usage: "(hash-map key value …)", summary: "A map of keys to values." }],
  ["count", { usage: "(count coll)", summary: "How many items a collection has." }],
  ["empty?", { usage: "(empty? coll)", summary: "True when a collection has no items." }],
  ["first", { usage: "(first coll)", summary: "The first item." }],
  ["rest", { usage: "(rest coll)", summary: "Everything after the first item." }],
  ["nth", { usage: "(nth coll index)", summary: "The item at an index." }],
  ["conj", { usage: "(conj coll x …)", summary: "Adds items to a collection." }],
  ["get", { usage: "(get map key)", summary: "The value for a key." }],
  ["assoc", { usage: "(assoc map key value …)", summary: "A map with keys set." }],
  ["keys", { usage: "(keys map)", summary: "A map's keys." }],
  ["vals", { usage: "(vals map)", summary: "A map's values." }],
  ["map", { usage: "(map f coll)", summary: "Applies f to each item." }],
  ["filter", { usage: "(filter f coll)", summary: "The items for which f is true." }],
  ["reduce", { usage: "(reduce f init coll)", summary: "Combines items with f." }],
  ["range", { usage: "(range end) (range start end)", summary: "Numbers from start up to end." }],
  ["apply", { usage: "(apply f args)", summary: "Calls f with a collection as its arguments." }],
  ["identity", { usage: "(identity x)", summary: "x itself." }],
  [
    "before?",
    {
      usage: "(before? flow first then)",
      summary: "True when a flow always finishes one step before another starts.",
    },
  ],
  ["true", { usage: "true", summary: "Boolean true." }],
  ["false", { usage: "false", summary: "Boolean false." }],
  ["nil", { usage: "nil", summary: "No value." }],
]);
