import * as stylex from "@stylexjs/stylex";

import { colors, radii, space, typography } from "@foldworks/ui/tokens.stylex";

export const styles = stylex.create({
  viewport: {
    backgroundColor: colors.canvas,
    display: "grid",
    gap: space.lg,
    gridTemplateColumns: {
      default: "minmax(0, 1fr) 300px",
      "@media (max-width: 960px)": "minmax(0, 1fr)",
    },
    gridTemplateRows: {
      default: "minmax(0, 1fr)",
      "@media (max-width: 960px)": "minmax(520px, 1fr) auto",
    },
    height: "100%",
    minHeight: 0,
    overflow: { default: "hidden", "@media (max-width: 960px)": "auto" },
    padding: { default: space.lg, "@media (max-width: 820px)": space.sm },
  },
  viewerCard: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.lg,
    borderStyle: "solid",
    borderWidth: "1px",
    display: "flex",
    minHeight: 0,
    overflow: "hidden",
  },
  panel: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.lg,
    borderStyle: "solid",
    borderWidth: "1px",
    display: "flex",
    flexDirection: "column",
    gap: space.md,
    minHeight: 0,
    overflowY: "auto",
    padding: space.lg,
  },
  heading: {
    color: colors.foreground,
    fontSize: typography.sizeLg,
    fontWeight: typography.weightSemibold,
    margin: 0,
  },
  description: {
    color: colors.foregroundMuted,
    fontSize: typography.sizeSm,
    lineHeight: typography.lineHeightNormal,
    margin: 0,
  },
  filters: {
    display: "flex",
    flexWrap: "wrap",
    gap: space.xs,
  },
  list: {
    display: "flex",
    flexDirection: "column",
    gap: space.xxs,
    listStyle: "none",
    margin: 0,
    padding: 0,
  },
  field: {
    alignItems: "center",
    backgroundColor: {
      default: "transparent",
      ":hover": colors.surfaceHover,
    },
    borderColor: "transparent",
    borderRadius: radii.md,
    borderStyle: "solid",
    borderWidth: "1px",
    color: colors.foreground,
    cursor: "pointer",
    display: "grid",
    gap: space.sm,
    gridTemplateColumns: "10px minmax(0, 1fr) auto",
    outline: { default: "none", ":focus-visible": `2px solid ${colors.focus}` },
    padding: `${space.xs} ${space.sm}`,
    textAlign: "start",
    width: "100%",
  },
  fieldSelected: {
    backgroundColor: colors.selection,
    borderColor: colors.selectionForeground,
  },
  fieldCopy: {
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
  },
  fieldLabel: {
    fontSize: typography.sizeSm,
    fontWeight: typography.weightMedium,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  fieldMeta: {
    color: colors.foregroundMuted,
    fontSize: typography.sizeXs,
  },
  swatch: {
    borderRadius: "2px",
    borderStyle: "solid",
    borderWidth: "1.5px",
    height: "10px",
    width: "10px",
  },
  filled: { backgroundColor: colors.successSurface, borderColor: colors.success },
  blank: { backgroundColor: colors.surfaceSubtle, borderColor: colors.foregroundMuted },
  omitted: {
    backgroundColor: "transparent",
    borderColor: colors.foregroundMuted,
    borderStyle: "dashed",
  },
  missing: { backgroundColor: colors.dangerSurface, borderColor: colors.danger },
  details: {
    backgroundColor: colors.surfaceSubtle,
    borderRadius: radii.md,
    color: colors.foregroundMuted,
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: typography.sizeXs,
    lineHeight: typography.lineHeightNormal,
    margin: 0,
    padding: space.sm,
    whiteSpace: "pre-wrap",
  },
});
