import * as stylex from "@stylexjs/stylex";

export const className = (...values: ReadonlyArray<stylex.StyleXStyles>) =>
  stylex.props(...values).className ?? "";

export const styles = stylex.create({
  viewport: {
    backgroundColor: "var(--muted)",
    minHeight: 0,
    overflowY: "auto",
  },
  content: {
    display: "flex",
    flexDirection: "column",
    gap: "72px",
    marginLeft: "auto",
    marginRight: "auto",
    maxWidth: "1240px",
    padding: {
      default: "64px 36px 88px",
      "@media (max-width: 760px)": "40px 18px 64px",
    },
  },
  hero: {
    alignItems: "center",
    display: "grid",
    gap: "48px",
    gridTemplateColumns: {
      default: "minmax(0, 1fr) minmax(420px, 0.85fr)",
      "@media (max-width: 980px)": "1fr",
    },
  },
  heroCopy: {
    alignItems: "flex-start",
    display: "flex",
    flexDirection: "column",
  },
  eyebrow: {
    alignItems: "center",
    color: "var(--primary)",
    display: "flex",
    fontSize: "12px",
    fontWeight: 650,
    gap: "8px",
    letterSpacing: "0.08em",
    marginBottom: "20px",
    textTransform: "uppercase",
  },
  title: {
    color: "var(--foreground)",
    fontSize: {
      default: "56px",
      "@media (max-width: 760px)": "40px",
    },
    fontWeight: 620,
    letterSpacing: "-0.055em",
    lineHeight: 1.02,
    margin: 0,
    maxWidth: "760px",
  },
  lead: {
    color: "var(--muted-foreground)",
    fontSize: {
      default: "18px",
      "@media (max-width: 760px)": "16px",
    },
    lineHeight: 1.7,
    marginBottom: 0,
    marginTop: "24px",
    maxWidth: "660px",
  },
  actions: {
    display: "flex",
    flexWrap: "wrap",
    gap: "10px",
    marginTop: "28px",
  },
  primaryLink: {
    alignItems: "center",
    backgroundColor: {
      default: "var(--primary)",
      ":hover": "color-mix(in oklch, var(--primary) 88%, black)",
    },
    borderRadius: "var(--radius)",
    color: "var(--primary-foreground)",
    display: "inline-flex",
    fontSize: "13px",
    fontWeight: 600,
    gap: "8px",
    minHeight: "40px",
    paddingLeft: "16px",
    paddingRight: "16px",
    textDecoration: "none",
  },
  secondaryLink: {
    alignItems: "center",
    backgroundColor: {
      default: "var(--background)",
      ":hover": "var(--accent)",
    },
    borderColor: "var(--border)",
    borderRadius: "var(--radius)",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--foreground)",
    display: "inline-flex",
    fontSize: "13px",
    fontWeight: 550,
    gap: "8px",
    minHeight: "40px",
    paddingLeft: "16px",
    paddingRight: "16px",
    textDecoration: "none",
  },
  heroMeta: {
    alignItems: "center",
    color: "var(--muted-foreground)",
    display: "flex",
    flexWrap: "wrap",
    fontSize: "12px",
    gap: "8px 18px",
    marginTop: "24px",
  },
  metaItem: {
    alignItems: "center",
    display: "inline-flex",
    gap: "6px",
  },
  preview: {
    backgroundColor: "var(--background)",
    borderColor: "var(--border)",
    borderRadius: "calc(var(--radius) + 6px)",
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: "0 18px 50px color-mix(in oklch, var(--foreground) 9%, transparent)",
    display: "flex",
    flexDirection: "column",
    gap: "14px",
    padding: "16px",
  },
  previewHeader: {
    alignItems: "center",
    display: "flex",
    justifyContent: "space-between",
    padding: "2px 2px 0",
  },
  previewTitle: {
    color: "var(--foreground)",
    fontSize: "13px",
    fontWeight: 650,
  },
  previewGrid: {
    display: "grid",
    gap: "12px",
    gridTemplateColumns: "minmax(0, 1.2fr) minmax(0, 0.8fr)",
  },
  previewCard: {
    minWidth: 0,
  },
  metric: {
    color: "var(--foreground)",
    fontSize: "30px",
    fontWeight: 620,
    letterSpacing: "-0.035em",
    lineHeight: 1.1,
    marginBottom: "12px",
  },
  metricMeta: {
    alignItems: "center",
    color: "var(--muted-foreground)",
    display: "flex",
    fontSize: "11px",
    justifyContent: "space-between",
    marginTop: "9px",
  },
  teamList: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  teamRow: {
    alignItems: "center",
    display: "flex",
    gap: "9px",
  },
  teamCopy: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    minWidth: 0,
  },
  teamName: {
    color: "var(--foreground)",
    fontSize: "12px",
    fontWeight: 600,
  },
  teamRole: {
    color: "var(--muted-foreground)",
    fontSize: "10px",
    marginTop: "2px",
  },
  chartCard: {
    gridColumn: "1 / -1",
  },
  section: {
    display: "flex",
    flexDirection: "column",
    gap: "24px",
  },
  sectionIntro: {
    maxWidth: "720px",
  },
  sectionLabel: {
    color: "var(--primary)",
    fontSize: "11px",
    fontWeight: 650,
    letterSpacing: "0.08em",
    marginBottom: "10px",
    textTransform: "uppercase",
  },
  sectionTitle: {
    color: "var(--foreground)",
    fontSize: {
      default: "32px",
      "@media (max-width: 760px)": "27px",
    },
    fontWeight: 620,
    letterSpacing: "-0.035em",
    lineHeight: 1.15,
    margin: 0,
  },
  sectionDescription: {
    color: "var(--muted-foreground)",
    fontSize: "15px",
    lineHeight: 1.65,
    marginBottom: 0,
    marginTop: "12px",
  },
  comparison: {
    backgroundColor: "var(--card)",
    borderColor: "var(--border)",
    borderRadius: "calc(var(--radius) + 4px)",
    borderStyle: "solid",
    borderWidth: "1px",
    display: "grid",
    gridTemplateColumns: {
      default: "1fr 1fr",
      "@media (max-width: 760px)": "1fr",
    },
    overflow: "hidden",
  },
  comparisonColumn: {
    padding: "28px",
  },
  comparisonApplication: {
    backgroundColor: "color-mix(in oklch, var(--primary) 5%, var(--card))",
    borderLeftColor: {
      default: "var(--border)",
      "@media (max-width: 760px)": "transparent",
    },
    borderLeftStyle: "solid",
    borderLeftWidth: "1px",
    borderTopColor: {
      default: "transparent",
      "@media (max-width: 760px)": "var(--border)",
    },
    borderTopStyle: "solid",
    borderTopWidth: "1px",
  },
  comparisonHeading: {
    alignItems: "center",
    color: "var(--foreground)",
    display: "flex",
    fontSize: "15px",
    fontWeight: 650,
    gap: "9px",
    margin: 0,
  },
  comparisonText: {
    color: "var(--muted-foreground)",
    fontSize: "13px",
    lineHeight: 1.6,
    marginBottom: 0,
    marginTop: "12px",
  },
  chips: {
    display: "flex",
    flexWrap: "wrap",
    gap: "7px",
    marginTop: "20px",
  },
  chip: {
    backgroundColor: "var(--secondary)",
    borderColor: "var(--border)",
    borderRadius: "999px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--secondary-foreground)",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: "11px",
    padding: "6px 9px",
  },
  packageGrid: {
    display: "grid",
    gap: "12px",
    gridTemplateColumns: {
      default: "repeat(4, minmax(0, 1fr))",
      "@media (max-width: 1060px)": "repeat(2, minmax(0, 1fr))",
      "@media (max-width: 620px)": "1fr",
    },
  },
  packageCard: {
    backgroundColor: {
      default: "var(--card)",
      ":hover": "var(--accent)",
    },
    borderColor: "var(--border)",
    borderRadius: "var(--radius)",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--foreground)",
    display: "flex",
    flexDirection: "column",
    minHeight: "180px",
    padding: "20px",
    textDecoration: "none",
    transition: "background-color 140ms ease, border-color 140ms ease, transform 140ms ease",
    transform: {
      default: "translateY(0)",
      ":hover": "translateY(-2px)",
    },
  },
  packageIcon: {
    alignItems: "center",
    backgroundColor: "var(--accent)",
    borderRadius: "var(--radius)",
    color: "var(--primary)",
    display: "inline-flex",
    height: "34px",
    justifyContent: "center",
    width: "34px",
  },
  packageCategory: {
    color: "var(--muted-foreground)",
    fontSize: "10px",
    fontWeight: 600,
    letterSpacing: "0.06em",
    marginTop: "22px",
    textTransform: "uppercase",
  },
  packageName: {
    alignItems: "center",
    display: "flex",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: "13px",
    fontWeight: 650,
    gap: "6px",
    justifyContent: "space-between",
    marginTop: "7px",
  },
  packageDescription: {
    color: "var(--muted-foreground)",
    fontSize: "12px",
    lineHeight: 1.55,
    marginBottom: 0,
    marginTop: "8px",
  },
  principles: {
    display: "grid",
    gap: "12px",
    gridTemplateColumns: {
      default: "repeat(3, minmax(0, 1fr))",
      "@media (max-width: 760px)": "1fr",
    },
  },
  principle: {
    backgroundColor: "var(--card)",
    borderColor: "var(--border)",
    borderRadius: "var(--radius)",
    borderStyle: "solid",
    borderWidth: "1px",
    padding: "22px",
  },
  principleHeading: {
    color: "var(--foreground)",
    fontSize: "14px",
    fontWeight: 650,
    marginBottom: "8px",
    marginTop: "16px",
  },
  principleText: {
    color: "var(--muted-foreground)",
    fontSize: "12px",
    lineHeight: 1.6,
    margin: 0,
  },
});
