import * as stylex from "@stylexjs/stylex";
const narrow = "@media (max-width: 760px)";
export const className = (...sx: stylex.StyleXStyles[]): string =>
  stylex.props(...sx).className ?? "";
export const styles = stylex.create({
  root: { height: "100%", minHeight: 0, display: "flex", flexDirection: "column", fontSize: 13 },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    padding: "20px 24px",
    borderBottom: "1px solid var(--border)",
    flexWrap: "wrap",
    backgroundColor: "var(--card)",
  },
  title: { fontSize: 22, fontWeight: 600, letterSpacing: "-0.7px" },
  subtitle: { fontSize: 12, color: "var(--muted-foreground)", marginTop: 4 },
  row: { display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap" },
  split: { display: "flex", gap: 10, alignItems: "center", justifyContent: "space-between" },
  body: {
    display: "grid",
    gridTemplateColumns: { default: "300px minmax(0, 1fr)", [narrow]: "minmax(0, 1fr)" },
    flexGrow: 1,
    minHeight: 0,
    overflow: { default: "hidden", [narrow]: "auto" },
  },
  rail: {
    overflowY: "auto",
    overscrollBehavior: "contain",
    padding: "8px 16px 24px",
    borderRight: { default: "1px solid var(--border)", [narrow]: "none" },
    maxHeight: { default: null, [narrow]: "460px" },
    backgroundColor: "var(--card)",
  },
  section: {
    borderBottom: "1px solid var(--border)",
    borderRadius: 0,
    backgroundColor: "transparent",
  },
  sectionTrigger: { padding: "16px 0", fontSize: 12, fontWeight: 600, color: "var(--foreground)" },
  sectionInner: { display: "flex", flexDirection: "column", gap: 14, padding: "0 0 18px" },
  chips: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8 },
  chip: {
    padding: 9,
    border: "1px solid var(--border)",
    borderRadius: 7,
    textAlign: "left",
    fontSize: 11,
    backgroundColor: "var(--background)",
    ":hover": { backgroundColor: "var(--accent)" },
    ":focus-visible": { outline: "2px solid var(--ring)", outlineOffset: 2 },
  },
  chipSelected: { borderColor: "var(--primary)", boxShadow: "0 0 0 1px var(--primary)" },
  swatches: {
    display: "flex",
    height: 14,
    gap: 2,
    marginBottom: 8,
    overflow: "hidden",
    borderRadius: 3,
  },
  swatch: { flexGrow: 1, border: "1px solid rgb(128 128 128 / 12%)" },
  control: { display: "flex", flexDirection: "column", gap: 7 },
  label: { fontSize: 11, fontWeight: 500, color: "var(--muted-foreground)" },
  colorRow: {
    display: "grid",
    gridTemplateColumns: "30px minmax(0, 1fr) auto",
    alignItems: "center",
    gap: 7,
  },
  colorInput: {
    width: 30,
    height: 30,
    padding: 2,
    borderRadius: 5,
    border: "1px solid var(--border)",
    cursor: "pointer",
    backgroundColor: "var(--background)",
  },
  colorText: {
    fontSize: 11,
    fontFamily: "var(--font-mono)",
    minWidth: 0,
    height: 30,
    padding: "4px 7px",
  },
  tokenLabel: {
    fontSize: 10,
    fontFamily: "var(--font-mono)",
    color: "var(--muted-foreground)",
    overflowWrap: "anywhere",
  },
  hint: { fontSize: 11, color: "var(--muted-foreground)", lineHeight: 1.6 },
  invalid: { color: "var(--destructive)", fontSize: 10 },
  advanced: {
    maxHeight: 360,
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: 12,
    paddingRight: 3,
  },
  contrast: {
    fontSize: 9,
    fontWeight: 600,
    padding: "2px 5px",
    borderRadius: 4,
    color: "var(--foreground)",
    backgroundColor: "var(--muted)",
    whiteSpace: "nowrap",
  },
  contrastFail: { color: "var(--destructive)", backgroundColor: "var(--destructive-surface)" },
  canvas: {
    minWidth: 0,
    overflow: "auto",
    backgroundColor: "var(--muted)",
    padding: { default: "20px 24px 28px", [narrow]: "16px 10px" },
  },
  previewToolbar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 16,
  },
  eyebrow: {
    fontSize: 10,
    letterSpacing: "1.1px",
    textTransform: "uppercase",
    fontWeight: 600,
    color: "var(--muted-foreground)",
  },
  previews: { display: "grid", gridTemplateColumns: "minmax(0, 1fr)", gap: 16 },
  previewsBoth: {
    gridTemplateColumns: { default: "repeat(2, minmax(0, 1fr))", [narrow]: "minmax(0, 1fr)" },
  },
  frame: {
    backgroundColor: "var(--background)",
    color: "var(--foreground)",
    fontFamily: "var(--font-sans)",
    border: "1px solid var(--border)",
    borderRadius: 10,
    overflow: "hidden",
    boxShadow: "0 4px 24px rgb(0 0 0 / 4%)",
    minWidth: 0,
    containerType: "inline-size",
  },
  frameBar: {
    height: 36,
    borderBottom: "1px solid var(--border)",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 14px",
    backgroundColor: "var(--card)",
    fontSize: 10,
    color: "var(--muted-foreground)",
  },
  dots: { display: "flex", gap: 4 },
  dot: { width: 6, height: 6, borderRadius: "50%", backgroundColor: "var(--input)" },
  product: {
    display: "grid",
    gridTemplateColumns: {
      default: "152px minmax(0, 1fr)",
      "@container (max-width: 760px)": "minmax(0, 1fr)",
    },
    minHeight: 680,
  },
  sidebar: {
    width: "100%",
    minWidth: 0,
    borderWidth: 0,
    borderRight: "1px solid var(--sidebar-border)",
    borderRadius: 0,
    padding: "20px 12px",
    display: { default: "flex", "@container (max-width: 760px)": "none" },
    flexDirection: "column",
    gap: 24,
    fontSize: 11,
  },
  brand: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    fontWeight: 600,
    fontSize: 13,
    marginBottom: 8,
  },
  brandIcon: {
    display: "grid",
    placeItems: "center",
    width: 25,
    height: 25,
    borderRadius: 7,
    backgroundColor: "var(--sidebar-primary)",
    color: "var(--sidebar-primary-foreground)",
  },
  sidebarFooter: { marginTop: "auto", fontSize: 10, color: "var(--sidebar-foreground)" },
  dashboard: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
    padding: { default: 24, "@container (max-width: 520px)": 16 },
    minWidth: 0,
  },
  productTitle: { fontSize: 22, letterSpacing: "-0.7px", fontWeight: 600 },
  stats: {
    display: "grid",
    gridTemplateColumns: {
      default: "repeat(3, minmax(0, 1fr))",
      "@container (max-width: 600px)": "minmax(0, 1fr)",
    },
    gap: 10,
  },
  statCard: { minWidth: 0 },
  statContent: { padding: 14 },
  statValue: { fontSize: 24, letterSpacing: "-0.8px" },
  card: { minWidth: 0, boxShadow: "var(--shadow-panel)" },
  middle: {
    display: "grid",
    gridTemplateColumns: {
      default: "minmax(0, 1.05fr) minmax(0, 1fr)",
      "@container (max-width: 760px)": "minmax(0, 1fr)",
    },
    gap: 14,
  },
  stack: { display: "flex", flexDirection: "column", gap: 14 },
  chart: { height: 100, alignItems: "end" },
  chartLabels: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: 9,
    color: "var(--muted-foreground)",
    marginTop: 6,
  },
  chartLegend: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 10,
    fontSize: 9,
    color: "var(--muted-foreground)",
  },
  legendDot: { display: "inline-block", width: 6, height: 6, borderRadius: "50%", marginRight: 4 },
  popover: {
    position: "relative",
    alignSelf: "flex-start",
    height: 32,
    width: 200,
    zIndex: 2,
    // The controlled Popover recipe uses the card aliases for its floating surface.
    // Rebind them within this primitive to demonstrate the popover contract.
    "--card": "var(--popover)",
    "--foreground": "var(--popover-foreground)",
  },
  popoverContent: { display: "flex", flexDirection: "column", gap: 6, minWidth: 175, fontSize: 11 },
  notice: { padding: 12 },
  reviewRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "10px 0",
    borderBottom: "1px solid var(--border)",
  },
  avatarRow: { display: "flex", alignItems: "center", gap: 8 },
  table: { minWidth: 0, overflowX: "auto" },
  tableCaption: {
    position: "absolute",
    width: 1,
    height: 1,
    overflow: "hidden",
    clipPath: "inset(50%)",
  },
  productHeader: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
  },
  footer: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 14,
  },
  exportPanel: { maxWidth: "min(860px, calc(100vw - 32px))", width: 860 },
  exportStack: { display: "flex", flexDirection: "column", gap: 16 },
  exportTabs: { display: "flex", gap: 6, flexWrap: "wrap" },
  srOnly: {
    position: "absolute",
    width: 1,
    height: 1,
    overflow: "hidden",
    clipPath: "inset(50%)",
    whiteSpace: "nowrap",
  },
});
