import * as stylex from "@stylexjs/stylex";

import {
  colors,
  motion,
  radii,
  shadows,
  space,
  typography,
} from "@foldworks/ui/tokens.stylex";

const reveal = stylex.keyframes({
  from: { opacity: 0, transform: "translateY(10px)" },
  to: { opacity: 1, transform: "translateY(0)" },
});

const reducedMotion = "@media (prefers-reduced-motion: reduce)" as const;

export const styles = stylex.create({
  viewport: {
    backgroundColor: colors.canvas,
    backgroundImage: "radial-gradient(circle at 72% -10%, var(--foldworks-ui-brand-surface) 0, transparent 34%)",
    minHeight: 0,
    overflowY: "auto",
    padding: {
      default: `${space.xl} ${space.xl} ${space.xxl}`,
      "@media (max-width: 820px)": space.lg,
    },
  },
  content: {
    animationDuration: { default: "420ms", [reducedMotion]: "0ms" },
    animationFillMode: "both",
    animationName: { default: reveal, [reducedMotion]: "none" },
    animationTimingFunction: motion.easeOut,
    display: "flex",
    flexDirection: "column",
    gap: space.lg,
    marginLeft: "auto",
    marginRight: "auto",
    maxWidth: "1180px",
  },
  hero: {
    alignItems: "flex-end",
    display: "flex",
    flexWrap: "wrap",
    gap: space.xl,
    justifyContent: "space-between",
  },
  heroCopy: { display: "flex", flexDirection: "column", gap: space.sm },
  eyebrow: {
    color: colors.brandForeground,
    fontSize: typography.sizeXs,
    fontWeight: typography.weightBold,
    letterSpacing: "0.1em",
    margin: 0,
    textTransform: "uppercase",
  },
  title: {
    color: colors.foreground,
    fontSize: "24px",
    fontWeight: 720,
    letterSpacing: "-0.035em",
    lineHeight: 1.15,
    margin: 0,
  },
  intro: {
    color: colors.foregroundMuted,
    fontSize: typography.sizeMd,
    lineHeight: typography.lineHeightNormal,
    margin: 0,
    maxWidth: "720px",
  },
  metrics: { alignItems: "center", display: "flex", flexWrap: "wrap", gap: space.sm },
  metric: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.full,
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: shadows.control,
    color: colors.foregroundMuted,
    display: "inline-flex",
    fontSize: typography.sizeXs,
    fontWeight: typography.weightMedium,
    gap: space.xs,
    minHeight: "28px",
    paddingLeft: space.sm,
    paddingRight: space.md,
    transitionDuration: motion.normal,
    transitionProperty: "border-color, box-shadow, transform",
    transitionTimingFunction: motion.easeOut,
  },
  metricAccent: { borderColor: colors.brandBorder, color: colors.brandForeground },
  metricDot: { backgroundColor: colors.brand, borderRadius: radii.full, height: "6px", width: "6px" },
  preview: {
    backgroundColor: colors.surface,
    borderColor: { default: colors.brandBorder, ":hover": colors.brand },
    borderRadius: radii.lg,
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: shadows.panel,
    overflow: "hidden",
    padding: `${space.md} ${space.lg} ${space.lg}`,
    position: "relative",
    transform: { default: "translateY(0)", ":hover": "translateY(-1px)" },
    transitionDuration: motion.normal,
    transitionProperty: "border-color, box-shadow, transform",
    transitionTimingFunction: motion.easeOut,
  },
  previewGlow: {
    backgroundImage: "linear-gradient(90deg, var(--foldworks-ui-brand), color-mix(in oklch, var(--foldworks-ui-brand) 45%, var(--foldworks-ui-info)))",
    height: "3px",
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  previewHeader: {
    alignItems: "center",
    display: "flex",
    gap: space.sm,
    justifyContent: "space-between",
    marginBottom: space.md,
  },
  previewLabel: {
    color: colors.foregroundSubtle,
    fontSize: typography.sizeXs,
    fontWeight: typography.weightBold,
    letterSpacing: "0.08em",
    margin: 0,
    textTransform: "uppercase",
  },
  previewHint: { color: colors.foregroundMuted, fontSize: typography.sizeXs },
  split: {
    alignItems: "start",
    display: "grid",
    gap: space.lg,
    gridTemplateColumns: {
      default: "minmax(0, 1.55fr) minmax(280px, 0.45fr)",
      "@media (max-width: 980px)": "1fr",
    },
  },
  editorPanel: {
    borderColor: colors.border,
    borderRadius: radii.lg,
    boxShadow: shadows.panel,
    overflow: "hidden",
  },
  codePanel: {
    borderColor: colors.border,
    borderRadius: radii.lg,
    boxShadow: shadows.panel,
    overflow: "hidden",
    position: { default: "sticky", "@media (max-width: 980px)": "static" },
    top: space.lg,
  },
  code: {
    color: colors.foregroundMuted,
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: typography.sizeXs,
    lineHeight: 1.55,
    margin: 0,
    maxHeight: "500px",
    overflow: "auto",
    whiteSpace: "pre-wrap",
  },
});
