import * as stylex from "@stylexjs/stylex";

import {
  colors,
  motion,
  radii,
  shadows,
  sizes,
  space,
  typography,
} from "@foldworks/ui/tokens.stylex";

const enter = stylex.keyframes({
  from: { opacity: 0, transform: "translateY(4px)" },
  to: { opacity: 1, transform: "translateY(0)" },
});

const fade = stylex.keyframes({
  from: { opacity: 0, transform: "translateY(3px)" },
  to: { opacity: 1, transform: "translateY(0)" },
});

const reducedMotion = "@media (prefers-reduced-motion: reduce)" as const;
const narrow = "@media (max-width: 760px)" as const;
const monospace = "ui-monospace, SFMono-Regular, Menlo, monospace";

export const styles = stylex.create({
  editor: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.lg,
    borderStyle: "solid",
    borderWidth: "1px",
    color: colors.foreground,
    display: "flex",
    flexDirection: "column",
    fontFamily: typography.fontFamily,
    minWidth: 0,
  },
  editorBody: { minWidth: 0, padding: space.md },
  group: {
    animationDuration: { default: motion.normal, [reducedMotion]: "0ms" },
    animationFillMode: "backwards",
    animationName: { default: enter, [reducedMotion]: "none" },
    animationTimingFunction: motion.easeOut,
    borderLeftColor: colors.borderStrong,
    borderLeftStyle: "solid",
    borderLeftWidth: "3px",
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    paddingBottom: space.xxs,
    paddingLeft: space.lg,
    paddingTop: space.xxs,
  },
  nestedGroup: {
    backgroundColor: "color-mix(in oklch, var(--secondary) 55%, transparent)",
    borderBottomRightRadius: radii.md,
    borderTopRightRadius: radii.md,
    paddingBottom: space.xs,
    paddingRight: space.sm,
    paddingTop: space.sm,
  },
  groupHeader: {
    alignItems: "center",
    display: "flex",
    gap: space.sm,
    minHeight: "28px",
    minWidth: 0,
    position: "relative",
  },
  groupDescription: {
    color: colors.foregroundMuted,
    fontSize: typography.sizeMd,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  groupRemoveButton: { marginLeft: "auto" },
  groupActions: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: space.xxs,
    marginLeft: `calc(-1 * ${space.sm})`,
  },
  addButton: {
    color: { default: colors.foregroundMuted, ":hover": colors.foreground },
    fontWeight: typography.weightMedium,
  },
  combinatorControl: {
    alignItems: "center",
    display: "inline-flex",
    flexShrink: 0,
    position: "relative",
  },
  combinatorSelect: {
    appearance: "none",
    backgroundColor: { default: colors.surfaceSubtle, ":hover": colors.surfaceHover },
    borderColor: colors.border,
    borderRadius: radii.sm,
    borderStyle: "solid",
    borderWidth: "1px",
    color: colors.foreground,
    cursor: "pointer",
    fontFamily: typography.fontFamily,
    fontSize: typography.sizeSm,
    fontWeight: typography.weightSemibold,
    height: "24px",
    letterSpacing: "0.02em",
    outline: { default: "none", ":focus-visible": `3px solid ${colors.focusGlow}` },
    paddingLeft: space.sm,
    paddingRight: "22px",
    transitionDuration: motion.fast,
    transitionProperty: "background-color, border-color",
    transitionTimingFunction: motion.easeOut,
  },
  combinatorChevron: {
    color: colors.foregroundMuted,
    display: "inline-flex",
    pointerEvents: "none",
    position: "absolute",
    right: "7px",
  },
  children: { display: "flex", flexDirection: "column", minWidth: 0 },
  dropTarget: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: "transparent",
    borderRadius: radii.md,
    borderStyle: "dashed",
    borderWidth: "1px",
    color: colors.brandForeground,
    display: "flex",
    height: space.sm,
    justifyContent: "center",
    opacity: 0,
    transitionDuration: motion.normal,
    transitionProperty: "background-color, border-color, height, opacity, box-shadow",
    transitionTimingFunction: motion.spring,
  },
  dropTargetAvailable: {
    backgroundColor: colors.brandSurface,
    borderColor: colors.brandBorder,
    height: "28px",
    opacity: 0.72,
  },
  dropTargetActive: {
    backgroundColor: colors.brandSurface,
    borderColor: colors.brand,
    boxShadow: `0 0 0 3px ${colors.focusGlow}`,
    height: "36px",
    opacity: 1,
  },
  empty: {
    color: colors.foregroundMuted,
    fontSize: typography.sizeMd,
    paddingBottom: space.xs,
  },
  rule: {
    alignItems: "center",
    animationDuration: { default: motion.normal, [reducedMotion]: "0ms" },
    animationFillMode: "backwards",
    animationName: { default: enter, [reducedMotion]: "none" },
    animationTimingFunction: motion.easeOut,
    display: "grid",
    gap: space.sm,
    gridTemplateColumns: {
      default: "minmax(0, 1.1fr) minmax(0, 0.9fr) minmax(0, 1.6fr) auto",
      [narrow]: "minmax(0, 1fr) minmax(0, 1fr) auto",
    },
    minWidth: 0,
    position: "relative",
    transitionDuration: motion.normal,
    transitionProperty: "opacity",
    transitionTimingFunction: motion.easeOut,
  },
  draggingRule: { opacity: 0.34 },
  // Rules and read-only logic carry the default marker so descendants can react
  // to row hover or the `<details>` open state without extra model state.
  dragHandle: {
    alignItems: "center",
    borderRadius: radii.sm,
    color: {
      default: colors.foregroundSubtle,
      ":hover": colors.foreground,
      ":focus-visible": colors.foreground,
    },
    cursor: "grab",
    display: "flex",
    height: sizes.controlSm,
    justifyContent: "center",
    left: "-15px",
    opacity: {
      default: 0,
      [stylex.when.ancestor(":hover")]: 1,
      [stylex.when.ancestor(":focus-within")]: 1,
      "@media (hover: none)": 1,
    },
    outline: { default: "none", ":focus-visible": `2px solid ${colors.focus}` },
    position: "absolute",
    top: 0,
    transitionDuration: motion.fast,
    transitionProperty: "color, opacity",
    transitionTimingFunction: motion.easeOut,
    width: "14px",
  },
  // Sits in the parent's gutter, left of the nested group's rail.
  groupDragHandle: { height: "28px", left: "-34px" },
  select: {
    backgroundColor: colors.surface,
    borderColor: {
      default: colors.input,
      ":hover": colors.borderStrong,
      ":focus": colors.brand,
    },
    borderRadius: radii.md,
    borderStyle: "solid",
    borderWidth: "1px",
    color: colors.foreground,
    cursor: "pointer",
    fontFamily: typography.fontFamily,
    fontSize: typography.sizeLg,
    height: sizes.controlSm,
    minWidth: 0,
    outline: { default: "none", ":focus-visible": `3px solid ${colors.focusGlow}` },
    paddingLeft: "10px",
    paddingRight: space.sm,
    transitionDuration: motion.fast,
    transitionProperty: "border-color, box-shadow",
    transitionTimingFunction: motion.easeOut,
    width: "100%",
  },
  value: {
    backgroundColor: colors.surface,
    borderColor: {
      default: colors.input,
      ":hover": colors.borderStrong,
      ":focus": colors.brand,
    },
    borderRadius: radii.md,
    borderStyle: "solid",
    borderWidth: "1px",
    color: colors.foreground,
    fontFamily: typography.fontFamily,
    fontSize: typography.sizeLg,
    height: sizes.controlSm,
    minWidth: 0,
    outline: { default: "none", ":focus-visible": `3px solid ${colors.focusGlow}` },
    paddingLeft: "10px",
    paddingRight: "10px",
    transitionDuration: motion.fast,
    transitionProperty: "border-color, box-shadow",
    transitionTimingFunction: motion.easeOut,
    width: "100%",
  },
  valueSlot: { gridColumn: { default: "auto", [narrow]: "1 / 3" } },
  invalidValue: {
    borderColor: colors.danger,
    boxShadow: `0 0 0 3px color-mix(in oklch, ${colors.danger} 16%, transparent)`,
  },
  hiddenValue: {
    color: colors.foregroundMuted,
    fontSize: typography.sizeMd,
    fontStyle: "italic",
    gridColumn: { default: "auto", [narrow]: "1 / 3" },
  },
  removeButton: { color: { default: colors.foregroundSubtle, ":hover": colors.danger } },
  ruleRemoveButton: {
    gridColumn: { default: "auto", [narrow]: "3" },
    gridRow: { default: "auto", [narrow]: "1" },
  },
  ghostPosition: {
    width: "min(460px, calc(100vw - 32px))",
  },
  ghost: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.brand,
    borderRadius: radii.md,
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: shadows.float,
    color: colors.foreground,
    display: "flex",
    gap: space.sm,
    minHeight: "40px",
    padding: `${space.xs} ${space.md}`,
    transform: "translate(-18px, -50%) rotate(-0.7deg)",
  },
  ghostCombinator: {
    backgroundColor: colors.surfaceSubtle,
    borderColor: colors.border,
    borderRadius: radii.sm,
    borderStyle: "solid",
    borderWidth: "1px",
    fontSize: typography.sizeSm,
    fontWeight: typography.weightSemibold,
    paddingLeft: space.sm,
    paddingRight: space.sm,
  },
  ghostAttribute: { fontSize: typography.sizeMd, fontWeight: typography.weightSemibold },
  ghostOperator: { color: colors.foregroundMuted, fontSize: typography.sizeMd },
  ghostValue: {
    backgroundColor: colors.surfaceSubtle,
    borderRadius: radii.sm,
    color: colors.foregroundMuted,
    fontFamily: monospace,
    fontSize: typography.sizeXs,
    marginLeft: "auto",
    maxWidth: "180px",
    overflow: "hidden",
    padding: `${space.xxs} ${space.xs}`,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  issue: {
    animationDuration: { default: motion.normal, [reducedMotion]: "0ms" },
    animationName: { default: fade, [reducedMotion]: "none" },
    color: colors.danger,
    fontSize: typography.sizeSm,
    gridColumn: "1 / -1",
    margin: 0,
  },
  footer: {
    alignItems: "center",
    borderTopColor: colors.border,
    borderTopStyle: "solid",
    borderTopWidth: "1px",
    display: "flex",
    flexWrap: "wrap",
    gap: `${space.xs} ${space.md}`,
    justifyContent: "space-between",
    padding: `${space.md} ${space.lg}`,
  },
  sentence: {
    color: colors.foreground,
    fontSize: typography.sizeMd,
    lineHeight: typography.lineHeightNormal,
    margin: 0,
    minWidth: 0,
  },
  sentenceAttribute: { fontWeight: typography.weightSemibold },
  sentenceValue: { fontWeight: typography.weightMedium },
  issueCount: {
    alignItems: "center",
    animationDuration: { default: motion.normal, [reducedMotion]: "0ms" },
    animationName: { default: fade, [reducedMotion]: "none" },
    color: colors.danger,
    display: "inline-flex",
    fontSize: typography.sizeSm,
    fontWeight: typography.weightMedium,
    gap: space.xs,
    whiteSpace: "nowrap",
  },
  invalidDot: {
    backgroundColor: colors.danger,
    borderRadius: radii.full,
    height: "6px",
    width: "6px",
  },
  readonly: {
    animationDuration: { default: motion.normal, [reducedMotion]: "0ms" },
    animationFillMode: "both",
    animationName: { default: fade, [reducedMotion]: "none" },
    color: colors.foreground,
    display: "flex",
    flexDirection: "column",
    fontFamily: typography.fontFamily,
    gap: space.sm,
    minWidth: 0,
  },
  logic: { display: "flex", flexDirection: "column", minWidth: 0 },
  logicToggle: {
    alignItems: "center",
    borderRadius: radii.sm,
    color: { default: colors.foregroundMuted, ":hover": colors.foreground },
    cursor: "pointer",
    display: "inline-flex",
    fontSize: typography.sizeSm,
    fontWeight: typography.weightMedium,
    gap: space.xs,
    listStyle: "none",
    outline: { default: "none", ":focus-visible": `2px solid ${colors.focus}` },
    outlineOffset: "2px",
    paddingBottom: space.xxs,
    paddingTop: space.xxs,
    transitionDuration: motion.fast,
    transitionProperty: "color",
    transitionTimingFunction: motion.easeOut,
    userSelect: "none",
    width: "fit-content",
    "::-webkit-details-marker": { display: "none" },
  },
  logicChevron: {
    display: "inline-flex",
    transform: { default: "rotate(0deg)", [stylex.when.ancestor("[open]")]: "rotate(180deg)" },
    transitionDuration: { default: motion.fast, [reducedMotion]: "0ms" },
    transitionProperty: "transform",
    transitionTimingFunction: motion.easeOut,
  },
  logicShowLabel: { display: { default: "inline", [stylex.when.ancestor("[open]")]: "none" } },
  logicHideLabel: { display: { default: "none", [stylex.when.ancestor("[open]")]: "inline" } },
  readonlyGroup: {
    borderLeftColor: colors.borderStrong,
    borderLeftStyle: "solid",
    borderLeftWidth: "3px",
    display: "flex",
    flexDirection: "column",
    gap: space.xs,
    marginTop: space.sm,
    minWidth: 0,
    paddingBottom: space.xs,
    paddingLeft: space.md,
    paddingTop: space.xs,
  },
  readonlyNested: { marginTop: space.xxs },
  readonlyHeader: {
    alignItems: "center",
    display: "flex",
    gap: space.sm,
    marginBottom: space.xxs,
    minWidth: 0,
  },
  readonlyCombinator: {
    alignItems: "center",
    backgroundColor: colors.surfaceSubtle,
    borderColor: colors.border,
    borderRadius: radii.sm,
    borderStyle: "solid",
    borderWidth: "1px",
    display: "inline-flex",
    flexShrink: 0,
    fontSize: typography.sizeSm,
    fontWeight: typography.weightSemibold,
    height: "22px",
    letterSpacing: "0.02em",
    paddingLeft: space.sm,
    paddingRight: space.sm,
  },
  readonlyRule: {
    alignItems: "baseline",
    display: "flex",
    flexWrap: "wrap",
    fontSize: typography.sizeSm,
    gap: `${space.xxs} 6px`,
    lineHeight: typography.lineHeightNormal,
    minWidth: 0,
  },
  readonlyAttribute: { fontWeight: typography.weightSemibold },
  readonlyOperator: { color: colors.foregroundMuted },
  readonlyValue: {
    backgroundColor: colors.surfaceSubtle,
    borderColor: colors.border,
    borderRadius: radii.sm,
    borderStyle: "solid",
    borderWidth: "1px",
    fontFamily: monospace,
    fontSize: typography.sizeXs,
    paddingLeft: "5px",
    paddingRight: "5px",
  },
});
