import * as stylex from "@stylexjs/stylex";

import {
  colors,
  motion,
  radii,
  shadows,
  sizes,
  space,
  typography,
} from "@foldworks/ui/tokens.stylex";

export const styles = stylex.create({
  editor: {
    color: colors.foreground,
    display: "flex",
    flexDirection: "column",
    fontFamily: typography.fontFamily,
    gap: space.md,
    minWidth: 0,
  },
  group: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.lg,
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: shadows.sm,
    display: "flex",
    flexDirection: "column",
    gap: space.sm,
    minWidth: 0,
    padding: space.md,
  },
  nestedGroup: {
    backgroundColor: colors.surfaceSubtle,
    borderColor: colors.borderStrong,
    boxShadow: "none",
    marginLeft: space.lg,
  },
  groupHeader: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: space.sm,
    justifyContent: "space-between",
  },
  groupLead: { alignItems: "center", display: "flex", gap: space.sm },
  groupLabel: {
    color: colors.foregroundMuted,
    fontSize: typography.sizeXs,
    fontWeight: typography.weightSemibold,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
  },
  groupActions: { alignItems: "center", display: "flex", flexWrap: "wrap", gap: space.xs },
  select: {
    backgroundColor: colors.surface,
    borderColor: { default: colors.input, ":focus": colors.foregroundMuted },
    borderRadius: radii.md,
    borderStyle: "solid",
    borderWidth: "1px",
    color: colors.foreground,
    fontFamily: typography.fontFamily,
    fontSize: typography.sizeSm,
    height: sizes.controlSm,
    minWidth: 0,
    outline: { default: "none", ":focus-visible": `2px solid ${colors.focus}` },
    outlineOffset: "1px",
    paddingLeft: space.sm,
    paddingRight: space.xl,
  },
  combinator: { fontWeight: typography.weightSemibold, width: "88px" },
  children: { display: "flex", flexDirection: "column", gap: space.sm, minWidth: 0 },
  empty: {
    alignItems: "center",
    borderColor: colors.borderStrong,
    borderRadius: radii.md,
    borderStyle: "dashed",
    borderWidth: "1px",
    color: colors.foregroundMuted,
    display: "flex",
    fontSize: typography.sizeSm,
    justifyContent: "center",
    minHeight: "54px",
    padding: space.md,
  },
  rule: {
    alignItems: "center",
    backgroundColor: colors.background,
    borderColor: colors.border,
    borderRadius: radii.md,
    borderStyle: "solid",
    borderWidth: "1px",
    display: "grid",
    gap: space.sm,
    gridTemplateColumns: "minmax(140px, 1.15fr) minmax(120px, 0.9fr) minmax(150px, 1.4fr) auto",
    minWidth: 0,
    padding: space.sm,
  },
  ruleInvalid: { borderColor: colors.dangerBorder },
  value: {
    backgroundColor: colors.surface,
    borderColor: { default: colors.input, ":focus": colors.foregroundMuted },
    borderRadius: radii.md,
    borderStyle: "solid",
    borderWidth: "1px",
    color: colors.foreground,
    fontFamily: typography.fontFamily,
    fontSize: typography.sizeSm,
    height: sizes.controlSm,
    minWidth: 0,
    outline: { default: "none", ":focus-visible": `2px solid ${colors.focus}` },
    outlineOffset: "1px",
    paddingLeft: space.sm,
    paddingRight: space.sm,
    width: "100%",
  },
  invalidValue: { borderColor: colors.danger },
  hiddenValue: { color: colors.foregroundMuted, fontSize: typography.sizeSm, fontStyle: "italic" },
  issue: { color: colors.danger, fontSize: typography.sizeXs, gridColumn: "1 / -1", margin: 0 },
  summary: {
    alignItems: "center",
    color: colors.foregroundMuted,
    display: "flex",
    fontSize: typography.sizeXs,
    gap: space.sm,
  },
  validDot: { backgroundColor: colors.success, borderRadius: radii.full, height: "6px", width: "6px" },
  invalidDot: { backgroundColor: colors.danger, borderRadius: radii.full, height: "6px", width: "6px" },
  readonly: {
    alignItems: "center",
    color: colors.foreground,
    display: "flex",
    flexWrap: "wrap",
    fontFamily: typography.fontFamily,
    fontSize: typography.sizeSm,
    gap: space.xs,
    lineHeight: typography.lineHeightNormal,
  },
  readonlyGroup: {
    alignItems: "center",
    display: "inline-flex",
    flexWrap: "wrap",
    gap: space.xs,
  },
  readonlyNested: {
    backgroundColor: colors.surfaceSubtle,
    borderColor: colors.border,
    borderRadius: radii.md,
    borderStyle: "solid",
    borderWidth: "1px",
    padding: `${space.xs} ${space.sm}`,
  },
  readonlyCombinator: {
    color: colors.foregroundMuted,
    fontSize: typography.sizeXs,
    fontWeight: typography.weightBold,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
  },
  readonlyRule: { alignItems: "baseline", display: "inline-flex", flexWrap: "wrap", gap: space.xs },
  readonlyAttribute: { fontWeight: typography.weightSemibold },
  readonlyOperator: { color: colors.foregroundMuted },
  readonlyValue: {
    backgroundColor: colors.surfaceSubtle,
    borderRadius: radii.sm,
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: typography.sizeXs,
    padding: `${space.xxs} ${space.xs}`,
  },
  responsiveRule: {
    gridTemplateColumns: {
      default: "minmax(140px, 1.15fr) minmax(120px, 0.9fr) minmax(150px, 1.4fr) auto",
      "@media (max-width: 760px)": "1fr",
    },
  },
  interactive: {
    transitionDuration: motion.fast,
    transitionTimingFunction: motion.easeOut,
  },
});
