import * as stylex from "@stylexjs/stylex";

import {
  colors,
  motion,
  radii,
  shadows,
  sizes,
  space,
  typography,
} from "@foldworks/ui/tokens.stylex";

const enter = stylex.keyframes({
  from: { opacity: 0, transform: "translateY(8px) scale(0.985)" },
  to: { opacity: 1, transform: "translateY(0) scale(1)" },
});

const fade = stylex.keyframes({
  from: { opacity: 0, transform: "translateY(3px)" },
  to: { opacity: 1, transform: "translateY(0)" },
});

const pulse = stylex.keyframes({
  "0%": { boxShadow: "0 0 0 0 var(--foldworks-ui-focus-glow)" },
  "60%": { boxShadow: "0 0 0 6px transparent" },
  "100%": { boxShadow: "0 0 0 0 transparent" },
});

const reducedMotion = "@media (prefers-reduced-motion: reduce)" as const;

export const styles = stylex.create({
  editor: {
    color: colors.foreground,
    display: "flex",
    flexDirection: "column",
    fontFamily: typography.fontFamily,
    gap: space.md,
    minWidth: 0,
  },
  group: {
    animationDuration: { default: motion.slow, [reducedMotion]: "0ms" },
    animationFillMode: "both",
    animationName: { default: enter, [reducedMotion]: "none" },
    animationTimingFunction: motion.spring,
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.lg,
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: shadows.sm,
    display: "flex",
    flexDirection: "column",
    gap: space.md,
    minWidth: 0,
    padding: space.md,
    position: "relative",
  },
  nestedGroup: {
    backgroundColor: colors.surfaceSubtle,
    borderColor: { default: colors.borderStrong, ":hover": colors.brandBorder },
    boxShadow: "none",
    marginLeft: space.lg,
    transitionDuration: motion.normal,
    transitionProperty: "border-color, box-shadow",
    transitionTimingFunction: motion.easeOut,
  },
  nestedRail: {
    backgroundColor: colors.brand,
    borderRadius: radii.full,
    bottom: space.md,
    left: "-1px",
    opacity: 0.55,
    position: "absolute",
    top: space.md,
    width: "2px",
  },
  groupHeader: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: space.sm,
    justifyContent: "space-between",
  },
  groupLead: { alignItems: "center", display: "flex", flexWrap: "wrap", gap: space.sm },
  groupIcon: {
    alignItems: "center",
    backgroundColor: colors.brandSurface,
    borderColor: colors.brandBorder,
    borderRadius: radii.md,
    borderStyle: "solid",
    borderWidth: "1px",
    color: colors.brandForeground,
    display: "inline-flex",
    height: "28px",
    justifyContent: "center",
    width: "28px",
  },
  groupLabel: {
    color: colors.foregroundMuted,
    fontSize: typography.sizeXs,
    fontWeight: typography.weightSemibold,
    letterSpacing: "0.055em",
    textTransform: "uppercase",
  },
  groupActions: { alignItems: "center", display: "flex", flexWrap: "wrap", gap: space.xs },
  combinatorControl: {
    alignItems: "center",
    backgroundColor: colors.surfaceSubtle,
    borderColor: colors.border,
    borderRadius: radii.md,
    borderStyle: "solid",
    borderWidth: "1px",
    display: "inline-flex",
    gap: space.xxs,
    padding: space.xxs,
  },
  combinatorButton: {
    backgroundColor: { default: "transparent", ":hover": colors.surfaceHover },
    border: 0,
    borderRadius: radii.sm,
    color: colors.foregroundMuted,
    cursor: "pointer",
    fontFamily: typography.fontFamily,
    fontSize: typography.sizeXs,
    fontWeight: typography.weightSemibold,
    height: "25px",
    minWidth: "38px",
    outline: { default: "none", ":focus-visible": `2px solid ${colors.focus}` },
    outlineOffset: "1px",
    paddingLeft: space.sm,
    paddingRight: space.sm,
    transform: { default: "scale(1)", ":active": "scale(0.95)" },
    transitionDuration: motion.fast,
    transitionProperty: "background-color, box-shadow, color, transform",
    transitionTimingFunction: motion.easeOut,
  },
  combinatorActive: {
    backgroundColor: colors.surface,
    boxShadow: shadows.control,
    color: colors.brandForeground,
  },
  children: { display: "flex", flexDirection: "column", gap: space.sm, minWidth: 0 },
  empty: {
    alignItems: "center",
    backgroundColor: { default: "transparent", ":hover": colors.brandSurface },
    borderColor: { default: colors.borderStrong, ":hover": colors.brandBorder },
    borderRadius: radii.md,
    borderStyle: "dashed",
    borderWidth: "1px",
    color: colors.foregroundMuted,
    display: "flex",
    fontSize: typography.sizeSm,
    justifyContent: "center",
    minHeight: "62px",
    padding: space.md,
    transitionDuration: motion.normal,
    transitionProperty: "background-color, border-color, color",
    transitionTimingFunction: motion.easeOut,
  },
  rule: {
    alignItems: "center",
    animationDuration: { default: motion.slow, [reducedMotion]: "0ms" },
    animationFillMode: "both",
    animationName: { default: enter, [reducedMotion]: "none" },
    animationTimingFunction: motion.spring,
    backgroundColor: colors.background,
    borderColor: {
      default: colors.border,
      ":hover": colors.brandBorder,
      ":focus-within": colors.brand,
    },
    borderRadius: radii.md,
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: {
      default: shadows.control,
      ":hover": shadows.interactive,
      ":focus-within": `0 0 0 3px ${colors.focusGlow}, ${shadows.interactive}`,
    },
    display: "grid",
    gap: space.sm,
    gridTemplateColumns: "minmax(140px, 1.15fr) minmax(120px, 0.9fr) minmax(150px, 1.4fr) auto",
    minWidth: 0,
    padding: space.sm,
    transform: {
      default: "translateY(0)",
      ":hover": "translateY(-1px)",
      ":focus-within": "translateY(-1px)",
    },
    transitionDuration: motion.normal,
    transitionProperty: "border-color, box-shadow, transform",
    transitionTimingFunction: motion.easeOut,
    willChange: "transform",
  },
  ruleInvalid: { borderColor: colors.dangerBorder },
  select: {
    backgroundColor: colors.surface,
    borderColor: {
      default: colors.input,
      ":hover": colors.borderStrong,
      ":focus": colors.brand,
    },
    borderRadius: radii.md,
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: { default: "none", ":hover": shadows.control },
    color: colors.foreground,
    cursor: "pointer",
    fontFamily: typography.fontFamily,
    fontSize: typography.sizeSm,
    height: sizes.controlSm,
    minWidth: 0,
    outline: { default: "none", ":focus-visible": `2px solid ${colors.focus}` },
    outlineOffset: "1px",
    paddingLeft: space.sm,
    paddingRight: space.xl,
    transitionDuration: motion.fast,
    transitionProperty: "background-color, border-color, box-shadow",
    transitionTimingFunction: motion.easeOut,
  },
  value: {
    backgroundColor: colors.surface,
    borderColor: {
      default: colors.input,
      ":hover": colors.borderStrong,
      ":focus": colors.brand,
    },
    borderRadius: radii.md,
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: { default: "none", ":hover": shadows.control },
    color: colors.foreground,
    fontFamily: typography.fontFamily,
    fontSize: typography.sizeSm,
    height: sizes.controlSm,
    minWidth: 0,
    outline: { default: "none", ":focus-visible": `2px solid ${colors.focus}` },
    outlineOffset: "1px",
    paddingLeft: space.sm,
    paddingRight: space.sm,
    transitionDuration: motion.fast,
    transitionProperty: "border-color, box-shadow",
    transitionTimingFunction: motion.easeOut,
    width: "100%",
  },
  invalidValue: { borderColor: colors.danger },
  hiddenValue: { color: colors.foregroundMuted, fontSize: typography.sizeSm, fontStyle: "italic" },
  removeButton: { color: { default: colors.foregroundSubtle, ":hover": colors.danger } },
  issue: {
    animationDuration: { default: motion.normal, [reducedMotion]: "0ms" },
    animationName: { default: fade, [reducedMotion]: "none" },
    color: colors.danger,
    fontSize: typography.sizeXs,
    gridColumn: "1 / -1",
    margin: 0,
  },
  summary: {
    alignItems: "center",
    animationDuration: { default: motion.normal, [reducedMotion]: "0ms" },
    animationName: { default: fade, [reducedMotion]: "none" },
    borderRadius: radii.full,
    color: colors.foregroundMuted,
    display: "inline-flex",
    fontSize: typography.sizeXs,
    fontWeight: typography.weightMedium,
    gap: space.sm,
    minHeight: "24px",
    paddingLeft: space.sm,
    paddingRight: space.sm,
    width: "fit-content",
  },
  summaryValid: { backgroundColor: colors.successSurface, color: colors.success },
  summaryInvalid: { backgroundColor: colors.dangerSurface, color: colors.danger },
  validDot: {
    animationDuration: { default: "1400ms", [reducedMotion]: "0ms" },
    animationIterationCount: { default: "infinite", [reducedMotion]: "1" },
    animationName: { default: pulse, [reducedMotion]: "none" },
    backgroundColor: colors.success,
    borderRadius: radii.full,
    height: "6px",
    width: "6px",
  },
  invalidDot: { backgroundColor: colors.danger, borderRadius: radii.full, height: "6px", width: "6px" },
  readonly: {
    alignItems: "center",
    animationDuration: { default: motion.normal, [reducedMotion]: "0ms" },
    animationFillMode: "both",
    animationName: { default: fade, [reducedMotion]: "none" },
    color: colors.foreground,
    display: "flex",
    flexWrap: "wrap",
    fontFamily: typography.fontFamily,
    fontSize: typography.sizeSm,
    gap: space.xs,
    lineHeight: typography.lineHeightNormal,
  },
  readonlyGroup: { alignItems: "center", display: "inline-flex", flexWrap: "wrap", gap: space.xs },
  readonlyNested: {
    backgroundColor: colors.brandSurface,
    borderColor: colors.brandBorder,
    borderRadius: radii.md,
    borderStyle: "solid",
    borderWidth: "1px",
    padding: `${space.xs} ${space.sm}`,
  },
  readonlyCombinator: {
    color: colors.brandForeground,
    fontSize: typography.sizeXs,
    fontWeight: typography.weightBold,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
  },
  readonlyRule: { alignItems: "baseline", display: "inline-flex", flexWrap: "wrap", gap: space.xs },
  readonlyAttribute: { fontWeight: typography.weightSemibold },
  readonlyOperator: { color: colors.foregroundMuted },
  readonlyValue: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.sm,
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: shadows.sm,
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: typography.sizeXs,
    padding: `${space.xxs} ${space.xs}`,
  },
  responsiveRule: {
    gridTemplateColumns: {
      default: "minmax(140px, 1.15fr) minmax(120px, 0.9fr) minmax(150px, 1.4fr) auto",
      "@media (max-width: 760px)": "1fr",
    },
  },
});
