import * as stylex from "@stylexjs/stylex";

export const className = (...values: ReadonlyArray<stylex.StyleXStyles>) =>
  stylex.props(...values).className ?? "";

export const nodeTransitionClass = stylex.viewTransitionClass({
  group: {
    animationDuration: "260ms",
    animationTimingFunction: "cubic-bezier(0.22, 1, 0.36, 1)",
  },
});

export const styles = stylex.create({
  app: {
    backgroundColor: "#f4f5f7",
    color: "#1b2230",
    display: "grid",
    fontFamily:
      'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    gridTemplateColumns: {
      default: "272px minmax(0, 1fr)",
      "@media (max-width: 820px)": "1fr",
    },
    height: "100vh",
    overflow: "hidden",
  },
  palette: {
    backgroundColor: "#111827",
    color: "#ffffff",
    display: {
      default: "flex",
      "@media (max-width: 820px)": "none",
    },
    flexDirection: "column",
    minHeight: 0,
    overflowY: "auto",
    padding: "24px 18px",
    zIndex: 4,
  },
  brandRow: {
    alignItems: "center",
    display: "flex",
    gap: "10px",
    marginBottom: "28px",
    paddingLeft: "6px",
  },
  brandMark: {
    alignItems: "center",
    backgroundColor: "#9df2cf",
    borderRadius: "10px",
    color: "#0e3427",
    display: "flex",
    fontSize: "18px",
    fontWeight: 800,
    height: "34px",
    justifyContent: "center",
    width: "34px",
  },
  brand: {
    fontSize: "15px",
    fontWeight: 750,
    letterSpacing: "-0.01em",
    margin: 0,
  },
  paletteLabel: {
    color: "#8792a7",
    fontSize: "11px",
    fontWeight: 750,
    letterSpacing: "0.12em",
    marginBottom: "10px",
    marginTop: 0,
    paddingLeft: "6px",
    textTransform: "uppercase",
  },
  paletteList: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    margin: 0,
    padding: 0,
  },
  paletteItem: {
    alignItems: "center",
    backgroundColor: {
      default: "rgba(255, 255, 255, 0.055)",
      ":hover": "rgba(255, 255, 255, 0.1)",
    },
    borderColor: {
      default: "rgba(255, 255, 255, 0.08)",
      ":hover": "rgba(157, 242, 207, 0.45)",
    },
    borderRadius: "12px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "#ffffff",
    cursor: "grab",
    display: "grid",
    gap: "11px",
    gridTemplateColumns: "34px 1fr 16px",
    minHeight: "58px",
    outline: {
      default: "none",
      ":focus-visible": "3px solid #9df2cf",
    },
    outlineOffset: "2px",
    padding: "9px 10px",
    transitionDuration: "150ms",
    transitionProperty: "background-color, border-color, transform",
    transitionTimingFunction: "ease-out",
    transform: {
      default: "translateX(0)",
      ":hover": "translateX(2px)",
      ":active": "scale(0.99)",
    },
  },
  paletteItemDragging: {
    opacity: 0.42,
  },
  paletteIcon: {
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: "9px",
    display: "flex",
    fontSize: "16px",
    fontWeight: 800,
    height: "34px",
    justifyContent: "center",
    width: "34px",
  },
  paletteName: {
    fontSize: "13px",
    fontWeight: 700,
    margin: 0,
  },
  paletteDescription: {
    color: "#9aa4b7",
    fontSize: "11px",
    lineHeight: 1.35,
    marginBottom: 0,
    marginTop: "2px",
  },
  paletteHandle: {
    color: "#667085",
    fontSize: "15px",
    letterSpacing: "-2px",
  },
  paletteHint: {
    borderColor: "rgba(255, 255, 255, 0.09)",
    borderStyle: "solid",
    borderWidth: "1px 0 0",
    color: "#7d899e",
    fontSize: "11px",
    lineHeight: 1.5,
    marginBottom: 0,
    marginTop: "auto",
    padding: "20px 6px 0",
  },
  workspace: {
    display: "grid",
    gridTemplateRows: "72px minmax(0, 1fr)",
    minHeight: 0,
    minWidth: 0,
  },
  toolbar: {
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.94)",
    borderBottomColor: "#e1e5ea",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    display: "flex",
    gap: "16px",
    justifyContent: "space-between",
    padding: "0 24px",
    zIndex: 3,
  },
  toolbarTitle: {
    fontSize: "16px",
    fontWeight: 760,
    letterSpacing: "-0.02em",
    margin: 0,
  },
  toolbarMeta: {
    color: "#758093",
    fontSize: "12px",
    marginBottom: 0,
    marginTop: "3px",
  },
  toolbarActions: {
    alignItems: "center",
    display: "flex",
    gap: "10px",
  },
  status: {
    alignItems: "center",
    backgroundColor: "#eefbf5",
    borderRadius: "999px",
    color: "#1a7455",
    display: "flex",
    fontSize: "12px",
    fontWeight: 700,
    gap: "7px",
    padding: "7px 11px",
  },
  statusDot: {
    backgroundColor: "#39b783",
    borderRadius: "999px",
    height: "7px",
    width: "7px",
  },
  quietButton: {
    backgroundColor: {
      default: "#ffffff",
      ":hover": "#f3f5f7",
    },
    borderColor: "#d8dde4",
    borderRadius: "9px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "#505a6b",
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: "12px",
    fontWeight: 700,
    minHeight: "36px",
    outline: {
      default: "none",
      ":focus-visible": "3px solid #77bda2",
    },
    outlineOffset: "2px",
    paddingLeft: "13px",
    paddingRight: "13px",
  },
  canvasViewport: {
    backgroundColor: "#f8fafc",
    backgroundImage:
      "radial-gradient(circle, rgba(148, 163, 184, 0.32) 1px, transparent 1px)",
    backgroundPosition: "0 0",
    backgroundSize: "12px 12px",
    minHeight: 0,
    overflow: "auto",
    position: "relative",
  },
  canvas: {
    marginLeft: "auto",
    marginRight: "auto",
    position: "relative",
  },
  edgeLayer: {
    inset: 0,
    overflow: "visible",
    pointerEvents: "none",
    position: "absolute",
  },
  edgePath: {
    fill: "none",
    stroke: "#cbd3dd",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    strokeWidth: 1.5,
    transitionDuration: "240ms",
    transitionProperty: "opacity, stroke, d",
    transitionTimingFunction: "cubic-bezier(0.22, 1, 0.36, 1)",
  },
  edgePathActive: {
    stroke: "#32d89b",
    strokeWidth: 2.5,
  },
  junction: {
    fill: "#ffffff",
    stroke: "#cbd3dd",
    strokeWidth: 1.5,
  },
  branchLabel: {
    backgroundColor: "#ffffff",
    borderColor: "#e0e5eb",
    borderRadius: "999px",
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: "0 2px 7px rgba(40, 51, 66, 0.06)",
    color: "#394355",
    fontSize: "10px",
    fontWeight: 750,
    minWidth: "62px",
    padding: "4px 10px",
    pointerEvents: "none",
    position: "absolute",
    textAlign: "center",
    transform: "translate(-50%, -50%)",
    whiteSpace: "nowrap",
    zIndex: 2,
  },
  edgeLabel: {
    backgroundColor: "#ffffff",
    borderColor: "#dce1e7",
    borderRadius: "999px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "#717c8e",
    fontSize: "10px",
    fontWeight: 700,
    left: 0,
    padding: "3px 7px",
    pointerEvents: "none",
    position: "absolute",
    top: 0,
    transform: "translate(-50%, -50%)",
    whiteSpace: "nowrap",
    zIndex: 1,
  },
  edgeTargetZone: {
    alignItems: "center",
    display: "flex",
    height: "54px",
    justifyContent: "center",
    left: 0,
    position: "absolute",
    top: 0,
    transform: "translate(-50%, -50%)",
    width: "72px",
    zIndex: 3,
  },
  edgeTarget: {
    alignItems: "center",
    backgroundColor: {
      default: "rgba(255, 255, 255, 0.82)",
      ":hover": "#173f34",
    },
    borderColor: {
      default: "#b8c1cc",
      ":hover": "#173f34",
    },
    borderRadius: "999px",
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: "0 3px 10px rgba(20, 31, 44, 0.09)",
    color: {
      default: "#526071",
      ":hover": "#ffffff",
    },
    cursor: "pointer",
    display: "flex",
    fontFamily: "inherit",
    fontSize: "17px",
    fontWeight: 500,
    height: "28px",
    justifyContent: "center",
    opacity: {
      default: 0.2,
      ":hover": 1,
      ":focus-visible": 1,
    },
    outline: {
      default: "none",
      ":focus-visible": "3px solid #77bda2",
    },
    outlineOffset: "3px",
    transform: "scale(0.9)",
    transitionDuration: "160ms",
    transitionProperty: "opacity, transform, background-color, border-color",
    transitionTimingFunction: "cubic-bezier(0.22, 1, 0.36, 1)",
    width: "28px",
    zIndex: 2,
  },
  edgeTargetDragging: {
    backgroundColor: "#effaf5",
    borderColor: "#74c7a8",
    color: "#20684f",
    height: "34px",
    opacity: 0.88,
    transform: "scale(1)",
    width: "34px",
  },
  edgeTargetActive: {
    backgroundColor: {
      default: "#173f34",
      ":hover": "#173f34",
    },
    borderColor: {
      default: "#173f34",
      ":hover": "#173f34",
    },
    boxShadow: "0 0 0 7px rgba(57, 183, 131, 0.18), 0 8px 20px rgba(20, 43, 35, 0.2)",
    color: {
      default: "#ffffff",
      ":hover": "#ffffff",
    },
    height: "40px",
    opacity: 1,
    transform: "scale(1.06)",
    width: "40px",
  },
  node: {
    backgroundColor: "#ffffff",
    borderColor: "#e1e6ec",
    borderRadius: "10px",
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: "0 5px 16px rgba(30, 42, 56, 0.08)",
    color: "#19212d",
    cursor: "grab",
    display: "block",
    left: 0,
    outline: {
      default: "none",
      ":focus-visible": "3px solid #6fc6a4",
    },
    outlineOffset: "3px",
    padding: 0,
    position: "absolute",
    textAlign: "left",
    top: 0,
    transitionDuration: "220ms",
    transitionProperty: "transform, opacity, box-shadow, border-color",
    transitionTimingFunction: "cubic-bezier(0.22, 1, 0.36, 1)",
    userSelect: "none",
    willChange: "transform",
    zIndex: 2,
  },
  nodeCompact: {
    borderRadius: "9px",
  },
  nodeHoverable: {
    boxShadow: {
      default: "0 5px 16px rgba(30, 42, 56, 0.08)",
      ":hover": "0 10px 24px rgba(30, 42, 56, 0.13)",
    },
    borderColor: {
      default: "#d9dee5",
      ":hover": "#aab6c3",
    },
  },
  nodeDragging: {
    backgroundColor: "rgba(255, 255, 255, 0.28)",
    borderColor: "#62aa8e",
    borderStyle: "dashed",
    boxShadow: "none",
    opacity: 1,
  },
  nodeDraggingContent: {
    opacity: 0,
  },
  nodeSelected: {
    borderColor: "#32dfa2",
    boxShadow: "0 0 0 2px rgba(50, 223, 162, 0.18), 0 10px 24px rgba(30, 42, 56, 0.1)",
  },
  nodePreview: {
    borderColor: "#39b783",
    borderStyle: "dashed",
    opacity: 0.78,
  },
  nodeHeader: {
    alignItems: "center",
    display: "flex",
    justifyContent: "space-between",
    minHeight: "34px",
    padding: "7px 10px 6px",
  },
  nodeHeaderCompact: {
    height: "36px",
    minHeight: "36px",
    paddingBottom: "5px",
    paddingTop: "5px",
  },
  nodeIdentity: {
    alignItems: "center",
    display: "inline-flex",
    gap: "7px",
  },
  nodeIcon: {
    alignItems: "center",
    borderRadius: "5px",
    display: "inline-flex",
    fontSize: "10px",
    fontWeight: 800,
    height: "18px",
    justifyContent: "center",
    width: "18px",
  },
  nodeRemoveHint: {
    alignItems: "center",
    backgroundColor: "#f2f4f7",
    borderRadius: "5px",
    color: "#b1bac6",
    display: "inline-flex",
    fontSize: "13px",
    height: "17px",
    justifyContent: "center",
    width: "17px",
  },
  nodeTitle: {
    color: "#202938",
    fontSize: "11px",
    fontWeight: 750,
    letterSpacing: "-0.005em",
    lineHeight: 1.2,
  },
  nodeDescription: {
    borderTopColor: "#edf0f3",
    borderTopStyle: "solid",
    borderTopWidth: "1px",
    color: "#a0a9b5",
    fontSize: "9px",
    lineHeight: "20px",
    margin: 0,
    overflow: "hidden",
    paddingLeft: "10px",
    paddingRight: "10px",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  ports: {
    alignItems: "center",
    display: "flex",
    justifyContent: "space-between",
    marginTop: "8px",
  },
  portLabel: {
    color: "#a0a8b5",
    fontSize: "9px",
    fontWeight: 700,
  },
  portDot: {
    backgroundColor: "#ffffff",
    borderColor: "#9aa7b7",
    borderRadius: "999px",
    borderStyle: "solid",
    borderWidth: "2px",
    height: "9px",
    left: "50%",
    position: "absolute",
    transform: "translateX(-50%)",
    width: "9px",
    zIndex: 2,
  },
  portDotIn: {
    top: "-5px",
  },
  portDotOut: {
    bottom: "-5px",
  },
  ghost: {
    backgroundColor: "#ffffff",
    borderColor: "#4aae88",
    borderRadius: "10px",
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: "0 20px 45px rgba(20, 43, 35, 0.22)",
    alignItems: "center",
    display: "flex",
    minHeight: "44px",
    padding: "10px 12px",
    pointerEvents: "none",
    transform: "rotate(1.5deg) scale(1.02)",
    width: "252px",
    zIndex: 100,
  },
  ghostTitle: {
    fontSize: "13px",
    fontWeight: 750,
    marginBottom: 0,
    marginTop: "8px",
  },
  srOnly: {
    clip: "rect(0, 0, 0, 0)",
    height: "1px",
    margin: "-1px",
    overflow: "hidden",
    padding: 0,
    position: "absolute",
    whiteSpace: "nowrap",
    width: "1px",
  },
  dialog: {
    backgroundColor: "transparent",
    borderWidth: 0,
    height: "100%",
    inset: 0,
    margin: 0,
    maxHeight: "none",
    maxWidth: "none",
    overflow: "hidden",
    padding: 0,
    width: "100%",
  },
  backdrop: {
    backgroundColor: "rgba(14, 21, 31, 0.3)",
    inset: 0,
    opacity: {
      default: 1,
      ":is([data-closed])": 0,
    },
    position: "fixed",
    transitionDuration: "200ms",
    transitionProperty: "opacity",
    zIndex: 0,
  },
  sheet: {
    backgroundColor: "#ffffff",
    borderLeftColor: "#dfe3e8",
    borderLeftStyle: "solid",
    borderLeftWidth: "1px",
    boxShadow: "-24px 0 60px rgba(20, 28, 40, 0.16)",
    display: "flex",
    flexDirection: "column",
    height: "100%",
    maxWidth: "420px",
    overflowY: "auto",
    position: "fixed",
    right: 0,
    top: 0,
    transform: {
      default: "translateX(0)",
      ":is([data-closed])": "translateX(100%)",
    },
    transitionDuration: "260ms",
    transitionProperty: "transform",
    transitionTimingFunction: "cubic-bezier(0.22, 1, 0.36, 1)",
    width: "min(420px, 92vw)",
    zIndex: 1,
  },
  sheetHeader: {
    alignItems: "flex-start",
    borderBottomColor: "#e6e9ed",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    display: "flex",
    justifyContent: "space-between",
    padding: "25px 26px 20px",
  },
  sheetEyebrow: {
    color: "#278562",
    fontSize: "10px",
    fontWeight: 800,
    letterSpacing: "0.11em",
    marginBottom: "7px",
    marginTop: 0,
    textTransform: "uppercase",
  },
  sheetTitle: {
    fontSize: "21px",
    fontWeight: 780,
    letterSpacing: "-0.03em",
    margin: 0,
  },
  sheetDescription: {
    color: "#7d8796",
    fontSize: "12px",
    lineHeight: 1.5,
    marginBottom: 0,
    marginTop: "7px",
  },
  closeButton: {
    alignItems: "center",
    backgroundColor: {
      default: "#f4f6f8",
      ":hover": "#e8ecef",
    },
    borderWidth: 0,
    borderRadius: "9px",
    color: "#5c6675",
    cursor: "pointer",
    display: "flex",
    fontSize: "18px",
    height: "34px",
    justifyContent: "center",
    minWidth: "34px",
  },
  sheetBody: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
    padding: "24px 26px",
  },
  field: {
    display: "flex",
    flexDirection: "column",
    gap: "7px",
  },
  label: {
    color: "#4b5565",
    fontSize: "12px",
    fontWeight: 750,
  },
  input: {
    backgroundColor: "#ffffff",
    borderColor: {
      default: "#d7dce3",
      ":focus": "#3d9b77",
    },
    borderRadius: "10px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "#1f2732",
    cursor: {
      default: "auto",
      ":disabled": "not-allowed",
    },
    fontFamily: "inherit",
    fontSize: "13px",
    minHeight: "42px",
    outline: "none",
    paddingLeft: "12px",
    paddingRight: "12px",
    opacity: {
      default: 1,
      ":disabled": 0.62,
    },
    width: "100%",
  },
  textarea: {
    lineHeight: 1.5,
    minHeight: "96px",
    paddingBottom: "10px",
    paddingTop: "10px",
    resize: "vertical",
  },
  fieldGrid: {
    display: "grid",
    gap: "14px",
    gridTemplateColumns: "1fr 1fr",
  },
  sheetNote: {
    backgroundColor: "#f5f8f7",
    borderColor: "#dce9e4",
    borderRadius: "11px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "#657269",
    fontSize: "11px",
    lineHeight: 1.5,
    margin: 0,
    padding: "11px 12px",
  },
  deleteButton: {
    backgroundColor: {
      default: "#ffffff",
      ":hover": "#fff1f0",
    },
    borderColor: "#e5b9b6",
    borderRadius: "10px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "#b13e37",
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: "12px",
    fontWeight: 750,
    minHeight: "40px",
    width: "100%",
  },
});

export const kindStyles = stylex.create({
  start: { backgroundColor: "#eef2f6", color: "#667386" },
  action: { backgroundColor: "#eef2f6", color: "#667386" },
  approval: { backgroundColor: "#f3ecff", color: "#7951ae" },
  condition: { backgroundColor: "#eef2f6", color: "#667386" },
  delay: { backgroundColor: "#f5eef9", color: "#87569d" },
  switch: { backgroundColor: "#eef2f6", color: "#667386" },
  end: { backgroundColor: "#eef2f6", color: "#667386" },
});
