import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  provider: {
    backgroundColor: "var(--sidebar)",
    color: "var(--sidebar-foreground)",
    display: "grid",
    fontFamily: "var(--font-sans)",
    gridTemplateColumns: {
      default: "256px minmax(0, 1fr)",
      "@media (max-width: 820px)": "minmax(0, 1fr)",
    },
    height: "100%",
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
    position: "relative",
    transitionDuration: "var(--duration-normal)",
    transitionProperty: "grid-template-columns",
    transitionTimingFunction: "var(--ease-out)",
    width: "100%",
  },
  providerCollapsed: {
    gridTemplateColumns: {
      default: "60px minmax(0, 1fr)",
      "@media (max-width: 820px)": "minmax(0, 1fr)",
    },
  },
  providerOffcanvasCollapsed: {
    gridTemplateColumns: {
      default: "0 minmax(0, 1fr)",
      "@media (max-width: 820px)": "minmax(0, 1fr)",
    },
  },
  desktopSidebar: {
    display: {
      default: "flex",
      "@media (max-width: 820px)": "none",
    },
    flexDirection: "column",
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
    position: "relative",
  },
  desktopOffcanvasClosed: { visibility: "hidden" },
  sidebarHeader: { flexShrink: 0, padding: "12px 10px 8px" },
  brand: {
    alignItems: "center",
    borderRadius: "var(--radius-lg)",
    color: "var(--sidebar-foreground)",
    display: "flex",
    gap: "10px",
    minHeight: "42px",
    outline: { default: "none", ":focus-visible": "3px solid var(--sidebar-ring)" },
    overflow: "hidden",
    padding: "5px 7px",
    textDecoration: "none",
  },
  brandIcon: {
    alignItems: "center",
    backgroundColor: "var(--sidebar-primary)",
    borderRadius: "var(--radius-lg)",
    color: "var(--sidebar-primary-foreground)",
    display: "flex",
    flexShrink: 0,
    height: "30px",
    justifyContent: "center",
    width: "30px",
  },
  brandCopy: { display: "grid", gap: "1px", minWidth: 0 },
  brandTitle: { fontSize: "13px", fontWeight: 700, lineHeight: 1.3, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  brandDescription: { color: "var(--muted-foreground)", fontSize: "11px", lineHeight: 1.3, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  collapsedCopy: { display: "none" },
  content: { display: "flex", flex: 1, flexDirection: "column", gap: "14px", minHeight: 0, overflowX: "hidden", overflowY: "auto", padding: "10px" },
  group: { display: "grid", gap: "4px" },
  groupLabel: { color: "var(--muted-foreground)", fontSize: "10px", fontWeight: 650, letterSpacing: "0.07em", minHeight: "22px", overflow: "hidden", padding: "3px 8px", textTransform: "uppercase", whiteSpace: "nowrap" },
  collapsedGroupLabel: { borderTopColor: "var(--sidebar-border)", borderTopStyle: "solid", borderTopWidth: "1px", fontSize: 0, margin: "4px 7px 5px", minHeight: 0, padding: 0 },
  menu: { display: "grid", gap: "3px", listStyle: "none", margin: 0, padding: 0 },
  menuItem: { minWidth: 0 },
  menuLink: {
    alignItems: "center",
    backgroundColor: { default: "transparent", ":hover": "var(--sidebar-accent)" },
    borderRadius: "var(--radius-lg)",
    color: { default: "var(--sidebar-foreground)", ":hover": "var(--sidebar-accent-foreground)" },
    display: "grid",
    fontSize: "13px",
    fontWeight: 550,
    gap: "9px",
    gridTemplateColumns: "18px minmax(0, 1fr) auto",
    minHeight: "34px",
    outline: { default: "none", ":focus-visible": "3px solid var(--sidebar-ring)" },
    padding: "6px 8px",
    textDecoration: "none",
    transitionDuration: "var(--duration-fast)",
    transitionProperty: "background-color, color, transform",
    transitionTimingFunction: "var(--ease-out)",
  },
  menuLinkActive: { backgroundColor: "var(--sidebar-accent)", color: "var(--sidebar-accent-foreground)", fontWeight: 650 },
  collapsedMenuLink: { display: "flex", justifyContent: "center", paddingLeft: 0, paddingRight: 0 },
  menuIcon: { alignItems: "center", display: "flex", flexShrink: 0, justifyContent: "center" },
  menuLabel: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  badge: { backgroundColor: "var(--sidebar-accent)", borderRadius: "999px", color: "var(--sidebar-accent-foreground)", fontSize: "10px", fontWeight: 650, padding: "1px 6px" },
  submenu: { borderLeftColor: "var(--sidebar-border)", borderLeftStyle: "solid", borderLeftWidth: "1px", display: "grid", gap: "2px", listStyle: "none", margin: "2px 0 4px 17px", padding: "2px 0 2px 12px" },
  submenuHidden: { display: "none" },
  submenuLink: { borderRadius: "var(--radius-md)", color: "var(--muted-foreground)", display: "block", fontSize: "12px", outline: { default: "none", ":focus-visible": "3px solid var(--sidebar-ring)" }, padding: "5px 8px", textDecoration: "none" },
  submenuLinkActive: { backgroundColor: "var(--sidebar-accent)", color: "var(--sidebar-accent-foreground)", fontWeight: 600 },
  sidebarFooter: { borderTopColor: "var(--sidebar-border)", borderTopStyle: "solid", borderTopWidth: "1px", flexShrink: 0, margin: "0 10px", padding: "10px 0 12px" },
  identity: { alignItems: "center", display: "flex", gap: "9px", minHeight: "38px", overflow: "hidden", padding: "4px 7px" },
  identityIcon: { alignItems: "center", backgroundColor: "var(--sidebar-accent)", borderRadius: "var(--radius-lg)", color: "var(--sidebar-accent-foreground)", display: "flex", flexShrink: 0, height: "28px", justifyContent: "center", width: "28px" },
  rail: {
    backgroundColor: { default: "transparent", ":hover": "var(--sidebar-border)" },
    border: 0,
    cursor: "col-resize",
    height: "100%",
    padding: 0,
    position: "absolute",
    right: 0,
    top: 0,
    width: "5px",
  },
  inset: {
    backgroundColor: "var(--background)",
    borderColor: "var(--sidebar-border)",
    borderRadius: {
      default: "var(--radius-xl)",
      "@media (max-width: 820px)": 0,
    },
    borderStyle: "solid",
    borderWidth: {
      default: "1px",
      "@media (max-width: 820px)": 0,
    },
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr)",
    margin: {
      default: "8px 8px 8px 0",
      "@media (max-width: 820px)": 0,
    },
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
  },
  insetFlat: { borderRadius: 0, borderWidth: 0, margin: 0 },
  topbar: { display: "grid", gridTemplateColumns: "auto minmax(0, 1fr)", minWidth: 0 },
  triggerCell: { alignItems: "center", backgroundColor: "var(--background)", borderBottomColor: "var(--border)", borderBottomStyle: "solid", borderBottomWidth: "1px", display: "flex", paddingLeft: "12px" },
  trigger: {
    alignItems: "center",
    backgroundColor: { default: "transparent", ":hover": "var(--accent)" },
    border: 0,
    borderRadius: "var(--radius-md)",
    color: "var(--foreground)",
    cursor: "pointer",
    display: "flex",
    height: "32px",
    justifyContent: "center",
    outline: { default: "none", ":focus-visible": "3px solid var(--ring)" },
    padding: 0,
    width: "32px",
  },
  desktopTrigger: { display: { default: "flex", "@media (max-width: 820px)": "none" } },
  mobileTrigger: { display: { default: "none", "@media (max-width: 820px)": "flex" } },
  headerSlot: { minWidth: 0 },
  main: {
    display: "grid",
    gridTemplateRows: "minmax(0, 1fr)",
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
  },
  overlay: {
    backgroundColor: "var(--foldworks-ui-overlay)",
    border: 0,
    display: { default: "none", "@media (max-width: 820px)": "block" },
    inset: 0,
    opacity: 0,
    padding: 0,
    pointerEvents: "none",
    position: "fixed",
    transitionDuration: "var(--duration-normal)",
    transitionProperty: "opacity",
    zIndex: 40,
  },
  overlayOpen: { opacity: 1, pointerEvents: "auto" },
  mobileSidebar: {
    backgroundColor: "var(--sidebar)",
    bottom: 0,
    boxShadow: "var(--shadow-sheet)",
    display: { default: "none", "@media (max-width: 820px)": "flex" },
    flexDirection: "column",
    left: 0,
    maxWidth: "calc(100vw - 48px)",
    position: "fixed",
    top: 0,
    transform: "translateX(-102%)",
    transitionDuration: "var(--duration-normal)",
    transitionProperty: "transform, visibility",
    transitionTimingFunction: "var(--ease-out)",
    visibility: "hidden",
    width: "280px",
    zIndex: 41,
  },
  mobileSidebarOpen: { transform: "translateX(0)", visibility: "visible" },
  mobileHeader: { alignItems: "center", display: "flex", justifyContent: "space-between" },
  mobileClose: { marginRight: "4px" },
  srOnly: { clip: "rect(0, 0, 0, 0)", clipPath: "inset(50%)", height: "1px", overflow: "hidden", position: "absolute", whiteSpace: "nowrap", width: "1px" },
});
