import * as stylex from "@stylexjs/stylex";
import { colors, radii, space, typography } from "@foldworks/ui/tokens.stylex";

export const coverageStyles = stylex.create({
  toolbar: {
    alignItems: "center",
    borderTopColor: colors.border,
    borderTopStyle: "solid",
    borderTopWidth: "1px",
    display: "flex",
    flexWrap: "wrap",
    gap: space.sm,
    padding: `${space.sm} ${space.md}`,
  },
  search: { flexBasis: "260px", flexGrow: 0, flexShrink: 1, minWidth: "180px" },
  spacer: { flexGrow: 1 },
  legend: {
    alignItems: "center",
    color: colors.foregroundMuted,
    display: "inline-flex",
    fontSize: typography.sizeXs,
    gap: space.md,
  },
  legendItem: { alignItems: "center", display: "inline-flex", gap: space.xs },
  swatch: {
    borderLeftStyle: "solid",
    borderLeftWidth: "3px",
    display: "inline-block",
    height: "12px",
    width: "14px",
  },
  swatchGap: { backgroundColor: colors.dangerSurface, borderLeftColor: colors.danger },
  swatchPartial: { backgroundColor: colors.warningSurface, borderLeftColor: colors.warning },
  label: { alignItems: "baseline", display: "flex", gap: space.sm, minWidth: 0 },
  labelText: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  code: {
    color: colors.foregroundMuted,
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: typography.sizeXs,
    fontWeight: typography.weightMedium,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  condition: { color: colors.foregroundMuted, fontWeight: 400 },
  muted: { color: colors.foregroundMuted, fontWeight: 400 },
  outcome: {
    borderRadius: radii.full,
    display: "inline-block",
    height: "9px",
    width: "9px",
  },
  Holds: { backgroundColor: colors.success },
  Fails: {
    borderColor: colors.borderStrong,
    borderStyle: "solid",
    borderWidth: "1.5px",
  },
  Skipped: {
    backgroundColor: colors.border,
    borderRadius: radii.full,
    height: "2px",
    width: "10px",
  },
  count: {
    alignItems: "center",
    display: "inline-flex",
    fontVariantNumeric: "tabular-nums",
    gap: space.sm,
  },
  bar: {
    backgroundColor: colors.surfaceSubtle,
    borderRadius: radii.full,
    height: "5px",
    overflow: "hidden",
    width: "54px",
  },
  barFill: { backgroundColor: colors.success, display: "block", height: "100%" },
  barFillGap: { backgroundColor: colors.danger },
  status: { fontSize: typography.sizeXs, fontWeight: typography.weightSemibold },
  statusGap: { color: colors.danger },
  statusPartial: { color: colors.warning },
  statusCovered: { color: colors.success },
  selection: {
    color: colors.foreground,
    fontWeight: typography.weightSemibold,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  tabs: {
    display: "inline-flex",
    gap: space.xxs,
    marginBottom: space.md,
    padding: space.xxs,
    backgroundColor: colors.surfaceSubtle,
    borderRadius: radii.md,
  },
  tab: {
    borderRadius: radii.sm,
    color: { default: colors.foregroundMuted, ":hover": colors.foreground },
    fontSize: typography.sizeSm,
    fontWeight: typography.weightMedium,
    padding: `${space.xs} ${space.md}`,
    textDecoration: "none",
    outline: { default: "none", ":focus-visible": `2px solid ${colors.focus}` },
  },
  tabActive: {
    backgroundColor: colors.surface,
    boxShadow: "var(--shadow-sm)",
    color: colors.foreground,
  },
});
