import * as stylex from "@stylexjs/stylex";

export const dataGridStyles = stylex.create({
  viewport: {
    backgroundColor: "var(--foldworks-ui-canvas)",
    minHeight: 0,
    overflow: "hidden",
    padding: {
      default: "24px",
      "@media (max-width: 820px)": "12px",
    },
  },
  card: {
    backgroundColor: "var(--foldworks-ui-surface)",
    borderColor: "var(--foldworks-ui-border)",
    borderRadius: "12px",
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: "var(--foldworks-ui-shadow-sm)",
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr) auto",
    height: "100%",
    minHeight: 0,
    overflow: "hidden",
  },
  cardHeader: {
    alignItems: "center",
    display: "flex",
    gap: "16px",
    justifyContent: "space-between",
    padding: "18px 20px 16px",
  },
  title: {
    color: "#1e2733",
    fontSize: "15px",
    fontWeight: 760,
    letterSpacing: "-0.015em",
    margin: 0,
  },
  description: {
    color: "#7a8493",
    fontSize: "12px",
    marginBottom: 0,
    marginTop: "4px",
  },
  rowCount: {
    backgroundColor: "#f1f5f3",
    borderRadius: "999px",
    color: "#477060",
    fontSize: "11px",
    fontWeight: 750,
    padding: "6px 10px",
    whiteSpace: "nowrap",
  },
  footer: {
    alignItems: "center",
    borderTopColor: "#e4e8ed",
    borderTopStyle: "solid",
    borderTopWidth: "1px",
    color: "#87919f",
    display: "flex",
    fontSize: "10px",
    justifyContent: "space-between",
    padding: "10px 14px",
  },
  person: {
    alignItems: "center",
    display: "flex",
    gap: "10px",
    minWidth: 0,
  },
  avatar: {
    alignItems: "center",
    backgroundColor: "#e8f4ef",
    borderRadius: "9px",
    color: "#287858",
    display: "flex",
    flexShrink: 0,
    fontSize: "10px",
    fontWeight: 800,
    height: "30px",
    justifyContent: "center",
    width: "30px",
  },
  personCopy: {
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
  },
  personName: {
    color: "#202936",
    fontSize: "12px",
    fontWeight: 700,
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  personEmail: {
    color: "#8a94a2",
    fontSize: "10px",
    marginTop: "2px",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  status: {
    alignItems: "center",
    borderRadius: "999px",
    display: "inline-flex",
    fontSize: "10px",
    fontWeight: 750,
    gap: "6px",
    padding: "5px 8px",
  },
  statusDot: {
    backgroundColor: "currentColor",
    borderRadius: "999px",
    height: "5px",
    width: "5px",
  },
  money: {
    fontVariantNumeric: "tabular-nums",
    fontWeight: 650,
  },
});

export const statusStyles = stylex.create({
  Active: { backgroundColor: "#eaf8f1", color: "#25815e" },
  "On leave": { backgroundColor: "#fff5dc", color: "#9a6a13" },
  Contractor: { backgroundColor: "#f1effb", color: "#6954a3" },
});
