import * as stylex from "@stylexjs/stylex";

export const dataGridStyles = stylex.create({
  viewport: {
    backgroundColor: "var(--foldworks-ui-canvas)",
    minHeight: 0,
    overflow: "hidden",
    padding: {
      default: "18px",
      "@media (max-width: 820px)": "10px",
    },
  },
  card: {
    backgroundColor: "var(--foldworks-ui-surface)",
    borderColor: "var(--foldworks-ui-border)",
    borderRadius: "8px",
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: "var(--foldworks-ui-shadow-sm)",
    display: "grid",
    gridTemplateRows: "auto auto minmax(0, 1fr) auto",
    height: "100%",
    minHeight: 0,
    overflow: "hidden",
  },
  cardHeader: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: "12px",
    justifyContent: "space-between",
    padding: "11px 14px",
  },
  title: {
    color: "var(--foldworks-ui-foreground)",
    fontSize: "14px",
    fontWeight: 760,
    letterSpacing: "-0.015em",
    margin: 0,
  },
  description: {
    color: "var(--foldworks-ui-foreground-muted)",
    fontSize: "12px",
    marginBottom: 0,
    marginTop: "2px",
  },
  saveBehavior: {
    alignItems: "center",
    color: "var(--foldworks-ui-foreground-muted)",
    display: "inline-flex",
    fontSize: "11px",
    gap: "7px",
    marginLeft: { default: "auto", "@media (max-width: 720px)": 0 },
    whiteSpace: "nowrap",
  },
  select: {
    backgroundColor: "var(--foldworks-ui-surface)",
    borderColor: "var(--foldworks-ui-border-strong)",
    borderRadius: "5px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--foldworks-ui-foreground)",
    fontFamily: "inherit",
    fontSize: "11px",
    height: "28px",
    padding: "0 24px 0 8px",
  },
  rowCount: {
    backgroundColor: "var(--foldworks-ui-surface-subtle)",
    borderRadius: "5px",
    color: "var(--foldworks-ui-foreground-muted)",
    fontSize: "11px",
    fontWeight: 750,
    padding: "5px 8px",
    whiteSpace: "nowrap",
  },
  formulaBar: {
    alignItems: "center",
    backgroundColor: "var(--foldworks-ui-surface)",
    borderBottomColor: "var(--foldworks-ui-border-strong)",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    borderTopColor: "var(--foldworks-ui-border)",
    borderTopStyle: "solid",
    borderTopWidth: "1px",
    display: "grid",
    gridTemplateColumns: "76px 38px minmax(0, 1fr)",
    height: "34px",
  },
  nameBox: {
    borderRightColor: "var(--foldworks-ui-border)",
    borderRightStyle: "solid",
    borderRightWidth: "1px",
    color: "var(--foldworks-ui-foreground)",
    fontSize: "11px",
    fontVariantNumeric: "tabular-nums",
    fontWeight: 700,
    padding: "0 12px",
  },
  formulaIcon: {
    color: "var(--foldworks-ui-foreground-muted)",
    fontFamily: "Georgia, serif",
    fontSize: "12px",
    fontStyle: "italic",
    textAlign: "center",
  },
  formulaValue: {
    borderLeftColor: "var(--foldworks-ui-border)",
    borderLeftStyle: "solid",
    borderLeftWidth: "1px",
    color: "var(--foldworks-ui-foreground)",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: "11px",
    overflow: "hidden",
    padding: "0 10px",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  footer: {
    alignItems: "center",
    borderTopColor: "var(--foldworks-ui-border)",
    borderTopStyle: "solid",
    borderTopWidth: "1px",
    color: "var(--foldworks-ui-foreground-muted)",
    display: "flex",
    flexWrap: "wrap",
    fontSize: "10px",
    gap: "14px",
    justifyContent: "space-between",
    padding: "0 10px",
    minHeight: "30px",
  },
  personName: {
    color: "var(--foldworks-ui-foreground)",
    fontWeight: 600,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  status: {
    alignItems: "center",
    display: "inline-flex",
    fontSize: "11px",
    gap: "6px",
  },
  statusDot: {
    backgroundColor: "currentColor",
    borderRadius: "999px",
    height: "5px",
    width: "5px",
  },
  money: {
    fontVariantNumeric: "tabular-nums",
  },
  sheetTab: {
    alignItems: "center",
    alignSelf: "stretch",
    borderBottomColor: "var(--foldworks-ui-primary)",
    borderBottomStyle: "solid",
    borderBottomWidth: "2px",
    color: "var(--foldworks-ui-foreground)",
    display: "inline-flex",
    fontWeight: 700,
    padding: "0 12px",
  },
});

export const statusStyles = stylex.create({
  Active: { color: "var(--foldworks-ui-success)" },
  "On leave": { color: "var(--foldworks-ui-warning)" },
  Contractor: { color: "var(--foldworks-ui-info)" },
});
